// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// This value set includes all SNOMED CT Additional Dosage Instructions.
  /// </summary>
  public static class AdditionalInstructionCodesCodes
  {
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HalfToOneHourBeforeFood = new Coding
    {
      Code = "311501008",
      Display = "Half to one hour before food",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding WithOrAfterFood = new Coding
    {
      Code = "311504000",
      Display = "With or after food",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Times = new Coding
    {
      Code = "417929005",
      Display = "Times",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ContainsAspirin = new Coding
    {
      Code = "417980006",
      Display = "Contains aspirin",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DissolveOrMixWithWaterBeforeTaking = new Coding
    {
      Code = "417995008",
      Display = "Dissolve or mix with water before taking",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding WarningCausesDrowsinessWhichMayContinueTheNextDayIfAffectedDoNotDriveOrOperateMachineryAvoidAlcoholicDrink = new Coding
    {
      Code = "418071006",
      Display = "Warning. Causes drowsiness which may continue the next day. If affected do not drive or operate machinery. Avoid alcoholic drink",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ContainsAnAspirinLikeMedicine = new Coding
    {
      Code = "418194009",
      Display = "Contains an aspirin-like medicine",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DoNotTakeAnythingContainingAspirinWhileTakingThisMedicine = new Coding
    {
      Code = "418281004",
      Display = "Do not take anything containing aspirin while taking this medicine",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DoNotTakeMoreThanIn24HoursOrInAnyOneWeek = new Coding
    {
      Code = "418443006",
      Display = "Do not take more than . . . in 24 hours or . . . in any one week",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding AvoidExposureOfSkinToDirectSunlightOrSunLamps = new Coding
    {
      Code = "418521000",
      Display = "Avoid exposure of skin to direct sunlight or sun lamps",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TakeAtRegularIntervalsCompleteThePrescribedCourseUnlessOtherwiseDirected = new Coding
    {
      Code = "418577003",
      Display = "Take at regular intervals. Complete the prescribed course unless otherwise directed",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DoNotTakeWithAnyOtherParacetamolProducts = new Coding
    {
      Code = "418637003",
      Display = "Do not take with any other paracetamol products",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding WarningMayCauseDrowsiness = new Coding
    {
      Code = "418639000",
      Display = "Warning. May cause drowsiness",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding SwallowedWholeNotChewed = new Coding
    {
      Code = "418693002",
      Display = "Swallowed whole, not chewed",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding WarningFollowThePrintedInstructionsYouHaveBeenGivenWithThisMedicine = new Coding
    {
      Code = "418849000",
      Display = "Warning. Follow the printed instructions you have been given with this medicine",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ContainsAspirinAndParacetamolDoNotTakeWithAnyOtherParacetamolProducts = new Coding
    {
      Code = "418850000",
      Display = "Contains aspirin and paracetamol. Do not take with any other paracetamol products",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding WarningMayCauseDrowsinessIfAffectedDoNotDriveOrOperateMachineryAvoidAlcoholicDrink = new Coding
    {
      Code = "418914006",
      Display = "Warning. May cause drowsiness. If affected do not drive or operate machinery. Avoid alcoholic drink",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding WarningMayCauseDrowsinessIfAffectedDoNotDriveOrOperateMachinery = new Coding
    {
      Code = "418954008",
      Display = "Warning. May cause drowsiness. If affected do not drive or operate machinery",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding SuckedOrChewed = new Coding
    {
      Code = "418991002",
      Display = "Sucked or chewed",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding AllowToDissolveUnderTheTongueDoNotTransferFromThisContainerKeepTightlyClosedDiscardEightWeeksAfterOpening = new Coding
    {
      Code = "419111009",
      Display = "Allow to dissolve under the tongue. Do not transfer from this container. Keep tightly closed. Discard eight weeks after opening",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DoNotTakeMilkIndigestionRemediesOrMedicinesContainingIronOrZincAtTheSameTimeOfDayAsThisMedicine = new Coding
    {
      Code = "419115000",
      Display = "Do not take milk, indigestion remedies, or medicines containing iron or zinc at the same time of day as this medicine",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding WithPlentyOfWater = new Coding
    {
      Code = "419303009",
      Display = "With plenty of water",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DoNotTakeMoreThan2AtAnyOneTimeDoNotTakeMoreThan8In24Hours = new Coding
    {
      Code = "419437002",
      Display = "Do not take more than 2 at any one time. Do not take more than 8 in 24 hours",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CautionFlammableKeepAwayFromFireOrFlames = new Coding
    {
      Code = "419439004",
      Display = "Caution flammable: keep away from fire or flames",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DoNotStopTakingThisMedicineExceptOnYourDoctorQuoteSAdvice = new Coding
    {
      Code = "419444006",
      Display = "Do not stop taking this medicine except on your doctor's advice",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Each = new Coding
    {
      Code = "419473009",
      Display = "Each",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding AdditionalDosageInstructions = new Coding
    {
      Code = "419492006",
      Display = "Additional dosage instructions",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DissolvedUnderTheTongue = new Coding
    {
      Code = "419529008",
      Display = "Dissolved under the tongue",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding WarningAvoidAlcoholicDrink = new Coding
    {
      Code = "419822006",
      Display = "Warning. Avoid alcoholic drink",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ThisMedicineMayColorTheUrine = new Coding
    {
      Code = "419974005",
      Display = "This medicine may color the urine",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DoNotTakeMoreThanIn24Hours = new Coding
    {
      Code = "420003005",
      Display = "Do not take more than . . . in 24 hours",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DoNotTakeIndigestionRemediesOrMedicinesContainingIronOrZincAtTheSameTimeOfDayAsThisMedicine = new Coding
    {
      Code = "420082003",
      Display = "Do not take indigestion remedies or medicines containing iron or zinc at the same time of day as this medicine",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DoNotTakeIndigestionRemediesAtTheSameTimeOfDayAsThisMedicine = new Coding
    {
      Code = "420110001",
      Display = "Do not take indigestion remedies at the same time of day as this medicine",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ToBeSpreadThinly = new Coding
    {
      Code = "420162004",
      Display = "To be spread thinly",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding UntilGone = new Coding
    {
      Code = "420652005",
      Display = "Until gone",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ThenDiscontinue = new Coding
    {
      Code = "421484000",
      Display = "Then discontinue",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding FollowDirections = new Coding
    {
      Code = "421769005",
      Display = "Follow directions",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding UntilFinished = new Coding
    {
      Code = "421984009",
      Display = "Until finished",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ThenStop = new Coding
    {
      Code = "422327006",
      Display = "Then stop",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding UseWithCaution = new Coding
    {
      Code = "428579001",
      Display = "Use with caution",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TakeOnAnEmptyStomach = new Coding
    {
      Code = "717154004",
      Display = "Take on an empty stomach",
      System = "http://snomed.info/sct"
    };

    /// <summary>
    /// Literal for code: HalfToOneHourBeforeFood
    /// </summary>
    public const string LiteralHalfToOneHourBeforeFood = "311501008";

    /// <summary>
    /// Literal for code: WithOrAfterFood
    /// </summary>
    public const string LiteralWithOrAfterFood = "311504000";

    /// <summary>
    /// Literal for code: Times
    /// </summary>
    public const string LiteralTimes = "417929005";

    /// <summary>
    /// Literal for code: ContainsAspirin
    /// </summary>
    public const string LiteralContainsAspirin = "417980006";

    /// <summary>
    /// Literal for code: DissolveOrMixWithWaterBeforeTaking
    /// </summary>
    public const string LiteralDissolveOrMixWithWaterBeforeTaking = "417995008";

    /// <summary>
    /// Literal for code: WarningCausesDrowsinessWhichMayContinueTheNextDayIfAffectedDoNotDriveOrOperateMachineryAvoidAlcoholicDrink
    /// </summary>
    public const string LiteralWarningCausesDrowsinessWhichMayContinueTheNextDayIfAffectedDoNotDriveOrOperateMachineryAvoidAlcoholicDrink = "418071006";

    /// <summary>
    /// Literal for code: ContainsAnAspirinLikeMedicine
    /// </summary>
    public const string LiteralContainsAnAspirinLikeMedicine = "418194009";

    /// <summary>
    /// Literal for code: DoNotTakeAnythingContainingAspirinWhileTakingThisMedicine
    /// </summary>
    public const string LiteralDoNotTakeAnythingContainingAspirinWhileTakingThisMedicine = "418281004";

    /// <summary>
    /// Literal for code: DoNotTakeMoreThanIn24HoursOrInAnyOneWeek
    /// </summary>
    public const string LiteralDoNotTakeMoreThanIn24HoursOrInAnyOneWeek = "418443006";

    /// <summary>
    /// Literal for code: AvoidExposureOfSkinToDirectSunlightOrSunLamps
    /// </summary>
    public const string LiteralAvoidExposureOfSkinToDirectSunlightOrSunLamps = "418521000";

    /// <summary>
    /// Literal for code: TakeAtRegularIntervalsCompleteThePrescribedCourseUnlessOtherwiseDirected
    /// </summary>
    public const string LiteralTakeAtRegularIntervalsCompleteThePrescribedCourseUnlessOtherwiseDirected = "418577003";

    /// <summary>
    /// Literal for code: DoNotTakeWithAnyOtherParacetamolProducts
    /// </summary>
    public const string LiteralDoNotTakeWithAnyOtherParacetamolProducts = "418637003";

    /// <summary>
    /// Literal for code: WarningMayCauseDrowsiness
    /// </summary>
    public const string LiteralWarningMayCauseDrowsiness = "418639000";

    /// <summary>
    /// Literal for code: SwallowedWholeNotChewed
    /// </summary>
    public const string LiteralSwallowedWholeNotChewed = "418693002";

    /// <summary>
    /// Literal for code: WarningFollowThePrintedInstructionsYouHaveBeenGivenWithThisMedicine
    /// </summary>
    public const string LiteralWarningFollowThePrintedInstructionsYouHaveBeenGivenWithThisMedicine = "418849000";

    /// <summary>
    /// Literal for code: ContainsAspirinAndParacetamolDoNotTakeWithAnyOtherParacetamolProducts
    /// </summary>
    public const string LiteralContainsAspirinAndParacetamolDoNotTakeWithAnyOtherParacetamolProducts = "418850000";

    /// <summary>
    /// Literal for code: WarningMayCauseDrowsinessIfAffectedDoNotDriveOrOperateMachineryAvoidAlcoholicDrink
    /// </summary>
    public const string LiteralWarningMayCauseDrowsinessIfAffectedDoNotDriveOrOperateMachineryAvoidAlcoholicDrink = "418914006";

    /// <summary>
    /// Literal for code: WarningMayCauseDrowsinessIfAffectedDoNotDriveOrOperateMachinery
    /// </summary>
    public const string LiteralWarningMayCauseDrowsinessIfAffectedDoNotDriveOrOperateMachinery = "418954008";

    /// <summary>
    /// Literal for code: SuckedOrChewed
    /// </summary>
    public const string LiteralSuckedOrChewed = "418991002";

    /// <summary>
    /// Literal for code: AllowToDissolveUnderTheTongueDoNotTransferFromThisContainerKeepTightlyClosedDiscardEightWeeksAfterOpening
    /// </summary>
    public const string LiteralAllowToDissolveUnderTheTongueDoNotTransferFromThisContainerKeepTightlyClosedDiscardEightWeeksAfterOpening = "419111009";

    /// <summary>
    /// Literal for code: DoNotTakeMilkIndigestionRemediesOrMedicinesContainingIronOrZincAtTheSameTimeOfDayAsThisMedicine
    /// </summary>
    public const string LiteralDoNotTakeMilkIndigestionRemediesOrMedicinesContainingIronOrZincAtTheSameTimeOfDayAsThisMedicine = "419115000";

    /// <summary>
    /// Literal for code: WithPlentyOfWater
    /// </summary>
    public const string LiteralWithPlentyOfWater = "419303009";

    /// <summary>
    /// Literal for code: DoNotTakeMoreThan2AtAnyOneTimeDoNotTakeMoreThan8In24Hours
    /// </summary>
    public const string LiteralDoNotTakeMoreThan2AtAnyOneTimeDoNotTakeMoreThan8In24Hours = "419437002";

    /// <summary>
    /// Literal for code: CautionFlammableKeepAwayFromFireOrFlames
    /// </summary>
    public const string LiteralCautionFlammableKeepAwayFromFireOrFlames = "419439004";

    /// <summary>
    /// Literal for code: DoNotStopTakingThisMedicineExceptOnYourDoctorQuoteSAdvice
    /// </summary>
    public const string LiteralDoNotStopTakingThisMedicineExceptOnYourDoctorQuoteSAdvice = "419444006";

    /// <summary>
    /// Literal for code: Each
    /// </summary>
    public const string LiteralEach = "419473009";

    /// <summary>
    /// Literal for code: AdditionalDosageInstructions
    /// </summary>
    public const string LiteralAdditionalDosageInstructions = "419492006";

    /// <summary>
    /// Literal for code: DissolvedUnderTheTongue
    /// </summary>
    public const string LiteralDissolvedUnderTheTongue = "419529008";

    /// <summary>
    /// Literal for code: WarningAvoidAlcoholicDrink
    /// </summary>
    public const string LiteralWarningAvoidAlcoholicDrink = "419822006";

    /// <summary>
    /// Literal for code: ThisMedicineMayColorTheUrine
    /// </summary>
    public const string LiteralThisMedicineMayColorTheUrine = "419974005";

    /// <summary>
    /// Literal for code: DoNotTakeMoreThanIn24Hours
    /// </summary>
    public const string LiteralDoNotTakeMoreThanIn24Hours = "420003005";

    /// <summary>
    /// Literal for code: DoNotTakeIndigestionRemediesOrMedicinesContainingIronOrZincAtTheSameTimeOfDayAsThisMedicine
    /// </summary>
    public const string LiteralDoNotTakeIndigestionRemediesOrMedicinesContainingIronOrZincAtTheSameTimeOfDayAsThisMedicine = "420082003";

    /// <summary>
    /// Literal for code: DoNotTakeIndigestionRemediesAtTheSameTimeOfDayAsThisMedicine
    /// </summary>
    public const string LiteralDoNotTakeIndigestionRemediesAtTheSameTimeOfDayAsThisMedicine = "420110001";

    /// <summary>
    /// Literal for code: ToBeSpreadThinly
    /// </summary>
    public const string LiteralToBeSpreadThinly = "420162004";

    /// <summary>
    /// Literal for code: UntilGone
    /// </summary>
    public const string LiteralUntilGone = "420652005";

    /// <summary>
    /// Literal for code: ThenDiscontinue
    /// </summary>
    public const string LiteralThenDiscontinue = "421484000";

    /// <summary>
    /// Literal for code: FollowDirections
    /// </summary>
    public const string LiteralFollowDirections = "421769005";

    /// <summary>
    /// Literal for code: UntilFinished
    /// </summary>
    public const string LiteralUntilFinished = "421984009";

    /// <summary>
    /// Literal for code: ThenStop
    /// </summary>
    public const string LiteralThenStop = "422327006";

    /// <summary>
    /// Literal for code: UseWithCaution
    /// </summary>
    public const string LiteralUseWithCaution = "428579001";

    /// <summary>
    /// Literal for code: TakeOnAnEmptyStomach
    /// </summary>
    public const string LiteralTakeOnAnEmptyStomach = "717154004";
  };
}
