// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// Used to express the reason and specific aspect for the variant title, such as language and specific language.
  /// </summary>
  public static class AlternativeTitleTypeCodes
  {
    /// <summary>
    /// Alternative form of title or abstract is a different language, language element codes the language into which it was translated by machine.
    /// </summary>
    public static readonly Coding DifferentLanguageDerivedFromAutotranslation = new Coding
    {
      Code = "autotranslated",
      Display = "Different language derived from autotranslation",
      System = "http://terminology.hl7.org/CodeSystem/alternative-title-type"
    };
    /// <summary>
    /// Alternative form of title or abstract  in two or more Medline entries.
    /// </summary>
    public static readonly Coding DifferentTextInAdditionalMedlineEntry = new Coding
    {
      Code = "duplicatePmid",
      Display = "Different text in additional Medline entry",
      System = "http://terminology.hl7.org/CodeSystem/alternative-title-type"
    };
    /// <summary>
    /// Alternative form of title or abstract in an earlier version such as epub ahead of print.
    /// </summary>
    public static readonly Coding DifferentTextInAnEarlierVersion = new Coding
    {
      Code = "earlierTitle",
      Display = "Different text in an earlier version",
      System = "http://terminology.hl7.org/CodeSystem/alternative-title-type"
    };
    /// <summary>
    /// Alternative form of title or abstract is a different language.
    /// </summary>
    public static readonly Coding DifferentLanguage = new Coding
    {
      Code = "language",
      Display = "Different language",
      System = "http://terminology.hl7.org/CodeSystem/alternative-title-type"
    };
    /// <summary>
    /// Subtitle or Secondary title.
    /// </summary>
    public static readonly Coding Subtitle = new Coding
    {
      Code = "subtitle",
      Display = "Subtitle",
      System = "http://terminology.hl7.org/CodeSystem/alternative-title-type"
    };

    /// <summary>
    /// Literal for code: DifferentLanguageDerivedFromAutotranslation
    /// </summary>
    public const string LiteralDifferentLanguageDerivedFromAutotranslation = "autotranslated";

    /// <summary>
    /// Literal for code: DifferentTextInAdditionalMedlineEntry
    /// </summary>
    public const string LiteralDifferentTextInAdditionalMedlineEntry = "duplicatePmid";

    /// <summary>
    /// Literal for code: DifferentTextInAnEarlierVersion
    /// </summary>
    public const string LiteralDifferentTextInAnEarlierVersion = "earlierTitle";

    /// <summary>
    /// Literal for code: DifferentLanguage
    /// </summary>
    public const string LiteralDifferentLanguage = "language";

    /// <summary>
    /// Literal for code: Subtitle
    /// </summary>
    public const string LiteralSubtitle = "subtitle";
  };
}
