// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// Example codes indicating the category a care plan falls within.  Note that these are in no way complete and might not even be appropriate for some uses.
  /// </summary>
  public static class CarePlanCategoryCodes
  {
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MentalHealthCarePlan = new Coding
    {
      Code = "718347000",
      Display = "Mental health care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CarePlan = new Coding
    {
      Code = "734163000",
      Display = "Care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding SurgicalInpatientCarePlan = new Coding
    {
      Code = "735321000",
      Display = "Surgical inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TerminationOfPregnancyInpatientCarePlan = new Coding
    {
      Code = "735322007",
      Display = "Termination of pregnancy inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ThoracicSurgeryInpatientCarePlan = new Coding
    {
      Code = "735323002",
      Display = "Thoracic surgery inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TreatmentEscalationPlan = new Coding
    {
      Code = "735324008",
      Display = "Treatment escalation plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding UnplannedInpatientCarePlan = new Coding
    {
      Code = "735325009",
      Display = "Unplanned inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding UpperGastrointestinalSurgeryInpatientCarePlan = new Coding
    {
      Code = "735326005",
      Display = "Upper gastrointestinal surgery inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding UpperGastrointestinalTractEndoscopyCarePlan = new Coding
    {
      Code = "735327001",
      Display = "Upper gastrointestinal tract endoscopy care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding UrologicalSurgeryInpatientCarePlan = new Coding
    {
      Code = "735328006",
      Display = "Urological surgery inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VascularSurgeryInpatientCarePlan = new Coding
    {
      Code = "735329003",
      Display = "Vascular surgery inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VulnerableAdultCarePlan = new Coding
    {
      Code = "735330008",
      Display = "Vulnerable adult care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HeartFailureSelfManagementPlan = new Coding
    {
      Code = "735984001",
      Display = "Heart failure self management plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DiabetesSelfManagementPlan = new Coding
    {
      Code = "735985000",
      Display = "Diabetes self management plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PatientWrittenBirthPlan = new Coding
    {
      Code = "735986004",
      Display = "Patient written birth plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PressureUlcerCarePlan = new Coding
    {
      Code = "736054002",
      Display = "Pressure ulcer care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding RehabilitationCarePlan = new Coding
    {
      Code = "736055001",
      Display = "Rehabilitation care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding AsthmaClinicalManagementPlan = new Coding
    {
      Code = "736056000",
      Display = "Asthma clinical management plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding RespiratoryDisorderInpatientCarePlan = new Coding
    {
      Code = "736057009",
      Display = "Respiratory disorder inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MentalHealthPersonalHealthPlan = new Coding
    {
      Code = "736058004",
      Display = "Mental health personal health plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding AnginaSelfManagementPlan = new Coding
    {
      Code = "736059007",
      Display = "Angina self management plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PediatricCommunityCarePlan = new Coding
    {
      Code = "736234007",
      Display = "Pediatric community care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PediatricInpatientCarePlan = new Coding
    {
      Code = "736235008",
      Display = "Pediatric inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PediatricOutpatientCarePlan = new Coding
    {
      Code = "736241001",
      Display = "Pediatric outpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PediatricCommunityComplexCarePlan = new Coding
    {
      Code = "736245005",
      Display = "Pediatric community complex care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PediatricSurgeryInpatientCarePlan = new Coding
    {
      Code = "736246006",
      Display = "Pediatric surgery inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PainControlCarePlan = new Coding
    {
      Code = "736248007",
      Display = "Pain control care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding RadiotherapyCarePlan = new Coding
    {
      Code = "736249004",
      Display = "Radiotherapy care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding RespiteCarePlan = new Coding
    {
      Code = "736250004",
      Display = "Respite care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding StrokeCarePlan = new Coding
    {
      Code = "736251000",
      Display = "Stroke care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CancerCarePlan = new Coding
    {
      Code = "736252007",
      Display = "Cancer care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MentalHealthCrisisPlan = new Coding
    {
      Code = "736253002",
      Display = "Mental health crisis plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PsychiatryCarePlan = new Coding
    {
      Code = "736254008",
      Display = "Psychiatry care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding OutpatientCarePlan = new Coding
    {
      Code = "736271009",
      Display = "Outpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding NeonatalCriticalCarePlan = new Coding
    {
      Code = "736282001",
      Display = "Neonatal critical care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ChronicObstructivePulmonaryDiseaseClinicalManagementPlan = new Coding
    {
      Code = "736283006",
      Display = "Chronic obstructive pulmonary disease clinical management plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DiabetesClinicalManagementPlan = new Coding
    {
      Code = "736284000",
      Display = "Diabetes clinical management plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HyperlipidemiaClinicalManagementPlan = new Coding
    {
      Code = "736285004",
      Display = "Hyperlipidemia clinical management plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HypertensionClinicalManagementPlan = new Coding
    {
      Code = "736286003",
      Display = "Hypertension clinical management plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HypothyroidismClinicalManagementPlan = new Coding
    {
      Code = "736287007",
      Display = "Hypothyroidism clinical management plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TransientIschemicAttackClinicalManagementPlan = new Coding
    {
      Code = "736288002",
      Display = "Transient ischemic attack clinical management plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MiscarriageInpatientCarePlan = new Coding
    {
      Code = "736336006",
      Display = "Miscarriage inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding NeurosurgeryInpatientCarePlan = new Coding
    {
      Code = "736337002",
      Display = "Neurosurgery inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding OphthalmicSurgeryInpatientCarePlan = new Coding
    {
      Code = "736338007",
      Display = "Ophthalmic surgery inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding OrthopedicSurgeryInpatientCarePlan = new Coding
    {
      Code = "736339004",
      Display = "Orthopedic surgery inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding OvarianHyperstimulationSyndromeInpatientCarePlan = new Coding
    {
      Code = "736340002",
      Display = "Ovarian hyperstimulation syndrome inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding BreastSurgeryInpatientCarePlan = new Coding
    {
      Code = "736351002",
      Display = "Breast surgery inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CardiacSurgeryInpatientCarePlan = new Coding
    {
      Code = "736352009",
      Display = "Cardiac surgery inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding InpatientCarePlan = new Coding
    {
      Code = "736353004",
      Display = "Inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding GynecologyBladderTrainingInpatientCarePlan = new Coding
    {
      Code = "736355006",
      Display = "Gynecology bladder training inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding GynecologyInpatientCarePlan = new Coding
    {
      Code = "736356007",
      Display = "Gynecology inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MinorGynecologySurgeryInpatientCarePlan = new Coding
    {
      Code = "736357003",
      Display = "Minor gynecology surgery inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MinorOphthalmicSurgeryInpatientCarePlan = new Coding
    {
      Code = "736358008",
      Display = "Minor ophthalmic surgery inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MinorSurgeryInpatientCarePlan = new Coding
    {
      Code = "736359000",
      Display = "Minor surgery inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MinorThoracicSurgeryInpatientCarePlan = new Coding
    {
      Code = "736361009",
      Display = "Minor thoracic surgery inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MinorUrologicSurgeryInpatientCarePlan = new Coding
    {
      Code = "736362002",
      Display = "Minor urologic surgery inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MinorPlasticSurgeryInpatientCarePlan = new Coding
    {
      Code = "736363007",
      Display = "Minor plastic surgery inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MinorOrthopedicSurgeryInpatientCarePlan = new Coding
    {
      Code = "736364001",
      Display = "Minor orthopedic surgery inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding AcuteExacerbationOfChronicObstructivePulmonaryDiseaseCarePlan = new Coding
    {
      Code = "736365000",
      Display = "Acute exacerbation of chronic obstructive pulmonary disease care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding AdvanceCarePlan = new Coding
    {
      Code = "736366004",
      Display = "Advance care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding AnticipatoryCarePlan = new Coding
    {
      Code = "736367008",
      Display = "Anticipatory care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CoronaryHeartDiseaseCarePlan = new Coding
    {
      Code = "736368003",
      Display = "Coronary heart disease care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DayCaseCarePlan = new Coding
    {
      Code = "736369006",
      Display = "Day case care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DayCaseSurgeryCarePlan = new Coding
    {
      Code = "736370007",
      Display = "Day case surgery care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DementiaCarePlan = new Coding
    {
      Code = "736371006",
      Display = "Dementia care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DischargeCarePlan = new Coding
    {
      Code = "736372004",
      Display = "Discharge care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding EndOfLifeCarePlan = new Coding
    {
      Code = "736373009",
      Display = "End of life care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding GynecologyUnplannedInpatientCarePlan = new Coding
    {
      Code = "736374003",
      Display = "Gynecology unplanned inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HemodialysisCarePlan = new Coding
    {
      Code = "736375002",
      Display = "Hemodialysis care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding InfectiousDiseaseCarePlan = new Coding
    {
      Code = "736376001",
      Display = "Infectious disease care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MaternityCarePlan = new Coding
    {
      Code = "736377005",
      Display = "Maternity care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MedicationManagementPlan = new Coding
    {
      Code = "736378000",
      Display = "Medication management plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MiscarriageCarePlan = new Coding
    {
      Code = "736379008",
      Display = "Miscarriage care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MajorSurgeryInpatientCarePlan = new Coding
    {
      Code = "736381005",
      Display = "Major surgery inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MajorHeadAndNeckSurgeryInpatientCarePlan = new Coding
    {
      Code = "736382003",
      Display = "Major head and neck surgery inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MajorNeurosurgeryInpatientCarePlan = new Coding
    {
      Code = "736383008",
      Display = "Major neurosurgery inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MajorOrthopedicSurgeryInpatientCarePlan = new Coding
    {
      Code = "736384002",
      Display = "Major orthopedic surgery inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MajorPlasticSurgeryInpatientCarePlan = new Coding
    {
      Code = "736385001",
      Display = "Major plastic surgery inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MajorVascularSurgeryInpatientCarePlan = new Coding
    {
      Code = "736386000",
      Display = "Major vascular surgery inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MajorUrologicSurgeryInpatientCarePlan = new Coding
    {
      Code = "736387009",
      Display = "Major urologic surgery inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ColorectalSurgeryInpatientCarePlan = new Coding
    {
      Code = "736389007",
      Display = "Colorectal surgery inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding GynecologyMajorSurgeryInpatientCarePlan = new Coding
    {
      Code = "736390003",
      Display = "Gynecology major surgery inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HepatobiliaryAndPancreaticSurgeryInpatientCarePlan = new Coding
    {
      Code = "736391004",
      Display = "Hepatobiliary and pancreatic surgery inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding BronchoscopyCarePlan = new Coding
    {
      Code = "736392006",
      Display = "Bronchoscopy care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ColposcopyCarePlan = new Coding
    {
      Code = "736393001",
      Display = "Colposcopy care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CystoscopyCarePlan = new Coding
    {
      Code = "736394007",
      Display = "Cystoscopy care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HysteroscopyCarePlan = new Coding
    {
      Code = "736395008",
      Display = "Hysteroscopy care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding InterventionalCardiologyInpatientCarePlan = new Coding
    {
      Code = "736396009",
      Display = "Interventional cardiology inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding LowerGastrointestinalTractEndoscopyCarePlan = new Coding
    {
      Code = "736397000",
      Display = "Lower gastrointestinal tract endoscopy care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding BurnInpatientCarePlan = new Coding
    {
      Code = "736399002",
      Display = "Burn inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CardiologyInpatientCarePlan = new Coding
    {
      Code = "736400009",
      Display = "Cardiology inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ChemotherapyCarePlan = new Coding
    {
      Code = "736401008",
      Display = "Chemotherapy care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HipFractureInpatientCarePlan = new Coding
    {
      Code = "736402001",
      Display = "Hip fracture inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HyperemesisInPregnancyInpatientCarePlan = new Coding
    {
      Code = "736403006",
      Display = "Hyperemesis in pregnancy inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding LaryngectomySurgeryInpatientCarePlan = new Coding
    {
      Code = "736453000",
      Display = "Laryngectomy surgery inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MajorBurnInpatientCarePlan = new Coding
    {
      Code = "736482004",
      Display = "Major burn inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DialysisCarePlan = new Coding
    {
      Code = "736690008",
      Display = "Dialysis care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PlasticSurgeryInpatientCarePlan = new Coding
    {
      Code = "736990006",
      Display = "Plastic surgery inpatient care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding AnkleBrachialPressureIndexManagementPlan = new Coding
    {
      Code = "737426005",
      Display = "Ankle brachial pressure index management plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ClinicalManagementPlan = new Coding
    {
      Code = "737427001",
      Display = "Clinical management plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ArthritisClinicalManagementPlan = new Coding
    {
      Code = "737428006",
      Display = "Arthritis clinical management plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ChronicKidneyDiseaseClinicalManagementPlan = new Coding
    {
      Code = "737429003",
      Display = "Chronic kidney disease clinical management plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CongestiveHeartFailureClinicalManagementPlan = new Coding
    {
      Code = "737430008",
      Display = "Congestive heart failure clinical management plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CoronaryHeartDiseaseRiskClinicalManagementPlan = new Coding
    {
      Code = "737431007",
      Display = "Coronary heart disease risk clinical management plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HyperglycemiaClinicalManagementPlan = new Coding
    {
      Code = "737432000",
      Display = "Hyperglycemia clinical management plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HypoglycemiaClinicalManagementPlan = new Coding
    {
      Code = "737433005",
      Display = "Hypoglycemia clinical management plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MajorDepressiveDisorderClinicalManagementPlan = new Coding
    {
      Code = "737434004",
      Display = "Major depressive disorder clinical management plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MalnutritionClinicalManagementPlan = new Coding
    {
      Code = "737435003",
      Display = "Malnutrition clinical management plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HypoglycemiaSelfManagementPlan = new Coding
    {
      Code = "737436002",
      Display = "Hypoglycemia self management plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HyperglycemiaSelfManagementPlan = new Coding
    {
      Code = "737437006",
      Display = "Hyperglycemia self management plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MyocardialInfarctionClinicalManagementPlan = new Coding
    {
      Code = "737438001",
      Display = "Myocardial infarction clinical management plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding SeizureDisorderClinicalManagementPlan = new Coding
    {
      Code = "737439009",
      Display = "Seizure disorder clinical management plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MedicalCriticalCarePlan = new Coding
    {
      Code = "744980002",
      Display = "Medical critical care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MentalHealthCareProgramApproachContingencyPlan = new Coding
    {
      Code = "763249000",
      Display = "Mental health care program approach contingency plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MentalHealthCareProgramApproachCrisisPlan = new Coding
    {
      Code = "763321009",
      Display = "Mental health care program approach crisis plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PreventionOfDeliriumCarePlan = new Coding
    {
      Code = "770576004",
      Display = "Prevention of delirium care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding AcuteMedicineCarePlan = new Coding
    {
      Code = "771082000",
      Display = "Acute medicine care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding NursingCarePlan = new Coding
    {
      Code = "773130005",
      Display = "Nursing care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ObstetricCarePlan = new Coding
    {
      Code = "773430001",
      Display = "Obstetric care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ObstetricIntrapartumCarePlan = new Coding
    {
      Code = "773431002",
      Display = "Obstetric intrapartum care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ObstetricPostnatalCarePlan = new Coding
    {
      Code = "773432009",
      Display = "Obstetric postnatal care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ObstetricAntenatalCarePlan = new Coding
    {
      Code = "773433004",
      Display = "Obstetric antenatal care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding SurgicalCarePlan = new Coding
    {
      Code = "773435006",
      Display = "Surgical care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PlasticSurgeryCarePlan = new Coding
    {
      Code = "773436007",
      Display = "Plastic surgery care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TraumaSurgeryCarePlan = new Coding
    {
      Code = "773437003",
      Display = "Trauma surgery care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding OralSurgeryCarePlan = new Coding
    {
      Code = "773438008",
      Display = "Oral surgery care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HepatobiliarySurgicalCarePlan = new Coding
    {
      Code = "773439000",
      Display = "Hepatobiliary surgical care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DermatologicalSurgeryCarePlan = new Coding
    {
      Code = "773440003",
      Display = "Dermatological surgery care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HandSurgeryCarePlan = new Coding
    {
      Code = "773441004",
      Display = "Hand surgery care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PodiatricSurgeryCarePlan = new Coding
    {
      Code = "773442006",
      Display = "Podiatric surgery care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding OphthalmicSurgeryCarePlan = new Coding
    {
      Code = "773443001",
      Display = "Ophthalmic surgery care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PancreaticSurgeryCarePlan = new Coding
    {
      Code = "773444007",
      Display = "Pancreatic surgery care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding GastrointestinalSurgeryCarePlan = new Coding
    {
      Code = "773445008",
      Display = "Gastrointestinal surgery care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding RehabilitationPsychiatryCarePlan = new Coding
    {
      Code = "773446009",
      Display = "Rehabilitation psychiatry care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ForensicPsychiatryCarePlan = new Coding
    {
      Code = "773447000",
      Display = "Forensic psychiatry care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PsychiatricIntensiveCarePlan = new Coding
    {
      Code = "773448005",
      Display = "Psychiatric intensive care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding OldAgePsychiatryCarePlan = new Coding
    {
      Code = "773449002",
      Display = "Old age psychiatry care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding LiaisonPsychiatryCarePlan = new Coding
    {
      Code = "773450002",
      Display = "Liaison psychiatry care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PsychotherapyCarePlan = new Coding
    {
      Code = "773451003",
      Display = "Psychotherapy care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PsychologyCarePlan = new Coding
    {
      Code = "773452005",
      Display = "Psychology care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding GynecologyCarePlan = new Coding
    {
      Code = "773506001",
      Display = "Gynecology care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding GynecologyOncologyCarePlan = new Coding
    {
      Code = "773507005",
      Display = "Gynecology oncology care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding InterventionalRadiologyCarePlan = new Coding
    {
      Code = "773508000",
      Display = "Interventional radiology care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding OphthalmologyCarePlan = new Coding
    {
      Code = "773509008",
      Display = "Ophthalmology care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding OccupationalTherapyCarePlan = new Coding
    {
      Code = "773511004",
      Display = "Occupational therapy care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding GenitourinaryMedicineCarePlan = new Coding
    {
      Code = "773512006",
      Display = "Genitourinary medicine care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PhysiotherapyCarePlan = new Coding
    {
      Code = "773513001",
      Display = "Physiotherapy care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding SpeechAndLanguageTherapyCarePlan = new Coding
    {
      Code = "773514007",
      Display = "Speech and language therapy care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HeadInjuryRehabilitationCarePlan = new Coding
    {
      Code = "773516009",
      Display = "Head injury rehabilitation care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding OsteopathicManipulativeMedicineCarePlan = new Coding
    {
      Code = "773517000",
      Display = "Osteopathic manipulative medicine care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DieteticCarePlan = new Coding
    {
      Code = "773590002",
      Display = "Dietetic care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PodiatryCarePlan = new Coding
    {
      Code = "773591003",
      Display = "Podiatry care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding OccupationalHealthCarePlan = new Coding
    {
      Code = "773592005",
      Display = "Occupational health care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding UrologyCarePlan = new Coding
    {
      Code = "773593000",
      Display = "Urology care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding OrthodonticCarePlan = new Coding
    {
      Code = "773594006",
      Display = "Orthodontic care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding RespiratoryMedicineCarePlan = new Coding
    {
      Code = "773595007",
      Display = "Respiratory medicine care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CareOfElderlyCarePlan = new Coding
    {
      Code = "773596008",
      Display = "Care of elderly care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding OrthopedicCarePlan = new Coding
    {
      Code = "773597004",
      Display = "Orthopedic care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding GastroenterologyCarePlan = new Coding
    {
      Code = "773598009",
      Display = "Gastroenterology care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HemophiliaCarePlan = new Coding
    {
      Code = "773599001",
      Display = "Hemophilia care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DermatologyCarePlan = new Coding
    {
      Code = "773976008",
      Display = "Dermatology care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HepatologyCarePlan = new Coding
    {
      Code = "773977004",
      Display = "Hepatology care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding EndocrinologyCarePlan = new Coding
    {
      Code = "773978009",
      Display = "Endocrinology care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ProstheticCarePlan = new Coding
    {
      Code = "773979001",
      Display = "Prosthetic care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding OrthoticCarePlan = new Coding
    {
      Code = "773980003",
      Display = "Orthotic care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PalliativeCarePlan = new Coding
    {
      Code = "773981004",
      Display = "Palliative care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding RheumatologyCarePlan = new Coding
    {
      Code = "773982006",
      Display = "Rheumatology care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ENTEarNoseThroatCarePlan = new Coding
    {
      Code = "773983001",
      Display = "ENT (ear, nose, throat) care plan",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding SpecialCareBabyCarePlan = new Coding
    {
      Code = "774202005",
      Display = "Special care baby care plan",
      System = "http://snomed.info/sct"
    };

    /// <summary>
    /// Literal for code: MentalHealthCarePlan
    /// </summary>
    public const string LiteralMentalHealthCarePlan = "718347000";

    /// <summary>
    /// Literal for code: CarePlan
    /// </summary>
    public const string LiteralCarePlan = "734163000";

    /// <summary>
    /// Literal for code: SurgicalInpatientCarePlan
    /// </summary>
    public const string LiteralSurgicalInpatientCarePlan = "735321000";

    /// <summary>
    /// Literal for code: TerminationOfPregnancyInpatientCarePlan
    /// </summary>
    public const string LiteralTerminationOfPregnancyInpatientCarePlan = "735322007";

    /// <summary>
    /// Literal for code: ThoracicSurgeryInpatientCarePlan
    /// </summary>
    public const string LiteralThoracicSurgeryInpatientCarePlan = "735323002";

    /// <summary>
    /// Literal for code: TreatmentEscalationPlan
    /// </summary>
    public const string LiteralTreatmentEscalationPlan = "735324008";

    /// <summary>
    /// Literal for code: UnplannedInpatientCarePlan
    /// </summary>
    public const string LiteralUnplannedInpatientCarePlan = "735325009";

    /// <summary>
    /// Literal for code: UpperGastrointestinalSurgeryInpatientCarePlan
    /// </summary>
    public const string LiteralUpperGastrointestinalSurgeryInpatientCarePlan = "735326005";

    /// <summary>
    /// Literal for code: UpperGastrointestinalTractEndoscopyCarePlan
    /// </summary>
    public const string LiteralUpperGastrointestinalTractEndoscopyCarePlan = "735327001";

    /// <summary>
    /// Literal for code: UrologicalSurgeryInpatientCarePlan
    /// </summary>
    public const string LiteralUrologicalSurgeryInpatientCarePlan = "735328006";

    /// <summary>
    /// Literal for code: VascularSurgeryInpatientCarePlan
    /// </summary>
    public const string LiteralVascularSurgeryInpatientCarePlan = "735329003";

    /// <summary>
    /// Literal for code: VulnerableAdultCarePlan
    /// </summary>
    public const string LiteralVulnerableAdultCarePlan = "735330008";

    /// <summary>
    /// Literal for code: HeartFailureSelfManagementPlan
    /// </summary>
    public const string LiteralHeartFailureSelfManagementPlan = "735984001";

    /// <summary>
    /// Literal for code: DiabetesSelfManagementPlan
    /// </summary>
    public const string LiteralDiabetesSelfManagementPlan = "735985000";

    /// <summary>
    /// Literal for code: PatientWrittenBirthPlan
    /// </summary>
    public const string LiteralPatientWrittenBirthPlan = "735986004";

    /// <summary>
    /// Literal for code: PressureUlcerCarePlan
    /// </summary>
    public const string LiteralPressureUlcerCarePlan = "736054002";

    /// <summary>
    /// Literal for code: RehabilitationCarePlan
    /// </summary>
    public const string LiteralRehabilitationCarePlan = "736055001";

    /// <summary>
    /// Literal for code: AsthmaClinicalManagementPlan
    /// </summary>
    public const string LiteralAsthmaClinicalManagementPlan = "736056000";

    /// <summary>
    /// Literal for code: RespiratoryDisorderInpatientCarePlan
    /// </summary>
    public const string LiteralRespiratoryDisorderInpatientCarePlan = "736057009";

    /// <summary>
    /// Literal for code: MentalHealthPersonalHealthPlan
    /// </summary>
    public const string LiteralMentalHealthPersonalHealthPlan = "736058004";

    /// <summary>
    /// Literal for code: AnginaSelfManagementPlan
    /// </summary>
    public const string LiteralAnginaSelfManagementPlan = "736059007";

    /// <summary>
    /// Literal for code: PediatricCommunityCarePlan
    /// </summary>
    public const string LiteralPediatricCommunityCarePlan = "736234007";

    /// <summary>
    /// Literal for code: PediatricInpatientCarePlan
    /// </summary>
    public const string LiteralPediatricInpatientCarePlan = "736235008";

    /// <summary>
    /// Literal for code: PediatricOutpatientCarePlan
    /// </summary>
    public const string LiteralPediatricOutpatientCarePlan = "736241001";

    /// <summary>
    /// Literal for code: PediatricCommunityComplexCarePlan
    /// </summary>
    public const string LiteralPediatricCommunityComplexCarePlan = "736245005";

    /// <summary>
    /// Literal for code: PediatricSurgeryInpatientCarePlan
    /// </summary>
    public const string LiteralPediatricSurgeryInpatientCarePlan = "736246006";

    /// <summary>
    /// Literal for code: PainControlCarePlan
    /// </summary>
    public const string LiteralPainControlCarePlan = "736248007";

    /// <summary>
    /// Literal for code: RadiotherapyCarePlan
    /// </summary>
    public const string LiteralRadiotherapyCarePlan = "736249004";

    /// <summary>
    /// Literal for code: RespiteCarePlan
    /// </summary>
    public const string LiteralRespiteCarePlan = "736250004";

    /// <summary>
    /// Literal for code: StrokeCarePlan
    /// </summary>
    public const string LiteralStrokeCarePlan = "736251000";

    /// <summary>
    /// Literal for code: CancerCarePlan
    /// </summary>
    public const string LiteralCancerCarePlan = "736252007";

    /// <summary>
    /// Literal for code: MentalHealthCrisisPlan
    /// </summary>
    public const string LiteralMentalHealthCrisisPlan = "736253002";

    /// <summary>
    /// Literal for code: PsychiatryCarePlan
    /// </summary>
    public const string LiteralPsychiatryCarePlan = "736254008";

    /// <summary>
    /// Literal for code: OutpatientCarePlan
    /// </summary>
    public const string LiteralOutpatientCarePlan = "736271009";

    /// <summary>
    /// Literal for code: NeonatalCriticalCarePlan
    /// </summary>
    public const string LiteralNeonatalCriticalCarePlan = "736282001";

    /// <summary>
    /// Literal for code: ChronicObstructivePulmonaryDiseaseClinicalManagementPlan
    /// </summary>
    public const string LiteralChronicObstructivePulmonaryDiseaseClinicalManagementPlan = "736283006";

    /// <summary>
    /// Literal for code: DiabetesClinicalManagementPlan
    /// </summary>
    public const string LiteralDiabetesClinicalManagementPlan = "736284000";

    /// <summary>
    /// Literal for code: HyperlipidemiaClinicalManagementPlan
    /// </summary>
    public const string LiteralHyperlipidemiaClinicalManagementPlan = "736285004";

    /// <summary>
    /// Literal for code: HypertensionClinicalManagementPlan
    /// </summary>
    public const string LiteralHypertensionClinicalManagementPlan = "736286003";

    /// <summary>
    /// Literal for code: HypothyroidismClinicalManagementPlan
    /// </summary>
    public const string LiteralHypothyroidismClinicalManagementPlan = "736287007";

    /// <summary>
    /// Literal for code: TransientIschemicAttackClinicalManagementPlan
    /// </summary>
    public const string LiteralTransientIschemicAttackClinicalManagementPlan = "736288002";

    /// <summary>
    /// Literal for code: MiscarriageInpatientCarePlan
    /// </summary>
    public const string LiteralMiscarriageInpatientCarePlan = "736336006";

    /// <summary>
    /// Literal for code: NeurosurgeryInpatientCarePlan
    /// </summary>
    public const string LiteralNeurosurgeryInpatientCarePlan = "736337002";

    /// <summary>
    /// Literal for code: OphthalmicSurgeryInpatientCarePlan
    /// </summary>
    public const string LiteralOphthalmicSurgeryInpatientCarePlan = "736338007";

    /// <summary>
    /// Literal for code: OrthopedicSurgeryInpatientCarePlan
    /// </summary>
    public const string LiteralOrthopedicSurgeryInpatientCarePlan = "736339004";

    /// <summary>
    /// Literal for code: OvarianHyperstimulationSyndromeInpatientCarePlan
    /// </summary>
    public const string LiteralOvarianHyperstimulationSyndromeInpatientCarePlan = "736340002";

    /// <summary>
    /// Literal for code: BreastSurgeryInpatientCarePlan
    /// </summary>
    public const string LiteralBreastSurgeryInpatientCarePlan = "736351002";

    /// <summary>
    /// Literal for code: CardiacSurgeryInpatientCarePlan
    /// </summary>
    public const string LiteralCardiacSurgeryInpatientCarePlan = "736352009";

    /// <summary>
    /// Literal for code: InpatientCarePlan
    /// </summary>
    public const string LiteralInpatientCarePlan = "736353004";

    /// <summary>
    /// Literal for code: GynecologyBladderTrainingInpatientCarePlan
    /// </summary>
    public const string LiteralGynecologyBladderTrainingInpatientCarePlan = "736355006";

    /// <summary>
    /// Literal for code: GynecologyInpatientCarePlan
    /// </summary>
    public const string LiteralGynecologyInpatientCarePlan = "736356007";

    /// <summary>
    /// Literal for code: MinorGynecologySurgeryInpatientCarePlan
    /// </summary>
    public const string LiteralMinorGynecologySurgeryInpatientCarePlan = "736357003";

    /// <summary>
    /// Literal for code: MinorOphthalmicSurgeryInpatientCarePlan
    /// </summary>
    public const string LiteralMinorOphthalmicSurgeryInpatientCarePlan = "736358008";

    /// <summary>
    /// Literal for code: MinorSurgeryInpatientCarePlan
    /// </summary>
    public const string LiteralMinorSurgeryInpatientCarePlan = "736359000";

    /// <summary>
    /// Literal for code: MinorThoracicSurgeryInpatientCarePlan
    /// </summary>
    public const string LiteralMinorThoracicSurgeryInpatientCarePlan = "736361009";

    /// <summary>
    /// Literal for code: MinorUrologicSurgeryInpatientCarePlan
    /// </summary>
    public const string LiteralMinorUrologicSurgeryInpatientCarePlan = "736362002";

    /// <summary>
    /// Literal for code: MinorPlasticSurgeryInpatientCarePlan
    /// </summary>
    public const string LiteralMinorPlasticSurgeryInpatientCarePlan = "736363007";

    /// <summary>
    /// Literal for code: MinorOrthopedicSurgeryInpatientCarePlan
    /// </summary>
    public const string LiteralMinorOrthopedicSurgeryInpatientCarePlan = "736364001";

    /// <summary>
    /// Literal for code: AcuteExacerbationOfChronicObstructivePulmonaryDiseaseCarePlan
    /// </summary>
    public const string LiteralAcuteExacerbationOfChronicObstructivePulmonaryDiseaseCarePlan = "736365000";

    /// <summary>
    /// Literal for code: AdvanceCarePlan
    /// </summary>
    public const string LiteralAdvanceCarePlan = "736366004";

    /// <summary>
    /// Literal for code: AnticipatoryCarePlan
    /// </summary>
    public const string LiteralAnticipatoryCarePlan = "736367008";

    /// <summary>
    /// Literal for code: CoronaryHeartDiseaseCarePlan
    /// </summary>
    public const string LiteralCoronaryHeartDiseaseCarePlan = "736368003";

    /// <summary>
    /// Literal for code: DayCaseCarePlan
    /// </summary>
    public const string LiteralDayCaseCarePlan = "736369006";

    /// <summary>
    /// Literal for code: DayCaseSurgeryCarePlan
    /// </summary>
    public const string LiteralDayCaseSurgeryCarePlan = "736370007";

    /// <summary>
    /// Literal for code: DementiaCarePlan
    /// </summary>
    public const string LiteralDementiaCarePlan = "736371006";

    /// <summary>
    /// Literal for code: DischargeCarePlan
    /// </summary>
    public const string LiteralDischargeCarePlan = "736372004";

    /// <summary>
    /// Literal for code: EndOfLifeCarePlan
    /// </summary>
    public const string LiteralEndOfLifeCarePlan = "736373009";

    /// <summary>
    /// Literal for code: GynecologyUnplannedInpatientCarePlan
    /// </summary>
    public const string LiteralGynecologyUnplannedInpatientCarePlan = "736374003";

    /// <summary>
    /// Literal for code: HemodialysisCarePlan
    /// </summary>
    public const string LiteralHemodialysisCarePlan = "736375002";

    /// <summary>
    /// Literal for code: InfectiousDiseaseCarePlan
    /// </summary>
    public const string LiteralInfectiousDiseaseCarePlan = "736376001";

    /// <summary>
    /// Literal for code: MaternityCarePlan
    /// </summary>
    public const string LiteralMaternityCarePlan = "736377005";

    /// <summary>
    /// Literal for code: MedicationManagementPlan
    /// </summary>
    public const string LiteralMedicationManagementPlan = "736378000";

    /// <summary>
    /// Literal for code: MiscarriageCarePlan
    /// </summary>
    public const string LiteralMiscarriageCarePlan = "736379008";

    /// <summary>
    /// Literal for code: MajorSurgeryInpatientCarePlan
    /// </summary>
    public const string LiteralMajorSurgeryInpatientCarePlan = "736381005";

    /// <summary>
    /// Literal for code: MajorHeadAndNeckSurgeryInpatientCarePlan
    /// </summary>
    public const string LiteralMajorHeadAndNeckSurgeryInpatientCarePlan = "736382003";

    /// <summary>
    /// Literal for code: MajorNeurosurgeryInpatientCarePlan
    /// </summary>
    public const string LiteralMajorNeurosurgeryInpatientCarePlan = "736383008";

    /// <summary>
    /// Literal for code: MajorOrthopedicSurgeryInpatientCarePlan
    /// </summary>
    public const string LiteralMajorOrthopedicSurgeryInpatientCarePlan = "736384002";

    /// <summary>
    /// Literal for code: MajorPlasticSurgeryInpatientCarePlan
    /// </summary>
    public const string LiteralMajorPlasticSurgeryInpatientCarePlan = "736385001";

    /// <summary>
    /// Literal for code: MajorVascularSurgeryInpatientCarePlan
    /// </summary>
    public const string LiteralMajorVascularSurgeryInpatientCarePlan = "736386000";

    /// <summary>
    /// Literal for code: MajorUrologicSurgeryInpatientCarePlan
    /// </summary>
    public const string LiteralMajorUrologicSurgeryInpatientCarePlan = "736387009";

    /// <summary>
    /// Literal for code: ColorectalSurgeryInpatientCarePlan
    /// </summary>
    public const string LiteralColorectalSurgeryInpatientCarePlan = "736389007";

    /// <summary>
    /// Literal for code: GynecologyMajorSurgeryInpatientCarePlan
    /// </summary>
    public const string LiteralGynecologyMajorSurgeryInpatientCarePlan = "736390003";

    /// <summary>
    /// Literal for code: HepatobiliaryAndPancreaticSurgeryInpatientCarePlan
    /// </summary>
    public const string LiteralHepatobiliaryAndPancreaticSurgeryInpatientCarePlan = "736391004";

    /// <summary>
    /// Literal for code: BronchoscopyCarePlan
    /// </summary>
    public const string LiteralBronchoscopyCarePlan = "736392006";

    /// <summary>
    /// Literal for code: ColposcopyCarePlan
    /// </summary>
    public const string LiteralColposcopyCarePlan = "736393001";

    /// <summary>
    /// Literal for code: CystoscopyCarePlan
    /// </summary>
    public const string LiteralCystoscopyCarePlan = "736394007";

    /// <summary>
    /// Literal for code: HysteroscopyCarePlan
    /// </summary>
    public const string LiteralHysteroscopyCarePlan = "736395008";

    /// <summary>
    /// Literal for code: InterventionalCardiologyInpatientCarePlan
    /// </summary>
    public const string LiteralInterventionalCardiologyInpatientCarePlan = "736396009";

    /// <summary>
    /// Literal for code: LowerGastrointestinalTractEndoscopyCarePlan
    /// </summary>
    public const string LiteralLowerGastrointestinalTractEndoscopyCarePlan = "736397000";

    /// <summary>
    /// Literal for code: BurnInpatientCarePlan
    /// </summary>
    public const string LiteralBurnInpatientCarePlan = "736399002";

    /// <summary>
    /// Literal for code: CardiologyInpatientCarePlan
    /// </summary>
    public const string LiteralCardiologyInpatientCarePlan = "736400009";

    /// <summary>
    /// Literal for code: ChemotherapyCarePlan
    /// </summary>
    public const string LiteralChemotherapyCarePlan = "736401008";

    /// <summary>
    /// Literal for code: HipFractureInpatientCarePlan
    /// </summary>
    public const string LiteralHipFractureInpatientCarePlan = "736402001";

    /// <summary>
    /// Literal for code: HyperemesisInPregnancyInpatientCarePlan
    /// </summary>
    public const string LiteralHyperemesisInPregnancyInpatientCarePlan = "736403006";

    /// <summary>
    /// Literal for code: LaryngectomySurgeryInpatientCarePlan
    /// </summary>
    public const string LiteralLaryngectomySurgeryInpatientCarePlan = "736453000";

    /// <summary>
    /// Literal for code: MajorBurnInpatientCarePlan
    /// </summary>
    public const string LiteralMajorBurnInpatientCarePlan = "736482004";

    /// <summary>
    /// Literal for code: DialysisCarePlan
    /// </summary>
    public const string LiteralDialysisCarePlan = "736690008";

    /// <summary>
    /// Literal for code: PlasticSurgeryInpatientCarePlan
    /// </summary>
    public const string LiteralPlasticSurgeryInpatientCarePlan = "736990006";

    /// <summary>
    /// Literal for code: AnkleBrachialPressureIndexManagementPlan
    /// </summary>
    public const string LiteralAnkleBrachialPressureIndexManagementPlan = "737426005";

    /// <summary>
    /// Literal for code: ClinicalManagementPlan
    /// </summary>
    public const string LiteralClinicalManagementPlan = "737427001";

    /// <summary>
    /// Literal for code: ArthritisClinicalManagementPlan
    /// </summary>
    public const string LiteralArthritisClinicalManagementPlan = "737428006";

    /// <summary>
    /// Literal for code: ChronicKidneyDiseaseClinicalManagementPlan
    /// </summary>
    public const string LiteralChronicKidneyDiseaseClinicalManagementPlan = "737429003";

    /// <summary>
    /// Literal for code: CongestiveHeartFailureClinicalManagementPlan
    /// </summary>
    public const string LiteralCongestiveHeartFailureClinicalManagementPlan = "737430008";

    /// <summary>
    /// Literal for code: CoronaryHeartDiseaseRiskClinicalManagementPlan
    /// </summary>
    public const string LiteralCoronaryHeartDiseaseRiskClinicalManagementPlan = "737431007";

    /// <summary>
    /// Literal for code: HyperglycemiaClinicalManagementPlan
    /// </summary>
    public const string LiteralHyperglycemiaClinicalManagementPlan = "737432000";

    /// <summary>
    /// Literal for code: HypoglycemiaClinicalManagementPlan
    /// </summary>
    public const string LiteralHypoglycemiaClinicalManagementPlan = "737433005";

    /// <summary>
    /// Literal for code: MajorDepressiveDisorderClinicalManagementPlan
    /// </summary>
    public const string LiteralMajorDepressiveDisorderClinicalManagementPlan = "737434004";

    /// <summary>
    /// Literal for code: MalnutritionClinicalManagementPlan
    /// </summary>
    public const string LiteralMalnutritionClinicalManagementPlan = "737435003";

    /// <summary>
    /// Literal for code: HypoglycemiaSelfManagementPlan
    /// </summary>
    public const string LiteralHypoglycemiaSelfManagementPlan = "737436002";

    /// <summary>
    /// Literal for code: HyperglycemiaSelfManagementPlan
    /// </summary>
    public const string LiteralHyperglycemiaSelfManagementPlan = "737437006";

    /// <summary>
    /// Literal for code: MyocardialInfarctionClinicalManagementPlan
    /// </summary>
    public const string LiteralMyocardialInfarctionClinicalManagementPlan = "737438001";

    /// <summary>
    /// Literal for code: SeizureDisorderClinicalManagementPlan
    /// </summary>
    public const string LiteralSeizureDisorderClinicalManagementPlan = "737439009";

    /// <summary>
    /// Literal for code: MedicalCriticalCarePlan
    /// </summary>
    public const string LiteralMedicalCriticalCarePlan = "744980002";

    /// <summary>
    /// Literal for code: MentalHealthCareProgramApproachContingencyPlan
    /// </summary>
    public const string LiteralMentalHealthCareProgramApproachContingencyPlan = "763249000";

    /// <summary>
    /// Literal for code: MentalHealthCareProgramApproachCrisisPlan
    /// </summary>
    public const string LiteralMentalHealthCareProgramApproachCrisisPlan = "763321009";

    /// <summary>
    /// Literal for code: PreventionOfDeliriumCarePlan
    /// </summary>
    public const string LiteralPreventionOfDeliriumCarePlan = "770576004";

    /// <summary>
    /// Literal for code: AcuteMedicineCarePlan
    /// </summary>
    public const string LiteralAcuteMedicineCarePlan = "771082000";

    /// <summary>
    /// Literal for code: NursingCarePlan
    /// </summary>
    public const string LiteralNursingCarePlan = "773130005";

    /// <summary>
    /// Literal for code: ObstetricCarePlan
    /// </summary>
    public const string LiteralObstetricCarePlan = "773430001";

    /// <summary>
    /// Literal for code: ObstetricIntrapartumCarePlan
    /// </summary>
    public const string LiteralObstetricIntrapartumCarePlan = "773431002";

    /// <summary>
    /// Literal for code: ObstetricPostnatalCarePlan
    /// </summary>
    public const string LiteralObstetricPostnatalCarePlan = "773432009";

    /// <summary>
    /// Literal for code: ObstetricAntenatalCarePlan
    /// </summary>
    public const string LiteralObstetricAntenatalCarePlan = "773433004";

    /// <summary>
    /// Literal for code: SurgicalCarePlan
    /// </summary>
    public const string LiteralSurgicalCarePlan = "773435006";

    /// <summary>
    /// Literal for code: PlasticSurgeryCarePlan
    /// </summary>
    public const string LiteralPlasticSurgeryCarePlan = "773436007";

    /// <summary>
    /// Literal for code: TraumaSurgeryCarePlan
    /// </summary>
    public const string LiteralTraumaSurgeryCarePlan = "773437003";

    /// <summary>
    /// Literal for code: OralSurgeryCarePlan
    /// </summary>
    public const string LiteralOralSurgeryCarePlan = "773438008";

    /// <summary>
    /// Literal for code: HepatobiliarySurgicalCarePlan
    /// </summary>
    public const string LiteralHepatobiliarySurgicalCarePlan = "773439000";

    /// <summary>
    /// Literal for code: DermatologicalSurgeryCarePlan
    /// </summary>
    public const string LiteralDermatologicalSurgeryCarePlan = "773440003";

    /// <summary>
    /// Literal for code: HandSurgeryCarePlan
    /// </summary>
    public const string LiteralHandSurgeryCarePlan = "773441004";

    /// <summary>
    /// Literal for code: PodiatricSurgeryCarePlan
    /// </summary>
    public const string LiteralPodiatricSurgeryCarePlan = "773442006";

    /// <summary>
    /// Literal for code: OphthalmicSurgeryCarePlan
    /// </summary>
    public const string LiteralOphthalmicSurgeryCarePlan = "773443001";

    /// <summary>
    /// Literal for code: PancreaticSurgeryCarePlan
    /// </summary>
    public const string LiteralPancreaticSurgeryCarePlan = "773444007";

    /// <summary>
    /// Literal for code: GastrointestinalSurgeryCarePlan
    /// </summary>
    public const string LiteralGastrointestinalSurgeryCarePlan = "773445008";

    /// <summary>
    /// Literal for code: RehabilitationPsychiatryCarePlan
    /// </summary>
    public const string LiteralRehabilitationPsychiatryCarePlan = "773446009";

    /// <summary>
    /// Literal for code: ForensicPsychiatryCarePlan
    /// </summary>
    public const string LiteralForensicPsychiatryCarePlan = "773447000";

    /// <summary>
    /// Literal for code: PsychiatricIntensiveCarePlan
    /// </summary>
    public const string LiteralPsychiatricIntensiveCarePlan = "773448005";

    /// <summary>
    /// Literal for code: OldAgePsychiatryCarePlan
    /// </summary>
    public const string LiteralOldAgePsychiatryCarePlan = "773449002";

    /// <summary>
    /// Literal for code: LiaisonPsychiatryCarePlan
    /// </summary>
    public const string LiteralLiaisonPsychiatryCarePlan = "773450002";

    /// <summary>
    /// Literal for code: PsychotherapyCarePlan
    /// </summary>
    public const string LiteralPsychotherapyCarePlan = "773451003";

    /// <summary>
    /// Literal for code: PsychologyCarePlan
    /// </summary>
    public const string LiteralPsychologyCarePlan = "773452005";

    /// <summary>
    /// Literal for code: GynecologyCarePlan
    /// </summary>
    public const string LiteralGynecologyCarePlan = "773506001";

    /// <summary>
    /// Literal for code: GynecologyOncologyCarePlan
    /// </summary>
    public const string LiteralGynecologyOncologyCarePlan = "773507005";

    /// <summary>
    /// Literal for code: InterventionalRadiologyCarePlan
    /// </summary>
    public const string LiteralInterventionalRadiologyCarePlan = "773508000";

    /// <summary>
    /// Literal for code: OphthalmologyCarePlan
    /// </summary>
    public const string LiteralOphthalmologyCarePlan = "773509008";

    /// <summary>
    /// Literal for code: OccupationalTherapyCarePlan
    /// </summary>
    public const string LiteralOccupationalTherapyCarePlan = "773511004";

    /// <summary>
    /// Literal for code: GenitourinaryMedicineCarePlan
    /// </summary>
    public const string LiteralGenitourinaryMedicineCarePlan = "773512006";

    /// <summary>
    /// Literal for code: PhysiotherapyCarePlan
    /// </summary>
    public const string LiteralPhysiotherapyCarePlan = "773513001";

    /// <summary>
    /// Literal for code: SpeechAndLanguageTherapyCarePlan
    /// </summary>
    public const string LiteralSpeechAndLanguageTherapyCarePlan = "773514007";

    /// <summary>
    /// Literal for code: HeadInjuryRehabilitationCarePlan
    /// </summary>
    public const string LiteralHeadInjuryRehabilitationCarePlan = "773516009";

    /// <summary>
    /// Literal for code: OsteopathicManipulativeMedicineCarePlan
    /// </summary>
    public const string LiteralOsteopathicManipulativeMedicineCarePlan = "773517000";

    /// <summary>
    /// Literal for code: DieteticCarePlan
    /// </summary>
    public const string LiteralDieteticCarePlan = "773590002";

    /// <summary>
    /// Literal for code: PodiatryCarePlan
    /// </summary>
    public const string LiteralPodiatryCarePlan = "773591003";

    /// <summary>
    /// Literal for code: OccupationalHealthCarePlan
    /// </summary>
    public const string LiteralOccupationalHealthCarePlan = "773592005";

    /// <summary>
    /// Literal for code: UrologyCarePlan
    /// </summary>
    public const string LiteralUrologyCarePlan = "773593000";

    /// <summary>
    /// Literal for code: OrthodonticCarePlan
    /// </summary>
    public const string LiteralOrthodonticCarePlan = "773594006";

    /// <summary>
    /// Literal for code: RespiratoryMedicineCarePlan
    /// </summary>
    public const string LiteralRespiratoryMedicineCarePlan = "773595007";

    /// <summary>
    /// Literal for code: CareOfElderlyCarePlan
    /// </summary>
    public const string LiteralCareOfElderlyCarePlan = "773596008";

    /// <summary>
    /// Literal for code: OrthopedicCarePlan
    /// </summary>
    public const string LiteralOrthopedicCarePlan = "773597004";

    /// <summary>
    /// Literal for code: GastroenterologyCarePlan
    /// </summary>
    public const string LiteralGastroenterologyCarePlan = "773598009";

    /// <summary>
    /// Literal for code: HemophiliaCarePlan
    /// </summary>
    public const string LiteralHemophiliaCarePlan = "773599001";

    /// <summary>
    /// Literal for code: DermatologyCarePlan
    /// </summary>
    public const string LiteralDermatologyCarePlan = "773976008";

    /// <summary>
    /// Literal for code: HepatologyCarePlan
    /// </summary>
    public const string LiteralHepatologyCarePlan = "773977004";

    /// <summary>
    /// Literal for code: EndocrinologyCarePlan
    /// </summary>
    public const string LiteralEndocrinologyCarePlan = "773978009";

    /// <summary>
    /// Literal for code: ProstheticCarePlan
    /// </summary>
    public const string LiteralProstheticCarePlan = "773979001";

    /// <summary>
    /// Literal for code: OrthoticCarePlan
    /// </summary>
    public const string LiteralOrthoticCarePlan = "773980003";

    /// <summary>
    /// Literal for code: PalliativeCarePlan
    /// </summary>
    public const string LiteralPalliativeCarePlan = "773981004";

    /// <summary>
    /// Literal for code: RheumatologyCarePlan
    /// </summary>
    public const string LiteralRheumatologyCarePlan = "773982006";

    /// <summary>
    /// Literal for code: ENTEarNoseThroatCarePlan
    /// </summary>
    public const string LiteralENTEarNoseThroatCarePlan = "773983001";

    /// <summary>
    /// Literal for code: SpecialCareBabyCarePlan
    /// </summary>
    public const string LiteralSpecialCareBabyCarePlan = "774202005";
  };
}
