// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// The format for display of the citation.
  /// </summary>
  public static class CitationSummaryStyleCodes
  {
    /// <summary>
    /// Chemistry.
    /// </summary>
    public static readonly Coding AmericanChemicalSociety = new Coding
    {
      Code = "ACS",
      Display = "American Chemical Society",
      System = "http://terminology.hl7.org/CodeSystem/citation-summary-style"
    };
    /// <summary>
    /// Medicine.
    /// </summary>
    public static readonly Coding AmericanMedicalAssociation11thEdition = new Coding
    {
      Code = "AMA11",
      Display = "American Medical Association 11th edition",
      System = "http://terminology.hl7.org/CodeSystem/citation-summary-style"
    };
    /// <summary>
    /// APA 6th edition used by Education, Psychology and Sciences.
    /// </summary>
    public static readonly Coding AmericanPsychologicalAssociation6thEdition = new Coding
    {
      Code = "APA6",
      Display = "American Psychological Association 6th edition",
      System = "http://terminology.hl7.org/CodeSystem/citation-summary-style"
    };
    /// <summary>
    /// APA 7th edition (October 2019) used by Education, Psychology and Sciences.
    /// </summary>
    public static readonly Coding AmericanPsychologicalAssociation7thEdition = new Coding
    {
      Code = "APA7",
      Display = "American Psychological Association 7th edition",
      System = "http://terminology.hl7.org/CodeSystem/citation-summary-style"
    };
    /// <summary>
    /// Sociology.
    /// </summary>
    public static readonly Coding AmericanSociologicalAssociation6thEdition = new Coding
    {
      Code = "ASA6",
      Display = "American Sociological Association 6th edition",
      System = "http://terminology.hl7.org/CodeSystem/citation-summary-style"
    };
    /// <summary>
    /// Used by Business, History and the Fine Arts.
    /// </summary>
    public static readonly Coding ChicagoStyleVersion17AuthorDate = new Coding
    {
      Code = "ChicagoA17",
      Display = "Chicago Style Version 17\nAuthor Date",
      System = "http://terminology.hl7.org/CodeSystem/citation-summary-style"
    };
    /// <summary>
    /// Used by Business, History and the Fine Arts.
    /// </summary>
    public static readonly Coding ChicagoStyleVersion17FullNote = new Coding
    {
      Code = "ChicagoB17",
      Display = "Chicago Style\nVersion 17\nFull note",
      System = "http://terminology.hl7.org/CodeSystem/citation-summary-style"
    };
    /// <summary>
    /// Used by Cochrane reviews, example: Huang, M, Tang T, Pang, P, Li, M, Ma R, Lu, J, et al. Treating COVID-19 with Chloroquine. J Mol Cell Biol 2020; 12(4):322–5.
    /// </summary>
    public static readonly Coding CochraneStyle = new Coding
    {
      Code = "Cochrane",
      Display = "Cochrane Style",
      System = "http://terminology.hl7.org/CodeSystem/citation-summary-style"
    };
    /// <summary>
    /// Citation style to report human-readable and machine-readable access paths.
    /// </summary>
    public static readonly Coding ComputablePublishing = new Coding
    {
      Code = "CompPub",
      Display = "Computable Publishing",
      System = "http://terminology.hl7.org/CodeSystem/citation-summary-style"
    };
    /// <summary>
    /// Biology ecology.
    /// </summary>
    public static readonly Coding ElsevierHarvardStyle = new Coding
    {
      Code = "Elsevier-Harvard",
      Display = "Elsevier-Harvard Style",
      System = "http://terminology.hl7.org/CodeSystem/citation-summary-style"
    };
    /// <summary>
    /// IT, Engineering.
    /// </summary>
    public static readonly Coding InstituteOfElectricalAndElectronicsEngineers = new Coding
    {
      Code = "IEEE",
      Display = "Institute of Electrical and Electronics Engineers",
      System = "http://terminology.hl7.org/CodeSystem/citation-summary-style"
    };
    /// <summary>
    /// MLA 8th edition used by the Humanities.
    /// </summary>
    public static readonly Coding ModernLanguageAssociation8thEdition = new Coding
    {
      Code = "MLA8",
      Display = "Modern Language Association 8th edition",
      System = "http://terminology.hl7.org/CodeSystem/citation-summary-style"
    };
    /// <summary>
    /// Biology.
    /// </summary>
    public static readonly Coding NatureReferencingStyle = new Coding
    {
      Code = "Nature",
      Display = "Nature Referencing style",
      System = "http://terminology.hl7.org/CodeSystem/citation-summary-style"
    };
    /// <summary>
    /// Citation style used by International Committee of Medical Journal Editors and maintained by US National Library of Medicine.
    /// </summary>
    public static readonly Coding VancouverStyle = new Coding
    {
      Code = "Vancouver",
      Display = "Vancouver style",
      System = "http://terminology.hl7.org/CodeSystem/citation-summary-style"
    };

    /// <summary>
    /// Literal for code: AmericanChemicalSociety
    /// </summary>
    public const string LiteralAmericanChemicalSociety = "ACS";

    /// <summary>
    /// Literal for code: AmericanMedicalAssociation11thEdition
    /// </summary>
    public const string LiteralAmericanMedicalAssociation11thEdition = "AMA11";

    /// <summary>
    /// Literal for code: AmericanPsychologicalAssociation6thEdition
    /// </summary>
    public const string LiteralAmericanPsychologicalAssociation6thEdition = "APA6";

    /// <summary>
    /// Literal for code: AmericanPsychologicalAssociation7thEdition
    /// </summary>
    public const string LiteralAmericanPsychologicalAssociation7thEdition = "APA7";

    /// <summary>
    /// Literal for code: AmericanSociologicalAssociation6thEdition
    /// </summary>
    public const string LiteralAmericanSociologicalAssociation6thEdition = "ASA6";

    /// <summary>
    /// Literal for code: ChicagoStyleVersion17AuthorDate
    /// </summary>
    public const string LiteralChicagoStyleVersion17AuthorDate = "ChicagoA17";

    /// <summary>
    /// Literal for code: ChicagoStyleVersion17FullNote
    /// </summary>
    public const string LiteralChicagoStyleVersion17FullNote = "ChicagoB17";

    /// <summary>
    /// Literal for code: CochraneStyle
    /// </summary>
    public const string LiteralCochraneStyle = "Cochrane";

    /// <summary>
    /// Literal for code: ComputablePublishing
    /// </summary>
    public const string LiteralComputablePublishing = "CompPub";

    /// <summary>
    /// Literal for code: ElsevierHarvardStyle
    /// </summary>
    public const string LiteralElsevierHarvardStyle = "Elsevier-Harvard";

    /// <summary>
    /// Literal for code: InstituteOfElectricalAndElectronicsEngineers
    /// </summary>
    public const string LiteralInstituteOfElectricalAndElectronicsEngineers = "IEEE";

    /// <summary>
    /// Literal for code: ModernLanguageAssociation8thEdition
    /// </summary>
    public const string LiteralModernLanguageAssociation8thEdition = "MLA8";

    /// <summary>
    /// Literal for code: NatureReferencingStyle
    /// </summary>
    public const string LiteralNatureReferencingStyle = "Nature";

    /// <summary>
    /// Literal for code: VancouverStyle
    /// </summary>
    public const string LiteralVancouverStyle = "Vancouver";
  };
}
