// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// Used for many classifiers including PublicationType, CitationSubset, MeshHeading, Chemical.
  /// </summary>
  public static class CitationClassifierCodes
  {
    /// <summary>
    /// Used with articles which include video files or clips, or for articles which are entirely video.
    /// </summary>
    public static readonly Coding VideoAudioMedia = new Coding
    {
      Code = "68059040",
      Display = "Video-Audio Media",
      System = "http://terminology.hl7.org/CodeSystem/citation-classifier"
    };
    /// <summary>
    /// The article cited is an audio file.
    /// </summary>
    public static readonly Coding AudioFile = new Coding
    {
      Code = "audio",
      Display = "Audio file",
      System = "http://terminology.hl7.org/CodeSystem/citation-classifier"
    };
    /// <summary>
    /// Scientific manuscript made available prior to PEER REVIEW.
    /// </summary>
    public static readonly Coding Preprint = new Coding
    {
      Code = "D000076942",
      Display = "Preprint",
      System = "http://terminology.hl7.org/CodeSystem/citation-classifier"
    };
    /// <summary>
    /// Non-periodical written or printed works consisting of sheets of pages fastened or bound together within covers.
    /// </summary>
    public static readonly Coding Book = new Coding
    {
      Code = "D001877",
      Display = "Book",
      System = "http://terminology.hl7.org/CodeSystem/citation-classifier"
    };
    /// <summary>
    /// A structured file of information or a set of logically related data stored and retrieved using computer-based means.
    /// </summary>
    public static readonly Coding Database = new Coding
    {
      Code = "D019991",
      Display = "Database",
      System = "http://terminology.hl7.org/CodeSystem/citation-classifier"
    };
    /// <summary>
    /// Works consisting of organized collections of data, which have been stored permanently in a formalized manner suitable for communication, interpretation, or processing.
    /// </summary>
    public static readonly Coding Dataset = new Coding
    {
      Code = "D064886",
      Display = "Dataset",
      System = "http://terminology.hl7.org/CodeSystem/citation-classifier"
    };
    /// <summary>
    /// The article cited is a FHIR resource.
    /// </summary>
    public static readonly Coding FHIRResource = new Coding
    {
      Code = "FHIR-resource",
      Display = "FHIR Resource",
      System = "http://terminology.hl7.org/CodeSystem/citation-classifier"
    };
    /// <summary>
    /// The article cited is an audio file.
    /// </summary>
    public static readonly Coding ImageFile = new Coding
    {
      Code = "image",
      Display = "Image file",
      System = "http://terminology.hl7.org/CodeSystem/citation-classifier"
    };
    /// <summary>
    /// The article cited is machine code.
    /// </summary>
    public static readonly Coding MachineCode = new Coding
    {
      Code = "machine-code",
      Display = "Machine code",
      System = "http://terminology.hl7.org/CodeSystem/citation-classifier"
    };
    /// <summary>
    /// The article cited is the protocol of an activity and not the results or findings.
    /// </summary>
    public static readonly Coding Protocol = new Coding
    {
      Code = "protocol",
      Display = "Protocol",
      System = "http://terminology.hl7.org/CodeSystem/citation-classifier"
    };

    /// <summary>
    /// Literal for code: VideoAudioMedia
    /// </summary>
    public const string LiteralVideoAudioMedia = "68059040";

    /// <summary>
    /// Literal for code: AudioFile
    /// </summary>
    public const string LiteralAudioFile = "audio";

    /// <summary>
    /// Literal for code: Preprint
    /// </summary>
    public const string LiteralPreprint = "D000076942";

    /// <summary>
    /// Literal for code: Book
    /// </summary>
    public const string LiteralBook = "D001877";

    /// <summary>
    /// Literal for code: Database
    /// </summary>
    public const string LiteralDatabase = "D019991";

    /// <summary>
    /// Literal for code: Dataset
    /// </summary>
    public const string LiteralDataset = "D064886";

    /// <summary>
    /// Literal for code: FHIRResource
    /// </summary>
    public const string LiteralFHIRResource = "FHIR-resource";

    /// <summary>
    /// Literal for code: ImageFile
    /// </summary>
    public const string LiteralImageFile = "image";

    /// <summary>
    /// Literal for code: MachineCode
    /// </summary>
    public const string LiteralMachineCode = "machine-code";

    /// <summary>
    /// Literal for code: Protocol
    /// </summary>
    public const string LiteralProtocol = "protocol";
  };
}
