// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// Citation contribution.
  /// </summary>
  public static class CitationContributionCodes
  {
    /// <summary>
    /// Conceptualization (see https://jats4r.org/credit-taxonomy).
    /// </summary>
    public static readonly Coding Conceptualization = new Coding
    {
      Code = "conceptualization",
      Display = "Conceptualization",
      System = "http://terminology.hl7.org/CodeSystem/citation-contribution"
    };
    /// <summary>
    /// Data curation (see https://jats4r.org/credit-taxonomy).
    /// </summary>
    public static readonly Coding DataCuration = new Coding
    {
      Code = "dataCuration",
      Display = "Data curation",
      System = "http://terminology.hl7.org/CodeSystem/citation-contribution"
    };
    /// <summary>
    /// Formal analysis (see https://jats4r.org/credit-taxonomy).
    /// </summary>
    public static readonly Coding FormalAnalysis = new Coding
    {
      Code = "formalAnalysis",
      Display = "Formal analysis",
      System = "http://terminology.hl7.org/CodeSystem/citation-contribution"
    };
    /// <summary>
    /// Funding acquisition (see https://jats4r.org/credit-taxonomy).
    /// </summary>
    public static readonly Coding FundingAcquisition = new Coding
    {
      Code = "fundingAcquisition",
      Display = "Funding acquisition",
      System = "http://terminology.hl7.org/CodeSystem/citation-contribution"
    };
    /// <summary>
    /// Investigation (see https://jats4r.org/credit-taxonomy).
    /// </summary>
    public static readonly Coding Investigation = new Coding
    {
      Code = "investigation",
      Display = "Investigation",
      System = "http://terminology.hl7.org/CodeSystem/citation-contribution"
    };
    /// <summary>
    /// Methodology (see https://jats4r.org/credit-taxonomy).
    /// </summary>
    public static readonly Coding Methodology = new Coding
    {
      Code = "methodology",
      Display = "Methodology",
      System = "http://terminology.hl7.org/CodeSystem/citation-contribution"
    };
    /// <summary>
    /// Project administration (see https://jats4r.org/credit-taxonomy).
    /// </summary>
    public static readonly Coding ProjectAdministration = new Coding
    {
      Code = "projectAdministration",
      Display = "Project administration",
      System = "http://terminology.hl7.org/CodeSystem/citation-contribution"
    };
    /// <summary>
    /// Resources (see https://jats4r.org/credit-taxonomy).
    /// </summary>
    public static readonly Coding Resources = new Coding
    {
      Code = "resources",
      Display = "Resources",
      System = "http://terminology.hl7.org/CodeSystem/citation-contribution"
    };
    /// <summary>
    /// Software (see https://jats4r.org/credit-taxonomy).
    /// </summary>
    public static readonly Coding Software = new Coding
    {
      Code = "software",
      Display = "Software",
      System = "http://terminology.hl7.org/CodeSystem/citation-contribution"
    };
    /// <summary>
    /// Supervision (see https://jats4r.org/credit-taxonomy).
    /// </summary>
    public static readonly Coding Supervision = new Coding
    {
      Code = "supervision",
      Display = "Supervision",
      System = "http://terminology.hl7.org/CodeSystem/citation-contribution"
    };
    /// <summary>
    /// Validation (see https://jats4r.org/credit-taxonomy).
    /// </summary>
    public static readonly Coding Validation = new Coding
    {
      Code = "validation",
      Display = "Validation",
      System = "http://terminology.hl7.org/CodeSystem/citation-contribution"
    };
    /// <summary>
    /// Visualization (see https://jats4r.org/credit-taxonomy).
    /// </summary>
    public static readonly Coding Visualization = new Coding
    {
      Code = "visualization",
      Display = "Visualization",
      System = "http://terminology.hl7.org/CodeSystem/citation-contribution"
    };
    /// <summary>
    /// Writing - original draft (see https://jats4r.org/credit-taxonomy).
    /// </summary>
    public static readonly Coding WritingOriginalDraft = new Coding
    {
      Code = "writingOriginalDraft",
      Display = "Writing - original draft",
      System = "http://terminology.hl7.org/CodeSystem/citation-contribution"
    };
    /// <summary>
    /// Writing - review &amp; editing (see https://jats4r.org/credit-taxonomy).
    /// </summary>
    public static readonly Coding WritingReviewAndEditing = new Coding
    {
      Code = "writingReviewEditing",
      Display = "Writing - review & editing",
      System = "http://terminology.hl7.org/CodeSystem/citation-contribution"
    };

    /// <summary>
    /// Literal for code: Conceptualization
    /// </summary>
    public const string LiteralConceptualization = "conceptualization";

    /// <summary>
    /// Literal for code: DataCuration
    /// </summary>
    public const string LiteralDataCuration = "dataCuration";

    /// <summary>
    /// Literal for code: FormalAnalysis
    /// </summary>
    public const string LiteralFormalAnalysis = "formalAnalysis";

    /// <summary>
    /// Literal for code: FundingAcquisition
    /// </summary>
    public const string LiteralFundingAcquisition = "fundingAcquisition";

    /// <summary>
    /// Literal for code: Investigation
    /// </summary>
    public const string LiteralInvestigation = "investigation";

    /// <summary>
    /// Literal for code: Methodology
    /// </summary>
    public const string LiteralMethodology = "methodology";

    /// <summary>
    /// Literal for code: ProjectAdministration
    /// </summary>
    public const string LiteralProjectAdministration = "projectAdministration";

    /// <summary>
    /// Literal for code: Resources
    /// </summary>
    public const string LiteralResources = "resources";

    /// <summary>
    /// Literal for code: Software
    /// </summary>
    public const string LiteralSoftware = "software";

    /// <summary>
    /// Literal for code: Supervision
    /// </summary>
    public const string LiteralSupervision = "supervision";

    /// <summary>
    /// Literal for code: Validation
    /// </summary>
    public const string LiteralValidation = "validation";

    /// <summary>
    /// Literal for code: Visualization
    /// </summary>
    public const string LiteralVisualization = "visualization";

    /// <summary>
    /// Literal for code: WritingOriginalDraft
    /// </summary>
    public const string LiteralWritingOriginalDraft = "writingOriginalDraft";

    /// <summary>
    /// Literal for code: WritingReviewAndEditing
    /// </summary>
    public const string LiteralWritingReviewAndEditing = "writingReviewEditing";
  };
}
