// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// Used to code the producer or rule for creating the display string.
  /// </summary>
  public static class ContributorSummarySourceCodes
  {
    /// <summary>
    /// Data copied by human from article text.
    /// </summary>
    public static readonly Coding CopiedFromArticle = new Coding
    {
      Code = "articleCopy",
      Display = "Copied from article",
      System = "http://terminology.hl7.org/CodeSystem/contributor-summary-source"
    };
    /// <summary>
    /// Data copied by machine from citation manager data.
    /// </summary>
    public static readonly Coding ReportedByCitationManager = new Coding
    {
      Code = "citationManager",
      Display = "Reported by citation manager",
      System = "http://terminology.hl7.org/CodeSystem/contributor-summary-source"
    };
    /// <summary>
    /// Custom format (may be described in text note).
    /// </summary>
    public static readonly Coding CustomFormat = new Coding
    {
      Code = "custom",
      Display = "custom format",
      System = "http://terminology.hl7.org/CodeSystem/contributor-summary-source"
    };
    /// <summary>
    /// Data copied by machine from publisher data.
    /// </summary>
    public static readonly Coding PublisherProvided = new Coding
    {
      Code = "publisherData",
      Display = "Publisher provided",
      System = "http://terminology.hl7.org/CodeSystem/contributor-summary-source"
    };

    /// <summary>
    /// Literal for code: CopiedFromArticle
    /// </summary>
    public const string LiteralCopiedFromArticle = "articleCopy";

    /// <summary>
    /// Literal for code: ReportedByCitationManager
    /// </summary>
    public const string LiteralReportedByCitationManager = "citationManager";

    /// <summary>
    /// Literal for code: CustomFormat
    /// </summary>
    public const string LiteralCustomFormat = "custom";

    /// <summary>
    /// Literal for code: PublisherProvided
    /// </summary>
    public const string LiteralPublisherProvided = "publisherData";
  };
}
