// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// This value set contract specific codes for status.
  /// </summary>
  public static class ContractDefinitionTypeCodes
  {
    /// <summary>
    /// To be completed
    /// </summary>
    public static readonly Coding TemporaryValue = new Coding
    {
      Code = "temp",
      Display = "Temporary Value",
      System = "http://hl7.org/fhir/contract-definition-type"
    };

    /// <summary>
    /// Literal for code: TemporaryValue
    /// </summary>
    public const string LiteralTemporaryValue = "temp";
  };
}
