// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// Used to code author list statement, contributorship statement, and such.
  /// </summary>
  public static class ContributorSummaryTypeCodes
  {
    /// <summary>
    /// Display of the author list as a complete string.
    /// </summary>
    public static readonly Coding AuthorString = new Coding
    {
      Code = "authorString",
      Display = "Author string",
      System = "http://terminology.hl7.org/CodeSystem/contributor-summary-type"
    };
    /// <summary>
    /// Compiled summary of contributions.
    /// </summary>
    public static readonly Coding ContributorshipStatement = new Coding
    {
      Code = "contributorshipStatement",
      Display = "Contributorship statement",
      System = "http://terminology.hl7.org/CodeSystem/contributor-summary-type"
    };

    /// <summary>
    /// Literal for code: AuthorString
    /// </summary>
    public const string LiteralAuthorString = "authorString";

    /// <summary>
    /// Literal for code: ContributorshipStatement
    /// </summary>
    public const string LiteralContributorshipStatement = "contributorshipStatement";
  };
}
