// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// Codes identifying the lifecycle stage of a definition.
  /// </summary>
  public static class DefinitionStatusCodes
  {
    /// <summary>
    /// The definition is considered ready for use.
    /// </summary>
    public static readonly Coding Active = new Coding
    {
      Code = "active",
      Display = "Active",
      System = "http://terminology.hl7.org/CodeSystem/definition-status"
    };
    /// <summary>
    /// The definition is in the design stage and is not yet considered to be "ready for use".
    /// </summary>
    public static readonly Coding Draft = new Coding
    {
      Code = "draft",
      Display = "Draft",
      System = "http://terminology.hl7.org/CodeSystem/definition-status"
    };
    /// <summary>
    /// The authoring/source system does not know which of the status values currently applies for this resource.  Note: This concept is not to be used for "other" - one of the listed statuses is presumed to apply,  but the authoring/source system does not know which.
    /// </summary>
    public static readonly Coding Unknown = new Coding
    {
      Code = "unknown",
      Display = "Unknown",
      System = "http://terminology.hl7.org/CodeSystem/definition-status"
    };
    /// <summary>
    /// The definition should no longer be used.
    /// </summary>
    public static readonly Coding Withdrawn = new Coding
    {
      Code = "withdrawn",
      Display = "Withdrawn",
      System = "http://terminology.hl7.org/CodeSystem/definition-status"
    };

    /// <summary>
    /// Literal for code: Active
    /// </summary>
    public const string LiteralActive = "active";

    /// <summary>
    /// Literal for code: Draft
    /// </summary>
    public const string LiteralDraft = "draft";

    /// <summary>
    /// Literal for code: Unknown
    /// </summary>
    public const string LiteralUnknown = "unknown";

    /// <summary>
    /// Literal for code: Withdrawn
    /// </summary>
    public const string LiteralWithdrawn = "withdrawn";
  };
}
