// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// Codes that can be used to indicate the type of food being ordered for a patient. This value set is provided as a suggestive example. It includes codes from [SNOMED CT](http://snomed.info/sct) where concept is-a 182922004 (Dietary regime (regime/therapy)) 
  /// </summary>
  public static class DietTypeCodes
  {
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DietaryApproachesToStopHypertensionDiet = new Coding
    {
      Code = "1151000175103",
      Display = "Dietary Approaches to Stop Hypertension diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DietaryRegime = new Coding
    {
      Code = "182922004",
      Display = "Dietary regime",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DietaryProphylaxis = new Coding
    {
      Code = "182954008",
      Display = "Dietary prophylaxis",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding LowCarbohydrateDietProphylaxis = new Coding
    {
      Code = "182955009",
      Display = "Low carbohydrate diet - prophylaxis",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding LowCalorieDietProphylaxis = new Coding
    {
      Code = "182956005",
      Display = "Low calorie diet - prophylaxis",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding LowSaltDietProphylaxis = new Coding
    {
      Code = "182957001",
      Display = "Low salt diet - prophylaxis",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding SaltFreeDietProphylaxis = new Coding
    {
      Code = "182958006",
      Display = "Salt free diet - prophylaxis",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding LowProteinDietProphylaxis = new Coding
    {
      Code = "182959003",
      Display = "Low protein diet - prophylaxis",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding UnsaturatedFatDietProphylaxis = new Coding
    {
      Code = "182960008",
      Display = "Unsaturated fat diet - prophylaxis",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding NasalTubeFeeding = new Coding
    {
      Code = "183028005",
      Display = "Nasal tube feeding",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ProvisionOfASpecialDiet = new Coding
    {
      Code = "223456000",
      Display = "Provision of a special diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PEGPercutaneousEndoscopicGastrostomyFeeding = new Coding
    {
      Code = "225373002",
      Display = "PEG - Percutaneous endoscopic gastrostomy feeding",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding JejunostomyFeeding = new Coding
    {
      Code = "225374008",
      Display = "Jejunostomy feeding",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding EnteralFeeding = new Coding
    {
      Code = "229912004",
      Display = "Enteral feeding",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding OralTubeFeeding = new Coding
    {
      Code = "229913009",
      Display = "Oral tube feeding",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding NasogastricFeeding = new Coding
    {
      Code = "229914003",
      Display = "Nasogastric feeding",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding NasoduodenalFeeding = new Coding
    {
      Code = "229915002",
      Display = "Nasoduodenal feeding",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding EsophagostomyFeeding = new Coding
    {
      Code = "229916001",
      Display = "Esophagostomy feeding",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding GastrostomyFeeding = new Coding
    {
      Code = "229917005",
      Display = "Gastrostomy feeding",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DietaryTreatmentForDisorder = new Coding
    {
      Code = "284071006",
      Display = "Dietary treatment for disorder",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ButtonGastrostomyFeeding = new Coding
    {
      Code = "289133003",
      Display = "Button gastrostomy feeding",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding NasojejunalFeeding = new Coding
    {
      Code = "310244003",
      Display = "Nasojejunal feeding",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PrescribedDietaryIntake = new Coding
    {
      Code = "361231003",
      Display = "Prescribed dietary intake",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DietStaging = new Coding
    {
      Code = "386261001",
      Display = "Diet staging",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TubeFeedingBySyringeMethod = new Coding
    {
      Code = "38903004",
      Display = "Tube feeding by syringe method",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding WheatFreeDiet = new Coding
    {
      Code = "404919001",
      Display = "Wheat-free diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding AdvanceDietAsTolerated = new Coding
    {
      Code = "422972009",
      Display = "Advance diet as tolerated",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding LactoseFreeDiet = new Coding
    {
      Code = "425458000",
      Display = "Lactose-free diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CarbohydrateModifiedDiet = new Coding
    {
      Code = "435581000124102",
      Display = "Carbohydrate modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ConsistentCarbohydrateDiet = new Coding
    {
      Code = "435651000124106",
      Display = "Consistent carbohydrate diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding GalactoseModifiedDiet = new Coding
    {
      Code = "435661000124108",
      Display = "Galactose modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CholesterolModifiedDiet = new Coding
    {
      Code = "435671000124101",
      Display = "Cholesterol modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DietaryLiquidConsistencyDiet = new Coding
    {
      Code = "435681000124103",
      Display = "Dietary liquid consistency diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DietModifiedForSpecificFoodsOrIngredients = new Coding
    {
      Code = "435691000124100",
      Display = "Diet modified for specific foods or ingredients",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding EnergyModifiedDiet = new Coding
    {
      Code = "435701000124100",
      Display = "Energy modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding FatModifiedDiet = new Coding
    {
      Code = "435711000124102",
      Display = "Fat modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding FiberModifiedDiet = new Coding
    {
      Code = "435721000124105",
      Display = "Fiber modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding LiquidDiet = new Coding
    {
      Code = "435731000124108",
      Display = "Liquid diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ClearLiquidDiet = new Coding
    {
      Code = "435741000124103",
      Display = "Clear liquid diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding FullLiquidDiet = new Coding
    {
      Code = "435751000124101",
      Display = "Full liquid diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding GeneralHealthfulDiet = new Coding
    {
      Code = "435771000124106",
      Display = "General healthful diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MineralModifiedDiet = new Coding
    {
      Code = "435781000124109",
      Display = "Mineral modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ProteinModifiedDiet = new Coding
    {
      Code = "435791000124107",
      Display = "Protein modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TextureModifiedDiet = new Coding
    {
      Code = "435801000124108",
      Display = "Texture modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VitaminModifiedDiet = new Coding
    {
      Code = "435811000124106",
      Display = "Vitamin modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding LactoseModifiedDiet = new Coding
    {
      Code = "436661000124100",
      Display = "Lactose modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedLactoseDiet = new Coding
    {
      Code = "436671000124107",
      Display = "Decreased lactose diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedCarbohydrateDiet = new Coding
    {
      Code = "436681000124105",
      Display = "Increased carbohydrate diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedCarbohydrateDiet = new Coding
    {
      Code = "436691000124108",
      Display = "Decreased carbohydrate diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedGalactoseDiet = new Coding
    {
      Code = "436701000124108",
      Display = "Decreased galactose diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedCholesterolDiet = new Coding
    {
      Code = "436711000124106",
      Display = "Decreased cholesterol diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedEnergyDiet = new Coding
    {
      Code = "436721000124103",
      Display = "Increased energy diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedEnergyDiet = new Coding
    {
      Code = "436731000124100",
      Display = "Decreased energy diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedFatDiet = new Coding
    {
      Code = "436851000124101",
      Display = "Increased fat diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedFatDiet = new Coding
    {
      Code = "436861000124104",
      Display = "Decreased fat diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MonounsaturatedFatModifiedDiet = new Coding
    {
      Code = "436871000124106",
      Display = "Monounsaturated fat modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PolyunsaturatedFatModifiedDiet = new Coding
    {
      Code = "436881000124109",
      Display = "Polyunsaturated fat modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding SaturatedFatModifiedDiet = new Coding
    {
      Code = "436891000124107",
      Display = "Saturated fat modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TransFatModifiedDiet = new Coding
    {
      Code = "436901000124106",
      Display = "Trans fat modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedMonounsaturatedFatDiet = new Coding
    {
      Code = "436911000124109",
      Display = "Increased monounsaturated fat diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedMonounsaturatedFatDiet = new Coding
    {
      Code = "436921000124101",
      Display = "Decreased monounsaturated fat diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedPolyunsaturatedFatDiet = new Coding
    {
      Code = "436931000124103",
      Display = "Increased polyunsaturated fat diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedPolyunsaturatedFatDiet = new Coding
    {
      Code = "436941000124108",
      Display = "Decreased polyunsaturated fat diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedSaturatedFatDiet = new Coding
    {
      Code = "436951000124105",
      Display = "Decreased saturated fat diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedTransFatDiet = new Coding
    {
      Code = "436961000124107",
      Display = "Decreased trans fat diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedFiberDiet = new Coding
    {
      Code = "436991000124104",
      Display = "Increased fiber diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedFiberDiet = new Coding
    {
      Code = "437001000124107",
      Display = "Decreased fiber diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding SolubleFiberModifiedDiet = new Coding
    {
      Code = "437011000124105",
      Display = "Soluble fiber modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding InsolubleFiberModifiedDiet = new Coding
    {
      Code = "437021000124102",
      Display = "Insoluble fiber modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedSolubleFiberDiet = new Coding
    {
      Code = "437031000124104",
      Display = "Increased soluble fiber diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedSolubleFiberDiet = new Coding
    {
      Code = "437041000124109",
      Display = "Decreased soluble fiber diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedInsolubleFiberDiet = new Coding
    {
      Code = "437051000124106",
      Display = "Increased insoluble fiber diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedInsolubleFiberDiet = new Coding
    {
      Code = "437061000124108",
      Display = "Decreased insoluble fiber diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding BoronModifiedDiet = new Coding
    {
      Code = "437081000124103",
      Display = "Boron modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CalciumModifiedDiet = new Coding
    {
      Code = "437091000124100",
      Display = "Calcium modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ChlorideModifiedDiet = new Coding
    {
      Code = "437101000124106",
      Display = "Chloride modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ChromiumModifiedDiet = new Coding
    {
      Code = "437111000124109",
      Display = "Chromium modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CobaltModifiedDiet = new Coding
    {
      Code = "437121000124101",
      Display = "Cobalt modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CopperModifiedDiet = new Coding
    {
      Code = "437131000124103",
      Display = "Copper modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding FluorideModifiedDiet = new Coding
    {
      Code = "437141000124108",
      Display = "Fluoride modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IodineModifiedDiet = new Coding
    {
      Code = "437151000124105",
      Display = "Iodine modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IronModifiedDiet = new Coding
    {
      Code = "437161000124107",
      Display = "Iron modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MagnesiumModifiedDiet = new Coding
    {
      Code = "437171000124100",
      Display = "Magnesium modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ManganeseModifiedDiet = new Coding
    {
      Code = "437181000124102",
      Display = "Manganese modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MolybdenumModifiedDiet = new Coding
    {
      Code = "437191000124104",
      Display = "Molybdenum modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PhosphorusModifiedDiet = new Coding
    {
      Code = "437201000124101",
      Display = "Phosphorus modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PotassiumModifiedDiet = new Coding
    {
      Code = "437211000124103",
      Display = "Potassium modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding SeleniumModifiedDiet = new Coding
    {
      Code = "437221000124106",
      Display = "Selenium modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding SodiumModifiedDiet = new Coding
    {
      Code = "437231000124109",
      Display = "Sodium modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding SulfurModifiedDiet = new Coding
    {
      Code = "437241000124104",
      Display = "Sulfur modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ZincModifiedDiet = new Coding
    {
      Code = "437251000124102",
      Display = "Zinc modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedCalciumDiet = new Coding
    {
      Code = "437261000124100",
      Display = "Increased calcium diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedCalciumDiet = new Coding
    {
      Code = "437271000124107",
      Display = "Decreased calcium diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedChromiumDiet = new Coding
    {
      Code = "437281000124105",
      Display = "Increased chromium diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedCopperDiet = new Coding
    {
      Code = "437291000124108",
      Display = "Increased copper diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedCopperDiet = new Coding
    {
      Code = "437301000124109",
      Display = "Decreased copper diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedIodineDiet = new Coding
    {
      Code = "437311000124107",
      Display = "Increased iodine diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedIodineDiet = new Coding
    {
      Code = "437321000124104",
      Display = "Decreased iodine diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedIronDiet = new Coding
    {
      Code = "437331000124101",
      Display = "Increased iron diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedIronDiet = new Coding
    {
      Code = "437341000124106",
      Display = "Decreased iron diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedMagnesiumDiet = new Coding
    {
      Code = "437351000124108",
      Display = "Increased magnesium diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedMagnesiumDiet = new Coding
    {
      Code = "437361000124105",
      Display = "Decreased magnesium diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedPhosphorusDiet = new Coding
    {
      Code = "437371000124103",
      Display = "Increased phosphorus diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedPhosphorusDiet = new Coding
    {
      Code = "437381000124100",
      Display = "Decreased phosphorus diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HighPotassiumDiet = new Coding
    {
      Code = "437391000124102",
      Display = "High potassium diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedPotassiumDiet = new Coding
    {
      Code = "437401000124100",
      Display = "Decreased potassium diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedSodiumDiet = new Coding
    {
      Code = "437411000124102",
      Display = "Increased sodium diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedSodiumDiet = new Coding
    {
      Code = "437421000124105",
      Display = "Decreased sodium diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedZincDiet = new Coding
    {
      Code = "437431000124108",
      Display = "Increased zinc diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedZincDiet = new Coding
    {
      Code = "437441000124103",
      Display = "Decreased zinc diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ConsistentProteinDiet = new Coding
    {
      Code = "437451000124101",
      Display = "Consistent protein diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedProteinDiet = new Coding
    {
      Code = "437461000124104",
      Display = "Increased protein diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedProteinDiet = new Coding
    {
      Code = "437471000124106",
      Display = "Decreased protein diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding AminoAcidModifiedDiet = new Coding
    {
      Code = "437481000124109",
      Display = "Amino acid modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ArginineModifiedDiet = new Coding
    {
      Code = "437491000124107",
      Display = "Arginine modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding GlutamineModifiedDiet = new Coding
    {
      Code = "437501000124104",
      Display = "Glutamine modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HistidineModifiedDiet = new Coding
    {
      Code = "437511000124101",
      Display = "Histidine modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedHomocysteineDiet = new Coding
    {
      Code = "437521000124109",
      Display = "Increased homocysteine diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IsoleucineModifiedDiet = new Coding
    {
      Code = "437531000124107",
      Display = "Isoleucine modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding LeucineModifiedDiet = new Coding
    {
      Code = "437541000124102",
      Display = "Leucine modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding LysineModifiedDiet = new Coding
    {
      Code = "437551000124100",
      Display = "Lysine modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MethionineModifiedDiet = new Coding
    {
      Code = "437561000124103",
      Display = "Methionine modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedPhenylalanineDiet = new Coding
    {
      Code = "437571000124105",
      Display = "Decreased phenylalanine diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ThreonineModifiedDiet = new Coding
    {
      Code = "437581000124108",
      Display = "Threonine modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TryptophanModifiedDiet = new Coding
    {
      Code = "437591000124106",
      Display = "Tryptophan modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedTyramineDiet = new Coding
    {
      Code = "437601000124103",
      Display = "Decreased tyramine diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TyrosineModifiedDiet = new Coding
    {
      Code = "437611000124100",
      Display = "Tyrosine modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ValineModifiedDiet = new Coding
    {
      Code = "437621000124108",
      Display = "Valine modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedCaseinDiet = new Coding
    {
      Code = "437631000124106",
      Display = "Decreased casein diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedGlutenDiet = new Coding
    {
      Code = "437641000124101",
      Display = "Decreased gluten diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding GlutenFreeDiet = new Coding
    {
      Code = "437651000124104",
      Display = "Gluten free diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedArginineDiet = new Coding
    {
      Code = "437661000124102",
      Display = "Increased arginine diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedArginineDiet = new Coding
    {
      Code = "437671000124109",
      Display = "Decreased arginine diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedGlutamineDiet = new Coding
    {
      Code = "437681000124107",
      Display = "Increased glutamine diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedGlutamineDiet = new Coding
    {
      Code = "437691000124105",
      Display = "Decreased glutamine diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedHistidineDiet = new Coding
    {
      Code = "437701000124105",
      Display = "Increased histidine diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedHistidineDiet = new Coding
    {
      Code = "437711000124108",
      Display = "Decreased histidine diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedIsoleucineDiet = new Coding
    {
      Code = "437721000124100",
      Display = "Increased isoleucine diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedIsoleucineDiet = new Coding
    {
      Code = "437731000124102",
      Display = "Decreased isoleucine diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedLeucineDiet = new Coding
    {
      Code = "437741000124107",
      Display = "Increased leucine diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedLeucineDiet = new Coding
    {
      Code = "437751000124109",
      Display = "Decreased leucine diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedLysineDiet = new Coding
    {
      Code = "437761000124106",
      Display = "Increased lysine diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedLysineDiet = new Coding
    {
      Code = "437771000124104",
      Display = "Decreased lysine diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedMethionineDiet = new Coding
    {
      Code = "437781000124101",
      Display = "Increased methionine diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedMethionineDiet = new Coding
    {
      Code = "437791000124103",
      Display = "Decreased methionine diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedThreonineDiet = new Coding
    {
      Code = "437801000124102",
      Display = "Increased threonine diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedThreonineDiet = new Coding
    {
      Code = "437811000124104",
      Display = "Decreased threonine diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedTryptophanDiet = new Coding
    {
      Code = "437821000124107",
      Display = "Increased tryptophan diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedTryptophanDiet = new Coding
    {
      Code = "437831000124105",
      Display = "Decreased tryptophan diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedTyrosineDiet = new Coding
    {
      Code = "437841000124100",
      Display = "Increased tyrosine diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedTyrosineDiet = new Coding
    {
      Code = "437851000124103",
      Display = "Decreased tyrosine diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedValineDiet = new Coding
    {
      Code = "437861000124101",
      Display = "Increased valine diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedValineDiet = new Coding
    {
      Code = "437871000124108",
      Display = "Decreased valine diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding BiotinModifiedDiet = new Coding
    {
      Code = "438001000124106",
      Display = "Biotin modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding FolicAcidModifiedDiet = new Coding
    {
      Code = "438011000124109",
      Display = "Folic acid modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding NiacinModifiedDiet = new Coding
    {
      Code = "438021000124101",
      Display = "Niacin modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PantothenicAcidModifiedDiet = new Coding
    {
      Code = "438031000124103",
      Display = "Pantothenic acid modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding RiboflavinModifiedDiet = new Coding
    {
      Code = "438041000124108",
      Display = "Riboflavin modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ThiamineModifiedDiet = new Coding
    {
      Code = "438051000124105",
      Display = "Thiamine modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VitaminAModifiedDiet = new Coding
    {
      Code = "438061000124107",
      Display = "Vitamin A modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VitaminB6ModifiedDiet = new Coding
    {
      Code = "438071000124100",
      Display = "Vitamin B6 modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VitaminB12ModifiedDiet = new Coding
    {
      Code = "438081000124102",
      Display = "Vitamin B12 modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VitaminCModifiedDiet = new Coding
    {
      Code = "438091000124104",
      Display = "Vitamin C modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VitaminDModifiedDiet = new Coding
    {
      Code = "438101000124105",
      Display = "Vitamin D modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VitaminEModifiedDiet = new Coding
    {
      Code = "438111000124108",
      Display = "Vitamin E modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VitaminKModifiedDiet = new Coding
    {
      Code = "438121000124100",
      Display = "Vitamin K modified diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedBiotinDiet = new Coding
    {
      Code = "438131000124102",
      Display = "Increased biotin diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedBiotinDiet = new Coding
    {
      Code = "438141000124107",
      Display = "Decreased biotin diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedFolicAcidDiet = new Coding
    {
      Code = "438151000124109",
      Display = "Increased folic acid diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedFolicAcidDiet = new Coding
    {
      Code = "438161000124106",
      Display = "Decreased folic acid diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedNiacinDiet = new Coding
    {
      Code = "438171000124104",
      Display = "Increased niacin diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedNiacinDiet = new Coding
    {
      Code = "438181000124101",
      Display = "Decreased niacin diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedPantothenicAcidDiet = new Coding
    {
      Code = "438191000124103",
      Display = "Increased pantothenic acid diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedPantothenicAcidDiet = new Coding
    {
      Code = "438201000124100",
      Display = "Decreased pantothenic acid diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedRiboflavinDiet = new Coding
    {
      Code = "438211000124102",
      Display = "Increased riboflavin diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedRiboflavinDiet = new Coding
    {
      Code = "438221000124105",
      Display = "Decreased riboflavin diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedThiamineDiet = new Coding
    {
      Code = "438231000124108",
      Display = "Increased thiamine diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedThiamineDiet = new Coding
    {
      Code = "438241000124103",
      Display = "Decreased thiamine diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedVitaminADiet = new Coding
    {
      Code = "438251000124101",
      Display = "Increased vitamin A diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedVitaminADiet = new Coding
    {
      Code = "438261000124104",
      Display = "Decreased vitamin A diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedVitaminB12Diet = new Coding
    {
      Code = "438271000124106",
      Display = "Increased vitamin B12 diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedVitaminB12Diet = new Coding
    {
      Code = "438281000124109",
      Display = "Decreased vitamin B12 diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedVitaminB6Diet = new Coding
    {
      Code = "438291000124107",
      Display = "Increased vitamin B6 diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedVitaminB6Diet = new Coding
    {
      Code = "438301000124108",
      Display = "Decreased vitamin B6 diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedVitaminCDiet = new Coding
    {
      Code = "438311000124106",
      Display = "Increased vitamin C diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedVitaminCDiet = new Coding
    {
      Code = "438321000124103",
      Display = "Decreased vitamin C diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedVitaminDDiet = new Coding
    {
      Code = "438331000124100",
      Display = "Increased vitamin D diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedVitaminDDiet = new Coding
    {
      Code = "438341000124105",
      Display = "Decreased vitamin D diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedVitaminEDiet = new Coding
    {
      Code = "438351000124107",
      Display = "Increased vitamin E diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedVitaminEDiet = new Coding
    {
      Code = "438361000124109",
      Display = "Decreased vitamin E diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedVitaminKDiet = new Coding
    {
      Code = "438371000124102",
      Display = "Increased vitamin K diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DecreasedVitaminKDiet = new Coding
    {
      Code = "438381000124104",
      Display = "Decreased vitamin K diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DietaryLiquidConsistencyNectarThickLiquid = new Coding
    {
      Code = "439021000124105",
      Display = "Dietary liquid consistency - nectar thick liquid",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DietaryLiquidConsistencyHoneyThickLiquid = new Coding
    {
      Code = "439031000124108",
      Display = "Dietary liquid consistency - honey thick liquid",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DietaryLiquidConsistencySpoonThickLiquid = new Coding
    {
      Code = "439041000124103",
      Display = "Dietary liquid consistency - spoon thick liquid",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding FluidRestrictedDiet = new Coding
    {
      Code = "439061000124104",
      Display = "Fluid restricted diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IncreasedFluidDiet = new Coding
    {
      Code = "439071000124106",
      Display = "Increased fluid diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DietaryLiquidConsistencyThinLiquid = new Coding
    {
      Code = "439081000124109",
      Display = "Dietary liquid consistency - thin liquid",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding EasyToChewDiet = new Coding
    {
      Code = "439101000124101",
      Display = "Easy to chew diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MechanicallyAlteredDiet = new Coding
    {
      Code = "439111000124103",
      Display = "Mechanically altered diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PureedDiet = new Coding
    {
      Code = "439121000124106",
      Display = "Pureed diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ModificationOfNutritionalRegime = new Coding
    {
      Code = "445341000124100",
      Display = "Modification of nutritional regime",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ModificationOfScheduleOfOralIntake = new Coding
    {
      Code = "445351000124103",
      Display = "Modification of schedule of oral intake",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TubeFeedingByBarronPump = new Coding
    {
      Code = "50712000",
      Display = "Tube feeding by Barron pump",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TubeFeedingByDripMethod = new Coding
    {
      Code = "56948003",
      Display = "Tube feeding by drip method",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TubeFeedingOfPatient = new Coding
    {
      Code = "61420007",
      Display = "Tube feeding of patient",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ModifiedFluidDiet = new Coding
    {
      Code = "762104002",
      Display = "Modified fluid diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VegetarianDiet = new Coding
    {
      Code = "765021002",
      Display = "Vegetarian diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding LactoVegetarianDiet = new Coding
    {
      Code = "765022009",
      Display = "Lacto-vegetarian diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding LactoOvoVegetarianDiet = new Coding
    {
      Code = "765023004",
      Display = "Lacto-ovo-vegetarian diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding AtkinsDiet = new Coding
    {
      Code = "765024005",
      Display = "Atkins diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding KosherDiet = new Coding
    {
      Code = "765025006",
      Display = "Kosher diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HinduDiet = new Coding
    {
      Code = "765052001",
      Display = "Hindu diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding LowFructoseDiet = new Coding
    {
      Code = "765053006",
      Display = "Low fructose diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding KetogenicDiet = new Coding
    {
      Code = "765060000",
      Display = "Ketogenic diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CantoneseDiet = new Coding
    {
      Code = "765063003",
      Display = "Cantonese diet",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Fasting = new Coding
    {
      Code = "792805006",
      Display = "Fasting",
      System = "http://snomed.info/sct"
    };

    /// <summary>
    /// Literal for code: DietaryApproachesToStopHypertensionDiet
    /// </summary>
    public const string LiteralDietaryApproachesToStopHypertensionDiet = "1151000175103";

    /// <summary>
    /// Literal for code: DietaryRegime
    /// </summary>
    public const string LiteralDietaryRegime = "182922004";

    /// <summary>
    /// Literal for code: DietaryProphylaxis
    /// </summary>
    public const string LiteralDietaryProphylaxis = "182954008";

    /// <summary>
    /// Literal for code: LowCarbohydrateDietProphylaxis
    /// </summary>
    public const string LiteralLowCarbohydrateDietProphylaxis = "182955009";

    /// <summary>
    /// Literal for code: LowCalorieDietProphylaxis
    /// </summary>
    public const string LiteralLowCalorieDietProphylaxis = "182956005";

    /// <summary>
    /// Literal for code: LowSaltDietProphylaxis
    /// </summary>
    public const string LiteralLowSaltDietProphylaxis = "182957001";

    /// <summary>
    /// Literal for code: SaltFreeDietProphylaxis
    /// </summary>
    public const string LiteralSaltFreeDietProphylaxis = "182958006";

    /// <summary>
    /// Literal for code: LowProteinDietProphylaxis
    /// </summary>
    public const string LiteralLowProteinDietProphylaxis = "182959003";

    /// <summary>
    /// Literal for code: UnsaturatedFatDietProphylaxis
    /// </summary>
    public const string LiteralUnsaturatedFatDietProphylaxis = "182960008";

    /// <summary>
    /// Literal for code: NasalTubeFeeding
    /// </summary>
    public const string LiteralNasalTubeFeeding = "183028005";

    /// <summary>
    /// Literal for code: ProvisionOfASpecialDiet
    /// </summary>
    public const string LiteralProvisionOfASpecialDiet = "223456000";

    /// <summary>
    /// Literal for code: PEGPercutaneousEndoscopicGastrostomyFeeding
    /// </summary>
    public const string LiteralPEGPercutaneousEndoscopicGastrostomyFeeding = "225373002";

    /// <summary>
    /// Literal for code: JejunostomyFeeding
    /// </summary>
    public const string LiteralJejunostomyFeeding = "225374008";

    /// <summary>
    /// Literal for code: EnteralFeeding
    /// </summary>
    public const string LiteralEnteralFeeding = "229912004";

    /// <summary>
    /// Literal for code: OralTubeFeeding
    /// </summary>
    public const string LiteralOralTubeFeeding = "229913009";

    /// <summary>
    /// Literal for code: NasogastricFeeding
    /// </summary>
    public const string LiteralNasogastricFeeding = "229914003";

    /// <summary>
    /// Literal for code: NasoduodenalFeeding
    /// </summary>
    public const string LiteralNasoduodenalFeeding = "229915002";

    /// <summary>
    /// Literal for code: EsophagostomyFeeding
    /// </summary>
    public const string LiteralEsophagostomyFeeding = "229916001";

    /// <summary>
    /// Literal for code: GastrostomyFeeding
    /// </summary>
    public const string LiteralGastrostomyFeeding = "229917005";

    /// <summary>
    /// Literal for code: DietaryTreatmentForDisorder
    /// </summary>
    public const string LiteralDietaryTreatmentForDisorder = "284071006";

    /// <summary>
    /// Literal for code: ButtonGastrostomyFeeding
    /// </summary>
    public const string LiteralButtonGastrostomyFeeding = "289133003";

    /// <summary>
    /// Literal for code: NasojejunalFeeding
    /// </summary>
    public const string LiteralNasojejunalFeeding = "310244003";

    /// <summary>
    /// Literal for code: PrescribedDietaryIntake
    /// </summary>
    public const string LiteralPrescribedDietaryIntake = "361231003";

    /// <summary>
    /// Literal for code: DietStaging
    /// </summary>
    public const string LiteralDietStaging = "386261001";

    /// <summary>
    /// Literal for code: TubeFeedingBySyringeMethod
    /// </summary>
    public const string LiteralTubeFeedingBySyringeMethod = "38903004";

    /// <summary>
    /// Literal for code: WheatFreeDiet
    /// </summary>
    public const string LiteralWheatFreeDiet = "404919001";

    /// <summary>
    /// Literal for code: AdvanceDietAsTolerated
    /// </summary>
    public const string LiteralAdvanceDietAsTolerated = "422972009";

    /// <summary>
    /// Literal for code: LactoseFreeDiet
    /// </summary>
    public const string LiteralLactoseFreeDiet = "425458000";

    /// <summary>
    /// Literal for code: CarbohydrateModifiedDiet
    /// </summary>
    public const string LiteralCarbohydrateModifiedDiet = "435581000124102";

    /// <summary>
    /// Literal for code: ConsistentCarbohydrateDiet
    /// </summary>
    public const string LiteralConsistentCarbohydrateDiet = "435651000124106";

    /// <summary>
    /// Literal for code: GalactoseModifiedDiet
    /// </summary>
    public const string LiteralGalactoseModifiedDiet = "435661000124108";

    /// <summary>
    /// Literal for code: CholesterolModifiedDiet
    /// </summary>
    public const string LiteralCholesterolModifiedDiet = "435671000124101";

    /// <summary>
    /// Literal for code: DietaryLiquidConsistencyDiet
    /// </summary>
    public const string LiteralDietaryLiquidConsistencyDiet = "435681000124103";

    /// <summary>
    /// Literal for code: DietModifiedForSpecificFoodsOrIngredients
    /// </summary>
    public const string LiteralDietModifiedForSpecificFoodsOrIngredients = "435691000124100";

    /// <summary>
    /// Literal for code: EnergyModifiedDiet
    /// </summary>
    public const string LiteralEnergyModifiedDiet = "435701000124100";

    /// <summary>
    /// Literal for code: FatModifiedDiet
    /// </summary>
    public const string LiteralFatModifiedDiet = "435711000124102";

    /// <summary>
    /// Literal for code: FiberModifiedDiet
    /// </summary>
    public const string LiteralFiberModifiedDiet = "435721000124105";

    /// <summary>
    /// Literal for code: LiquidDiet
    /// </summary>
    public const string LiteralLiquidDiet = "435731000124108";

    /// <summary>
    /// Literal for code: ClearLiquidDiet
    /// </summary>
    public const string LiteralClearLiquidDiet = "435741000124103";

    /// <summary>
    /// Literal for code: FullLiquidDiet
    /// </summary>
    public const string LiteralFullLiquidDiet = "435751000124101";

    /// <summary>
    /// Literal for code: GeneralHealthfulDiet
    /// </summary>
    public const string LiteralGeneralHealthfulDiet = "435771000124106";

    /// <summary>
    /// Literal for code: MineralModifiedDiet
    /// </summary>
    public const string LiteralMineralModifiedDiet = "435781000124109";

    /// <summary>
    /// Literal for code: ProteinModifiedDiet
    /// </summary>
    public const string LiteralProteinModifiedDiet = "435791000124107";

    /// <summary>
    /// Literal for code: TextureModifiedDiet
    /// </summary>
    public const string LiteralTextureModifiedDiet = "435801000124108";

    /// <summary>
    /// Literal for code: VitaminModifiedDiet
    /// </summary>
    public const string LiteralVitaminModifiedDiet = "435811000124106";

    /// <summary>
    /// Literal for code: LactoseModifiedDiet
    /// </summary>
    public const string LiteralLactoseModifiedDiet = "436661000124100";

    /// <summary>
    /// Literal for code: DecreasedLactoseDiet
    /// </summary>
    public const string LiteralDecreasedLactoseDiet = "436671000124107";

    /// <summary>
    /// Literal for code: IncreasedCarbohydrateDiet
    /// </summary>
    public const string LiteralIncreasedCarbohydrateDiet = "436681000124105";

    /// <summary>
    /// Literal for code: DecreasedCarbohydrateDiet
    /// </summary>
    public const string LiteralDecreasedCarbohydrateDiet = "436691000124108";

    /// <summary>
    /// Literal for code: DecreasedGalactoseDiet
    /// </summary>
    public const string LiteralDecreasedGalactoseDiet = "436701000124108";

    /// <summary>
    /// Literal for code: DecreasedCholesterolDiet
    /// </summary>
    public const string LiteralDecreasedCholesterolDiet = "436711000124106";

    /// <summary>
    /// Literal for code: IncreasedEnergyDiet
    /// </summary>
    public const string LiteralIncreasedEnergyDiet = "436721000124103";

    /// <summary>
    /// Literal for code: DecreasedEnergyDiet
    /// </summary>
    public const string LiteralDecreasedEnergyDiet = "436731000124100";

    /// <summary>
    /// Literal for code: IncreasedFatDiet
    /// </summary>
    public const string LiteralIncreasedFatDiet = "436851000124101";

    /// <summary>
    /// Literal for code: DecreasedFatDiet
    /// </summary>
    public const string LiteralDecreasedFatDiet = "436861000124104";

    /// <summary>
    /// Literal for code: MonounsaturatedFatModifiedDiet
    /// </summary>
    public const string LiteralMonounsaturatedFatModifiedDiet = "436871000124106";

    /// <summary>
    /// Literal for code: PolyunsaturatedFatModifiedDiet
    /// </summary>
    public const string LiteralPolyunsaturatedFatModifiedDiet = "436881000124109";

    /// <summary>
    /// Literal for code: SaturatedFatModifiedDiet
    /// </summary>
    public const string LiteralSaturatedFatModifiedDiet = "436891000124107";

    /// <summary>
    /// Literal for code: TransFatModifiedDiet
    /// </summary>
    public const string LiteralTransFatModifiedDiet = "436901000124106";

    /// <summary>
    /// Literal for code: IncreasedMonounsaturatedFatDiet
    /// </summary>
    public const string LiteralIncreasedMonounsaturatedFatDiet = "436911000124109";

    /// <summary>
    /// Literal for code: DecreasedMonounsaturatedFatDiet
    /// </summary>
    public const string LiteralDecreasedMonounsaturatedFatDiet = "436921000124101";

    /// <summary>
    /// Literal for code: IncreasedPolyunsaturatedFatDiet
    /// </summary>
    public const string LiteralIncreasedPolyunsaturatedFatDiet = "436931000124103";

    /// <summary>
    /// Literal for code: DecreasedPolyunsaturatedFatDiet
    /// </summary>
    public const string LiteralDecreasedPolyunsaturatedFatDiet = "436941000124108";

    /// <summary>
    /// Literal for code: DecreasedSaturatedFatDiet
    /// </summary>
    public const string LiteralDecreasedSaturatedFatDiet = "436951000124105";

    /// <summary>
    /// Literal for code: DecreasedTransFatDiet
    /// </summary>
    public const string LiteralDecreasedTransFatDiet = "436961000124107";

    /// <summary>
    /// Literal for code: IncreasedFiberDiet
    /// </summary>
    public const string LiteralIncreasedFiberDiet = "436991000124104";

    /// <summary>
    /// Literal for code: DecreasedFiberDiet
    /// </summary>
    public const string LiteralDecreasedFiberDiet = "437001000124107";

    /// <summary>
    /// Literal for code: SolubleFiberModifiedDiet
    /// </summary>
    public const string LiteralSolubleFiberModifiedDiet = "437011000124105";

    /// <summary>
    /// Literal for code: InsolubleFiberModifiedDiet
    /// </summary>
    public const string LiteralInsolubleFiberModifiedDiet = "437021000124102";

    /// <summary>
    /// Literal for code: IncreasedSolubleFiberDiet
    /// </summary>
    public const string LiteralIncreasedSolubleFiberDiet = "437031000124104";

    /// <summary>
    /// Literal for code: DecreasedSolubleFiberDiet
    /// </summary>
    public const string LiteralDecreasedSolubleFiberDiet = "437041000124109";

    /// <summary>
    /// Literal for code: IncreasedInsolubleFiberDiet
    /// </summary>
    public const string LiteralIncreasedInsolubleFiberDiet = "437051000124106";

    /// <summary>
    /// Literal for code: DecreasedInsolubleFiberDiet
    /// </summary>
    public const string LiteralDecreasedInsolubleFiberDiet = "437061000124108";

    /// <summary>
    /// Literal for code: BoronModifiedDiet
    /// </summary>
    public const string LiteralBoronModifiedDiet = "437081000124103";

    /// <summary>
    /// Literal for code: CalciumModifiedDiet
    /// </summary>
    public const string LiteralCalciumModifiedDiet = "437091000124100";

    /// <summary>
    /// Literal for code: ChlorideModifiedDiet
    /// </summary>
    public const string LiteralChlorideModifiedDiet = "437101000124106";

    /// <summary>
    /// Literal for code: ChromiumModifiedDiet
    /// </summary>
    public const string LiteralChromiumModifiedDiet = "437111000124109";

    /// <summary>
    /// Literal for code: CobaltModifiedDiet
    /// </summary>
    public const string LiteralCobaltModifiedDiet = "437121000124101";

    /// <summary>
    /// Literal for code: CopperModifiedDiet
    /// </summary>
    public const string LiteralCopperModifiedDiet = "437131000124103";

    /// <summary>
    /// Literal for code: FluorideModifiedDiet
    /// </summary>
    public const string LiteralFluorideModifiedDiet = "437141000124108";

    /// <summary>
    /// Literal for code: IodineModifiedDiet
    /// </summary>
    public const string LiteralIodineModifiedDiet = "437151000124105";

    /// <summary>
    /// Literal for code: IronModifiedDiet
    /// </summary>
    public const string LiteralIronModifiedDiet = "437161000124107";

    /// <summary>
    /// Literal for code: MagnesiumModifiedDiet
    /// </summary>
    public const string LiteralMagnesiumModifiedDiet = "437171000124100";

    /// <summary>
    /// Literal for code: ManganeseModifiedDiet
    /// </summary>
    public const string LiteralManganeseModifiedDiet = "437181000124102";

    /// <summary>
    /// Literal for code: MolybdenumModifiedDiet
    /// </summary>
    public const string LiteralMolybdenumModifiedDiet = "437191000124104";

    /// <summary>
    /// Literal for code: PhosphorusModifiedDiet
    /// </summary>
    public const string LiteralPhosphorusModifiedDiet = "437201000124101";

    /// <summary>
    /// Literal for code: PotassiumModifiedDiet
    /// </summary>
    public const string LiteralPotassiumModifiedDiet = "437211000124103";

    /// <summary>
    /// Literal for code: SeleniumModifiedDiet
    /// </summary>
    public const string LiteralSeleniumModifiedDiet = "437221000124106";

    /// <summary>
    /// Literal for code: SodiumModifiedDiet
    /// </summary>
    public const string LiteralSodiumModifiedDiet = "437231000124109";

    /// <summary>
    /// Literal for code: SulfurModifiedDiet
    /// </summary>
    public const string LiteralSulfurModifiedDiet = "437241000124104";

    /// <summary>
    /// Literal for code: ZincModifiedDiet
    /// </summary>
    public const string LiteralZincModifiedDiet = "437251000124102";

    /// <summary>
    /// Literal for code: IncreasedCalciumDiet
    /// </summary>
    public const string LiteralIncreasedCalciumDiet = "437261000124100";

    /// <summary>
    /// Literal for code: DecreasedCalciumDiet
    /// </summary>
    public const string LiteralDecreasedCalciumDiet = "437271000124107";

    /// <summary>
    /// Literal for code: IncreasedChromiumDiet
    /// </summary>
    public const string LiteralIncreasedChromiumDiet = "437281000124105";

    /// <summary>
    /// Literal for code: IncreasedCopperDiet
    /// </summary>
    public const string LiteralIncreasedCopperDiet = "437291000124108";

    /// <summary>
    /// Literal for code: DecreasedCopperDiet
    /// </summary>
    public const string LiteralDecreasedCopperDiet = "437301000124109";

    /// <summary>
    /// Literal for code: IncreasedIodineDiet
    /// </summary>
    public const string LiteralIncreasedIodineDiet = "437311000124107";

    /// <summary>
    /// Literal for code: DecreasedIodineDiet
    /// </summary>
    public const string LiteralDecreasedIodineDiet = "437321000124104";

    /// <summary>
    /// Literal for code: IncreasedIronDiet
    /// </summary>
    public const string LiteralIncreasedIronDiet = "437331000124101";

    /// <summary>
    /// Literal for code: DecreasedIronDiet
    /// </summary>
    public const string LiteralDecreasedIronDiet = "437341000124106";

    /// <summary>
    /// Literal for code: IncreasedMagnesiumDiet
    /// </summary>
    public const string LiteralIncreasedMagnesiumDiet = "437351000124108";

    /// <summary>
    /// Literal for code: DecreasedMagnesiumDiet
    /// </summary>
    public const string LiteralDecreasedMagnesiumDiet = "437361000124105";

    /// <summary>
    /// Literal for code: IncreasedPhosphorusDiet
    /// </summary>
    public const string LiteralIncreasedPhosphorusDiet = "437371000124103";

    /// <summary>
    /// Literal for code: DecreasedPhosphorusDiet
    /// </summary>
    public const string LiteralDecreasedPhosphorusDiet = "437381000124100";

    /// <summary>
    /// Literal for code: HighPotassiumDiet
    /// </summary>
    public const string LiteralHighPotassiumDiet = "437391000124102";

    /// <summary>
    /// Literal for code: DecreasedPotassiumDiet
    /// </summary>
    public const string LiteralDecreasedPotassiumDiet = "437401000124100";

    /// <summary>
    /// Literal for code: IncreasedSodiumDiet
    /// </summary>
    public const string LiteralIncreasedSodiumDiet = "437411000124102";

    /// <summary>
    /// Literal for code: DecreasedSodiumDiet
    /// </summary>
    public const string LiteralDecreasedSodiumDiet = "437421000124105";

    /// <summary>
    /// Literal for code: IncreasedZincDiet
    /// </summary>
    public const string LiteralIncreasedZincDiet = "437431000124108";

    /// <summary>
    /// Literal for code: DecreasedZincDiet
    /// </summary>
    public const string LiteralDecreasedZincDiet = "437441000124103";

    /// <summary>
    /// Literal for code: ConsistentProteinDiet
    /// </summary>
    public const string LiteralConsistentProteinDiet = "437451000124101";

    /// <summary>
    /// Literal for code: IncreasedProteinDiet
    /// </summary>
    public const string LiteralIncreasedProteinDiet = "437461000124104";

    /// <summary>
    /// Literal for code: DecreasedProteinDiet
    /// </summary>
    public const string LiteralDecreasedProteinDiet = "437471000124106";

    /// <summary>
    /// Literal for code: AminoAcidModifiedDiet
    /// </summary>
    public const string LiteralAminoAcidModifiedDiet = "437481000124109";

    /// <summary>
    /// Literal for code: ArginineModifiedDiet
    /// </summary>
    public const string LiteralArginineModifiedDiet = "437491000124107";

    /// <summary>
    /// Literal for code: GlutamineModifiedDiet
    /// </summary>
    public const string LiteralGlutamineModifiedDiet = "437501000124104";

    /// <summary>
    /// Literal for code: HistidineModifiedDiet
    /// </summary>
    public const string LiteralHistidineModifiedDiet = "437511000124101";

    /// <summary>
    /// Literal for code: IncreasedHomocysteineDiet
    /// </summary>
    public const string LiteralIncreasedHomocysteineDiet = "437521000124109";

    /// <summary>
    /// Literal for code: IsoleucineModifiedDiet
    /// </summary>
    public const string LiteralIsoleucineModifiedDiet = "437531000124107";

    /// <summary>
    /// Literal for code: LeucineModifiedDiet
    /// </summary>
    public const string LiteralLeucineModifiedDiet = "437541000124102";

    /// <summary>
    /// Literal for code: LysineModifiedDiet
    /// </summary>
    public const string LiteralLysineModifiedDiet = "437551000124100";

    /// <summary>
    /// Literal for code: MethionineModifiedDiet
    /// </summary>
    public const string LiteralMethionineModifiedDiet = "437561000124103";

    /// <summary>
    /// Literal for code: DecreasedPhenylalanineDiet
    /// </summary>
    public const string LiteralDecreasedPhenylalanineDiet = "437571000124105";

    /// <summary>
    /// Literal for code: ThreonineModifiedDiet
    /// </summary>
    public const string LiteralThreonineModifiedDiet = "437581000124108";

    /// <summary>
    /// Literal for code: TryptophanModifiedDiet
    /// </summary>
    public const string LiteralTryptophanModifiedDiet = "437591000124106";

    /// <summary>
    /// Literal for code: DecreasedTyramineDiet
    /// </summary>
    public const string LiteralDecreasedTyramineDiet = "437601000124103";

    /// <summary>
    /// Literal for code: TyrosineModifiedDiet
    /// </summary>
    public const string LiteralTyrosineModifiedDiet = "437611000124100";

    /// <summary>
    /// Literal for code: ValineModifiedDiet
    /// </summary>
    public const string LiteralValineModifiedDiet = "437621000124108";

    /// <summary>
    /// Literal for code: DecreasedCaseinDiet
    /// </summary>
    public const string LiteralDecreasedCaseinDiet = "437631000124106";

    /// <summary>
    /// Literal for code: DecreasedGlutenDiet
    /// </summary>
    public const string LiteralDecreasedGlutenDiet = "437641000124101";

    /// <summary>
    /// Literal for code: GlutenFreeDiet
    /// </summary>
    public const string LiteralGlutenFreeDiet = "437651000124104";

    /// <summary>
    /// Literal for code: IncreasedArginineDiet
    /// </summary>
    public const string LiteralIncreasedArginineDiet = "437661000124102";

    /// <summary>
    /// Literal for code: DecreasedArginineDiet
    /// </summary>
    public const string LiteralDecreasedArginineDiet = "437671000124109";

    /// <summary>
    /// Literal for code: IncreasedGlutamineDiet
    /// </summary>
    public const string LiteralIncreasedGlutamineDiet = "437681000124107";

    /// <summary>
    /// Literal for code: DecreasedGlutamineDiet
    /// </summary>
    public const string LiteralDecreasedGlutamineDiet = "437691000124105";

    /// <summary>
    /// Literal for code: IncreasedHistidineDiet
    /// </summary>
    public const string LiteralIncreasedHistidineDiet = "437701000124105";

    /// <summary>
    /// Literal for code: DecreasedHistidineDiet
    /// </summary>
    public const string LiteralDecreasedHistidineDiet = "437711000124108";

    /// <summary>
    /// Literal for code: IncreasedIsoleucineDiet
    /// </summary>
    public const string LiteralIncreasedIsoleucineDiet = "437721000124100";

    /// <summary>
    /// Literal for code: DecreasedIsoleucineDiet
    /// </summary>
    public const string LiteralDecreasedIsoleucineDiet = "437731000124102";

    /// <summary>
    /// Literal for code: IncreasedLeucineDiet
    /// </summary>
    public const string LiteralIncreasedLeucineDiet = "437741000124107";

    /// <summary>
    /// Literal for code: DecreasedLeucineDiet
    /// </summary>
    public const string LiteralDecreasedLeucineDiet = "437751000124109";

    /// <summary>
    /// Literal for code: IncreasedLysineDiet
    /// </summary>
    public const string LiteralIncreasedLysineDiet = "437761000124106";

    /// <summary>
    /// Literal for code: DecreasedLysineDiet
    /// </summary>
    public const string LiteralDecreasedLysineDiet = "437771000124104";

    /// <summary>
    /// Literal for code: IncreasedMethionineDiet
    /// </summary>
    public const string LiteralIncreasedMethionineDiet = "437781000124101";

    /// <summary>
    /// Literal for code: DecreasedMethionineDiet
    /// </summary>
    public const string LiteralDecreasedMethionineDiet = "437791000124103";

    /// <summary>
    /// Literal for code: IncreasedThreonineDiet
    /// </summary>
    public const string LiteralIncreasedThreonineDiet = "437801000124102";

    /// <summary>
    /// Literal for code: DecreasedThreonineDiet
    /// </summary>
    public const string LiteralDecreasedThreonineDiet = "437811000124104";

    /// <summary>
    /// Literal for code: IncreasedTryptophanDiet
    /// </summary>
    public const string LiteralIncreasedTryptophanDiet = "437821000124107";

    /// <summary>
    /// Literal for code: DecreasedTryptophanDiet
    /// </summary>
    public const string LiteralDecreasedTryptophanDiet = "437831000124105";

    /// <summary>
    /// Literal for code: IncreasedTyrosineDiet
    /// </summary>
    public const string LiteralIncreasedTyrosineDiet = "437841000124100";

    /// <summary>
    /// Literal for code: DecreasedTyrosineDiet
    /// </summary>
    public const string LiteralDecreasedTyrosineDiet = "437851000124103";

    /// <summary>
    /// Literal for code: IncreasedValineDiet
    /// </summary>
    public const string LiteralIncreasedValineDiet = "437861000124101";

    /// <summary>
    /// Literal for code: DecreasedValineDiet
    /// </summary>
    public const string LiteralDecreasedValineDiet = "437871000124108";

    /// <summary>
    /// Literal for code: BiotinModifiedDiet
    /// </summary>
    public const string LiteralBiotinModifiedDiet = "438001000124106";

    /// <summary>
    /// Literal for code: FolicAcidModifiedDiet
    /// </summary>
    public const string LiteralFolicAcidModifiedDiet = "438011000124109";

    /// <summary>
    /// Literal for code: NiacinModifiedDiet
    /// </summary>
    public const string LiteralNiacinModifiedDiet = "438021000124101";

    /// <summary>
    /// Literal for code: PantothenicAcidModifiedDiet
    /// </summary>
    public const string LiteralPantothenicAcidModifiedDiet = "438031000124103";

    /// <summary>
    /// Literal for code: RiboflavinModifiedDiet
    /// </summary>
    public const string LiteralRiboflavinModifiedDiet = "438041000124108";

    /// <summary>
    /// Literal for code: ThiamineModifiedDiet
    /// </summary>
    public const string LiteralThiamineModifiedDiet = "438051000124105";

    /// <summary>
    /// Literal for code: VitaminAModifiedDiet
    /// </summary>
    public const string LiteralVitaminAModifiedDiet = "438061000124107";

    /// <summary>
    /// Literal for code: VitaminB6ModifiedDiet
    /// </summary>
    public const string LiteralVitaminB6ModifiedDiet = "438071000124100";

    /// <summary>
    /// Literal for code: VitaminB12ModifiedDiet
    /// </summary>
    public const string LiteralVitaminB12ModifiedDiet = "438081000124102";

    /// <summary>
    /// Literal for code: VitaminCModifiedDiet
    /// </summary>
    public const string LiteralVitaminCModifiedDiet = "438091000124104";

    /// <summary>
    /// Literal for code: VitaminDModifiedDiet
    /// </summary>
    public const string LiteralVitaminDModifiedDiet = "438101000124105";

    /// <summary>
    /// Literal for code: VitaminEModifiedDiet
    /// </summary>
    public const string LiteralVitaminEModifiedDiet = "438111000124108";

    /// <summary>
    /// Literal for code: VitaminKModifiedDiet
    /// </summary>
    public const string LiteralVitaminKModifiedDiet = "438121000124100";

    /// <summary>
    /// Literal for code: IncreasedBiotinDiet
    /// </summary>
    public const string LiteralIncreasedBiotinDiet = "438131000124102";

    /// <summary>
    /// Literal for code: DecreasedBiotinDiet
    /// </summary>
    public const string LiteralDecreasedBiotinDiet = "438141000124107";

    /// <summary>
    /// Literal for code: IncreasedFolicAcidDiet
    /// </summary>
    public const string LiteralIncreasedFolicAcidDiet = "438151000124109";

    /// <summary>
    /// Literal for code: DecreasedFolicAcidDiet
    /// </summary>
    public const string LiteralDecreasedFolicAcidDiet = "438161000124106";

    /// <summary>
    /// Literal for code: IncreasedNiacinDiet
    /// </summary>
    public const string LiteralIncreasedNiacinDiet = "438171000124104";

    /// <summary>
    /// Literal for code: DecreasedNiacinDiet
    /// </summary>
    public const string LiteralDecreasedNiacinDiet = "438181000124101";

    /// <summary>
    /// Literal for code: IncreasedPantothenicAcidDiet
    /// </summary>
    public const string LiteralIncreasedPantothenicAcidDiet = "438191000124103";

    /// <summary>
    /// Literal for code: DecreasedPantothenicAcidDiet
    /// </summary>
    public const string LiteralDecreasedPantothenicAcidDiet = "438201000124100";

    /// <summary>
    /// Literal for code: IncreasedRiboflavinDiet
    /// </summary>
    public const string LiteralIncreasedRiboflavinDiet = "438211000124102";

    /// <summary>
    /// Literal for code: DecreasedRiboflavinDiet
    /// </summary>
    public const string LiteralDecreasedRiboflavinDiet = "438221000124105";

    /// <summary>
    /// Literal for code: IncreasedThiamineDiet
    /// </summary>
    public const string LiteralIncreasedThiamineDiet = "438231000124108";

    /// <summary>
    /// Literal for code: DecreasedThiamineDiet
    /// </summary>
    public const string LiteralDecreasedThiamineDiet = "438241000124103";

    /// <summary>
    /// Literal for code: IncreasedVitaminADiet
    /// </summary>
    public const string LiteralIncreasedVitaminADiet = "438251000124101";

    /// <summary>
    /// Literal for code: DecreasedVitaminADiet
    /// </summary>
    public const string LiteralDecreasedVitaminADiet = "438261000124104";

    /// <summary>
    /// Literal for code: IncreasedVitaminB12Diet
    /// </summary>
    public const string LiteralIncreasedVitaminB12Diet = "438271000124106";

    /// <summary>
    /// Literal for code: DecreasedVitaminB12Diet
    /// </summary>
    public const string LiteralDecreasedVitaminB12Diet = "438281000124109";

    /// <summary>
    /// Literal for code: IncreasedVitaminB6Diet
    /// </summary>
    public const string LiteralIncreasedVitaminB6Diet = "438291000124107";

    /// <summary>
    /// Literal for code: DecreasedVitaminB6Diet
    /// </summary>
    public const string LiteralDecreasedVitaminB6Diet = "438301000124108";

    /// <summary>
    /// Literal for code: IncreasedVitaminCDiet
    /// </summary>
    public const string LiteralIncreasedVitaminCDiet = "438311000124106";

    /// <summary>
    /// Literal for code: DecreasedVitaminCDiet
    /// </summary>
    public const string LiteralDecreasedVitaminCDiet = "438321000124103";

    /// <summary>
    /// Literal for code: IncreasedVitaminDDiet
    /// </summary>
    public const string LiteralIncreasedVitaminDDiet = "438331000124100";

    /// <summary>
    /// Literal for code: DecreasedVitaminDDiet
    /// </summary>
    public const string LiteralDecreasedVitaminDDiet = "438341000124105";

    /// <summary>
    /// Literal for code: IncreasedVitaminEDiet
    /// </summary>
    public const string LiteralIncreasedVitaminEDiet = "438351000124107";

    /// <summary>
    /// Literal for code: DecreasedVitaminEDiet
    /// </summary>
    public const string LiteralDecreasedVitaminEDiet = "438361000124109";

    /// <summary>
    /// Literal for code: IncreasedVitaminKDiet
    /// </summary>
    public const string LiteralIncreasedVitaminKDiet = "438371000124102";

    /// <summary>
    /// Literal for code: DecreasedVitaminKDiet
    /// </summary>
    public const string LiteralDecreasedVitaminKDiet = "438381000124104";

    /// <summary>
    /// Literal for code: DietaryLiquidConsistencyNectarThickLiquid
    /// </summary>
    public const string LiteralDietaryLiquidConsistencyNectarThickLiquid = "439021000124105";

    /// <summary>
    /// Literal for code: DietaryLiquidConsistencyHoneyThickLiquid
    /// </summary>
    public const string LiteralDietaryLiquidConsistencyHoneyThickLiquid = "439031000124108";

    /// <summary>
    /// Literal for code: DietaryLiquidConsistencySpoonThickLiquid
    /// </summary>
    public const string LiteralDietaryLiquidConsistencySpoonThickLiquid = "439041000124103";

    /// <summary>
    /// Literal for code: FluidRestrictedDiet
    /// </summary>
    public const string LiteralFluidRestrictedDiet = "439061000124104";

    /// <summary>
    /// Literal for code: IncreasedFluidDiet
    /// </summary>
    public const string LiteralIncreasedFluidDiet = "439071000124106";

    /// <summary>
    /// Literal for code: DietaryLiquidConsistencyThinLiquid
    /// </summary>
    public const string LiteralDietaryLiquidConsistencyThinLiquid = "439081000124109";

    /// <summary>
    /// Literal for code: EasyToChewDiet
    /// </summary>
    public const string LiteralEasyToChewDiet = "439101000124101";

    /// <summary>
    /// Literal for code: MechanicallyAlteredDiet
    /// </summary>
    public const string LiteralMechanicallyAlteredDiet = "439111000124103";

    /// <summary>
    /// Literal for code: PureedDiet
    /// </summary>
    public const string LiteralPureedDiet = "439121000124106";

    /// <summary>
    /// Literal for code: ModificationOfNutritionalRegime
    /// </summary>
    public const string LiteralModificationOfNutritionalRegime = "445341000124100";

    /// <summary>
    /// Literal for code: ModificationOfScheduleOfOralIntake
    /// </summary>
    public const string LiteralModificationOfScheduleOfOralIntake = "445351000124103";

    /// <summary>
    /// Literal for code: TubeFeedingByBarronPump
    /// </summary>
    public const string LiteralTubeFeedingByBarronPump = "50712000";

    /// <summary>
    /// Literal for code: TubeFeedingByDripMethod
    /// </summary>
    public const string LiteralTubeFeedingByDripMethod = "56948003";

    /// <summary>
    /// Literal for code: TubeFeedingOfPatient
    /// </summary>
    public const string LiteralTubeFeedingOfPatient = "61420007";

    /// <summary>
    /// Literal for code: ModifiedFluidDiet
    /// </summary>
    public const string LiteralModifiedFluidDiet = "762104002";

    /// <summary>
    /// Literal for code: VegetarianDiet
    /// </summary>
    public const string LiteralVegetarianDiet = "765021002";

    /// <summary>
    /// Literal for code: LactoVegetarianDiet
    /// </summary>
    public const string LiteralLactoVegetarianDiet = "765022009";

    /// <summary>
    /// Literal for code: LactoOvoVegetarianDiet
    /// </summary>
    public const string LiteralLactoOvoVegetarianDiet = "765023004";

    /// <summary>
    /// Literal for code: AtkinsDiet
    /// </summary>
    public const string LiteralAtkinsDiet = "765024005";

    /// <summary>
    /// Literal for code: KosherDiet
    /// </summary>
    public const string LiteralKosherDiet = "765025006";

    /// <summary>
    /// Literal for code: HinduDiet
    /// </summary>
    public const string LiteralHinduDiet = "765052001";

    /// <summary>
    /// Literal for code: LowFructoseDiet
    /// </summary>
    public const string LiteralLowFructoseDiet = "765053006";

    /// <summary>
    /// Literal for code: KetogenicDiet
    /// </summary>
    public const string LiteralKetogenicDiet = "765060000";

    /// <summary>
    /// Literal for code: CantoneseDiet
    /// </summary>
    public const string LiteralCantoneseDiet = "765063003";

    /// <summary>
    /// Literal for code: Fasting
    /// </summary>
    public const string LiteralFasting = "792805006";
  };
}
