// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// This is an example value set that includes all the LOINC codes for serum/plasma cholesterol from v2.36.
  /// </summary>
  public static class ExampleExtensionalCodes
  {
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CholesterolMolesVolume = new Coding
    {
      Code = "14647-2",
      Display = "Cholesterol [Moles/Volume]",
      System = "http://loinc.org"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CholesterolMassVolume = new Coding
    {
      Code = "2093-3",
      Display = "Cholesterol [Mass/Volume]",
      System = "http://loinc.org"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CholesterolMassOrMolesVolume = new Coding
    {
      Code = "35200-5",
      Display = "Cholesterol [Mass Or Moles/Volume]",
      System = "http://loinc.org"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CholesterolPercentile = new Coding
    {
      Code = "9342-7",
      Display = "Cholesterol [Percentile]",
      System = "http://loinc.org"
    };

    /// <summary>
    /// Literal for code: CholesterolMolesVolume
    /// </summary>
    public const string LiteralCholesterolMolesVolume = "14647-2";

    /// <summary>
    /// Literal for code: CholesterolMassVolume
    /// </summary>
    public const string LiteralCholesterolMassVolume = "2093-3";

    /// <summary>
    /// Literal for code: CholesterolMassOrMolesVolume
    /// </summary>
    public const string LiteralCholesterolMassOrMolesVolume = "35200-5";

    /// <summary>
    /// Literal for code: CholesterolPercentile
    /// </summary>
    public const string LiteralCholesterolPercentile = "9342-7";
  };
}
