// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// Materials used or needed to feed the patient.
  /// </summary>
  public static class FeedingDeviceCodes
  {
    /// <summary>
    /// Angled utensils definition:
    /// </summary>
    public static readonly Coding AngledUtensils_feeding_device = new Coding
    {
      Code = "angled-utensil",
      Display = "Angled utensils",
      System = "http://hl7.org/fhir/feeding-device"
    };
    /// <summary>
    /// Automated feeding devices definition:
    /// </summary>
    public static readonly Coding AutomatedFeedingDevices_feeding_device = new Coding
    {
      Code = "autofeeding-device",
      Display = "Automated feeding devices",
      System = "http://hl7.org/fhir/feeding-device"
    };
    /// <summary>
    /// Enlarged, cross-cut nipple definition:
    /// </summary>
    public static readonly Coding EnlargedCrossCutNipple_feeding_device = new Coding
    {
      Code = "bigcut-nipple",
      Display = "Enlarged, cross-cut nipple",
      System = "http://hl7.org/fhir/feeding-device"
    };
    /// <summary>
    /// Foam handle utensils definition:
    /// </summary>
    public static readonly Coding FoamHandleUtensils_feeding_device = new Coding
    {
      Code = "foam-handle",
      Display = "Foam handle utensils",
      System = "http://hl7.org/fhir/feeding-device"
    };
    /// <summary>
    /// Glass with lid/sippy cup definition:
    /// </summary>
    public static readonly Coding GlassWithLidSippyCup_feeding_device = new Coding
    {
      Code = "glass-lid",
      Display = "Glass with lid/sippy cup",
      System = "http://hl7.org/fhir/feeding-device"
    };
    /// <summary>
    /// Haberman bottle definition:
    /// </summary>
    public static readonly Coding HabermanBottle_feeding_device = new Coding
    {
      Code = "haberman-bottle",
      Display = "Haberman bottle",
      System = "http://hl7.org/fhir/feeding-device"
    };
    /// <summary>
    /// Double handhold on glass/cup definition:
    /// </summary>
    public static readonly Coding DoubleHandholdOnGlassCup_feeding_device = new Coding
    {
      Code = "handhold-cup",
      Display = "Double handhold on glass/cup",
      System = "http://hl7.org/fhir/feeding-device"
    };
    /// <summary>
    /// Middle flow nipple definition:
    /// </summary>
    public static readonly Coding MiddleFlowNipple_feeding_device = new Coding
    {
      Code = "midflo-nipple",
      Display = "Middle flow nipple",
      System = "http://hl7.org/fhir/feeding-device"
    };
    /// <summary>
    /// Nose cup definition:
    /// </summary>
    public static readonly Coding NoseCup_feeding_device = new Coding
    {
      Code = "nose-cup",
      Display = "Nose cup",
      System = "http://hl7.org/fhir/feeding-device"
    };
    /// <summary>
    /// Orthodontic nipple definition:
    /// </summary>
    public static readonly Coding OrthodonticNipple_feeding_device = new Coding
    {
      Code = "ortho-nipple",
      Display = "Orthodontic nipple",
      System = "http://hl7.org/fhir/feeding-device"
    };
    /// <summary>
    /// Preemie nipple definition:
    /// </summary>
    public static readonly Coding PreemieNipple_feeding_device = new Coding
    {
      Code = "preemie-nipple",
      Display = "Preemie nipple",
      System = "http://hl7.org/fhir/feeding-device"
    };
    /// <summary>
    /// Provale Cup definition:
    /// </summary>
    public static readonly Coding ProvaleCup_feeding_device = new Coding
    {
      Code = "provale-cup",
      Display = "Provale Cup",
      System = "http://hl7.org/fhir/feeding-device"
    };
    /// <summary>
    /// Rocker knife definition:
    /// </summary>
    public static readonly Coding RockerKnife_feeding_device = new Coding
    {
      Code = "rocker-knife",
      Display = "Rocker knife",
      System = "http://hl7.org/fhir/feeding-device"
    };
    /// <summary>
    /// Rubber matting under tray definition:
    /// </summary>
    public static readonly Coding RubberMattingUnderTray_feeding_device = new Coding
    {
      Code = "rubber-mat",
      Display = "Rubber matting under tray",
      System = "http://hl7.org/fhir/feeding-device"
    };
    /// <summary>
    /// Scoop plate definition:
    /// </summary>
    public static readonly Coding ScoopPlate_feeding_device = new Coding
    {
      Code = "scoop-plate",
      Display = "Scoop plate",
      System = "http://hl7.org/fhir/feeding-device"
    };
    /// <summary>
    /// Sippy cup without valve definition:
    /// </summary>
    public static readonly Coding SippyCupWithoutValve_feeding_device = new Coding
    {
      Code = "sippy-no-valve",
      Display = "Sippy cup without valve",
      System = "http://hl7.org/fhir/feeding-device"
    };
    /// <summary>
    /// Sippy cup with valve definition:
    /// </summary>
    public static readonly Coding SippyCupWithValve_feeding_device = new Coding
    {
      Code = "sippy-valve",
      Display = "Sippy cup with valve",
      System = "http://hl7.org/fhir/feeding-device"
    };
    /// <summary>
    /// Slow flow nipple definition:
    /// </summary>
    public static readonly Coding SlowFlowNipple_feeding_device = new Coding
    {
      Code = "sloflo-nipple",
      Display = "Slow flow nipple",
      System = "http://hl7.org/fhir/feeding-device"
    };
    /// <summary>
    /// Spout cup definition:
    /// </summary>
    public static readonly Coding SpoutCup_feeding_device = new Coding
    {
      Code = "spout-cup",
      Display = "Spout cup",
      System = "http://hl7.org/fhir/feeding-device"
    };
    /// <summary>
    /// Standard nipple definition:
    /// </summary>
    public static readonly Coding StandardNipple_feeding_device = new Coding
    {
      Code = "standard-nipple",
      Display = "Standard nipple",
      System = "http://hl7.org/fhir/feeding-device"
    };
    /// <summary>
    /// Straw definition:
    /// </summary>
    public static readonly Coding Straw_feeding_device = new Coding
    {
      Code = "straw",
      Display = "Straw",
      System = "http://hl7.org/fhir/feeding-device"
    };
    /// <summary>
    /// Hand wrap utensil holder definition:
    /// </summary>
    public static readonly Coding HandWrapUtensilHolder_feeding_device = new Coding
    {
      Code = "utensil-holder",
      Display = "Hand wrap utensil holder",
      System = "http://hl7.org/fhir/feeding-device"
    };

    /// <summary>
    /// Literal for code: AngledUtensils_feeding_device
    /// </summary>
    public const string LiteralAngledUtensils_feeding_device = "angled-utensil";

    /// <summary>
    /// Literal for code: AutomatedFeedingDevices_feeding_device
    /// </summary>
    public const string LiteralAutomatedFeedingDevices_feeding_device = "autofeeding-device";

    /// <summary>
    /// Literal for code: EnlargedCrossCutNipple_feeding_device
    /// </summary>
    public const string LiteralEnlargedCrossCutNipple_feeding_device = "bigcut-nipple";

    /// <summary>
    /// Literal for code: FoamHandleUtensils_feeding_device
    /// </summary>
    public const string LiteralFoamHandleUtensils_feeding_device = "foam-handle";

    /// <summary>
    /// Literal for code: GlassWithLidSippyCup_feeding_device
    /// </summary>
    public const string LiteralGlassWithLidSippyCup_feeding_device = "glass-lid";

    /// <summary>
    /// Literal for code: HabermanBottle_feeding_device
    /// </summary>
    public const string LiteralHabermanBottle_feeding_device = "haberman-bottle";

    /// <summary>
    /// Literal for code: DoubleHandholdOnGlassCup_feeding_device
    /// </summary>
    public const string LiteralDoubleHandholdOnGlassCup_feeding_device = "handhold-cup";

    /// <summary>
    /// Literal for code: MiddleFlowNipple_feeding_device
    /// </summary>
    public const string LiteralMiddleFlowNipple_feeding_device = "midflo-nipple";

    /// <summary>
    /// Literal for code: NoseCup_feeding_device
    /// </summary>
    public const string LiteralNoseCup_feeding_device = "nose-cup";

    /// <summary>
    /// Literal for code: OrthodonticNipple_feeding_device
    /// </summary>
    public const string LiteralOrthodonticNipple_feeding_device = "ortho-nipple";

    /// <summary>
    /// Literal for code: PreemieNipple_feeding_device
    /// </summary>
    public const string LiteralPreemieNipple_feeding_device = "preemie-nipple";

    /// <summary>
    /// Literal for code: ProvaleCup_feeding_device
    /// </summary>
    public const string LiteralProvaleCup_feeding_device = "provale-cup";

    /// <summary>
    /// Literal for code: RockerKnife_feeding_device
    /// </summary>
    public const string LiteralRockerKnife_feeding_device = "rocker-knife";

    /// <summary>
    /// Literal for code: RubberMattingUnderTray_feeding_device
    /// </summary>
    public const string LiteralRubberMattingUnderTray_feeding_device = "rubber-mat";

    /// <summary>
    /// Literal for code: ScoopPlate_feeding_device
    /// </summary>
    public const string LiteralScoopPlate_feeding_device = "scoop-plate";

    /// <summary>
    /// Literal for code: SippyCupWithoutValve_feeding_device
    /// </summary>
    public const string LiteralSippyCupWithoutValve_feeding_device = "sippy-no-valve";

    /// <summary>
    /// Literal for code: SippyCupWithValve_feeding_device
    /// </summary>
    public const string LiteralSippyCupWithValve_feeding_device = "sippy-valve";

    /// <summary>
    /// Literal for code: SlowFlowNipple_feeding_device
    /// </summary>
    public const string LiteralSlowFlowNipple_feeding_device = "sloflo-nipple";

    /// <summary>
    /// Literal for code: SpoutCup_feeding_device
    /// </summary>
    public const string LiteralSpoutCup_feeding_device = "spout-cup";

    /// <summary>
    /// Literal for code: StandardNipple_feeding_device
    /// </summary>
    public const string LiteralStandardNipple_feeding_device = "standard-nipple";

    /// <summary>
    /// Literal for code: Straw_feeding_device
    /// </summary>
    public const string LiteralStraw_feeding_device = "straw";

    /// <summary>
    /// Literal for code: HandWrapUtensilHolder_feeding_device
    /// </summary>
    public const string LiteralHandWrapUtensilHolder_feeding_device = "utensil-holder";
  };
}
