// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// This value set includes sample ICD-10 codes.
  /// </summary>
  public static class Icd10Codes
  {
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding EndocrineNutritionalAndMetabolicDiseases = new Coding
    {
      Code = "E00-E90",
      Display = "Endocrine, nutritional and metabolic diseases",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MetabolicDisorders = new Coding
    {
      Code = "E70-E90",
      Display = "Metabolic disorders",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CysticFibrosis = new Coding
    {
      Code = "E84",
      Display = "Cystic fibrosis",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CysticFibrosisWithPulmonaryManifestations = new Coding
    {
      Code = "E84.0",
      Display = "Cystic fibrosis with pulmonary manifestations",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DiseasesOfTheCirculatorySystem = new Coding
    {
      Code = "I00-I99",
      Display = "Diseases of the circulatory system",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding OtherFormsOfHeartDisease = new Coding
    {
      Code = "I30-I52",
      Display = "Other forms of heart disease",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ComplicationsAndIllDefinedDescriptionsOfHeartDisease = new Coding
    {
      Code = "I51",
      Display = "Complications and ill-defined descriptions of heart disease",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CardiacSeptalDefectAcquired = new Coding
    {
      Code = "I51.0",
      Display = "Cardiac septal defect, acquired",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding RuptureOfChordaeTendineaeNotElsewhereClassified = new Coding
    {
      Code = "I51.1",
      Display = "Rupture of chordae tendineae, not elsewhere classified",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding RuptureOfPapillaryMuscleNotElsewhereClassified = new Coding
    {
      Code = "I51.2",
      Display = "Rupture of papillary muscle, not elsewhere classified",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding IntracardiacThrombosisNotElsewhereClassified = new Coding
    {
      Code = "I51.3",
      Display = "Intracardiac thrombosis, not elsewhere classified",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MyocarditisUnspecified = new Coding
    {
      Code = "I51.4",
      Display = "Myocarditis, unspecified",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MyocardialDegeneration = new Coding
    {
      Code = "I51.5",
      Display = "Myocardial degeneration",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CardiovascularDiseaseUnspecified = new Coding
    {
      Code = "I51.6",
      Display = "Cardiovascular disease, unspecified",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Cardiomegaly = new Coding
    {
      Code = "I51.7",
      Display = "Cardiomegaly",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding OtherIllDefinedHeartDiseases = new Coding
    {
      Code = "I51.8",
      Display = "Other ill-defined heart diseases",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding HeartDiseaseUnspecified = new Coding
    {
      Code = "I51.9",
      Display = "Heart disease, unspecified",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DiseasesOfOralCavitySalivaryGlandsAndJaws = new Coding
    {
      Code = "K00-K14",
      Display = "Diseases of oral cavity, salivary glands and jaws",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DiseasesOfTheDigestiveSystem = new Coding
    {
      Code = "K00-K93",
      Display = "Diseases of the digestive system",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DentofacialAnomaliesIncludingMalocclusion = new Coding
    {
      Code = "K07",
      Display = "Dentofacial anomalies [including malocclusion]",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MajorAnomaliesOfJawSize = new Coding
    {
      Code = "K07.0",
      Display = "Major anomalies of jaw size",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding AnomaliesOfJawCranialBaseRelationship = new Coding
    {
      Code = "K07.1",
      Display = "Anomalies of jaw-cranial base relationship",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding AnomaliesOfDentalArchRelationship = new Coding
    {
      Code = "K07.2",
      Display = "Anomalies of dental arch relationship",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding AnomaliesOfToothPosition = new Coding
    {
      Code = "K07.3",
      Display = "Anomalies of tooth position",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MalocclusionUnspecified = new Coding
    {
      Code = "K07.4",
      Display = "Malocclusion, unspecified",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DentofacialFunctionalAbnormalities = new Coding
    {
      Code = "K07.5",
      Display = "Dentofacial functional abnormalities",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TemporomandibularJointDisorders = new Coding
    {
      Code = "K07.6",
      Display = "Temporomandibular joint disorders",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding OtherDentofacialAnomalies = new Coding
    {
      Code = "K07.8",
      Display = "Other dentofacial anomalies",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DentofacialAnomalyUnspecified = new Coding
    {
      Code = "K07.9",
      Display = "Dentofacial anomaly, unspecified",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DiseasesOfTheMusculoskeletalSystemAndConnectiveTissue = new Coding
    {
      Code = "M00-M99",
      Display = "Diseases of the musculoskeletal system and connective tissue",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Dorsopathies = new Coding
    {
      Code = "M40-M54",
      Display = "Dorsopathies",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Spondylopathies = new Coding
    {
      Code = "M45-M49",
      Display = "Spondylopathies",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Spondylosis = new Coding
    {
      Code = "M47",
      Display = "Spondylosis",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding AnteriorSpinalAndVertebralArteryCompressionSyndromes = new Coding
    {
      Code = "M47.0†",
      Display = "Anterior spinal and vertebral artery compression syndromes",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding OtherSpondylosisWithMyelopathy = new Coding
    {
      Code = "M47.1",
      Display = "Other spondylosis with myelopathy",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding OtherSpondylosisWithRadiculopathy = new Coding
    {
      Code = "M47.2",
      Display = "Other spondylosis with radiculopathy",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding OtherSpondylosis = new Coding
    {
      Code = "M47.8",
      Display = "Other spondylosis",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding SpondylosisUnspecified = new Coding
    {
      Code = "M47.9",
      Display = "Spondylosis, unspecified",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding OtherDorsopathies = new Coding
    {
      Code = "M50-54",
      Display = "Other dorsopathies",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding OtherDorsopathiesNotElsewhereClassified = new Coding
    {
      Code = "M53",
      Display = "Other dorsopathies, not elsewhere classified",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CervicocranialSyndrome = new Coding
    {
      Code = "M53.0",
      Display = "Cervicocranial syndrome",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CervicobrachialSyndrome = new Coding
    {
      Code = "M53.1",
      Display = "Cervicobrachial syndrome",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding SpinalInstabilities = new Coding
    {
      Code = "M53.2",
      Display = "Spinal instabilities",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding SacrococcygealDisordersNotElsewhereClassified = new Coding
    {
      Code = "M53.3",
      Display = "Sacrococcygeal disorders, not elsewhere classified",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding OtherSpecifiedDorsopathies = new Coding
    {
      Code = "M53.8",
      Display = "Other specified dorsopathies",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DorsopathyUnspecified = new Coding
    {
      Code = "M53.9",
      Display = "Dorsopathy, unspecified",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding OtherDisordersOfTheMusculoskeletalSystemAndConnectiveTissue = new Coding
    {
      Code = "M95-M99",
      Display = "Other disorders of the musculoskeletal system and connective tissue",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PostproceduralMusculoskeletalDisordersNotElsewhereClassified = new Coding
    {
      Code = "M96",
      Display = "Postprocedural musculoskeletal disorders, not elsewhere classified",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PseudarthrosisAfterFusionOrArthrodesis = new Coding
    {
      Code = "M96.0",
      Display = "Pseudarthrosis after fusion or arthrodesis",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PostlaminectomySyndromeNotElsewhereClassified = new Coding
    {
      Code = "M96.1",
      Display = "Postlaminectomy syndrome, not elsewhere classified",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PostradiationKyphosis = new Coding
    {
      Code = "M96.2",
      Display = "Postradiation kyphosis",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PostlaminectomyKyphosis = new Coding
    {
      Code = "M96.3",
      Display = "Postlaminectomy kyphosis",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PostsurgicalLordosis = new Coding
    {
      Code = "M96.4",
      Display = "Postsurgical lordosis",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PostradiationScoliosis = new Coding
    {
      Code = "M96.5",
      Display = "Postradiation scoliosis",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding FractureOfBoneFollowingInsertionOfOrthopaedicImplantJointProsthesisOrBonePlate = new Coding
    {
      Code = "M96.6",
      Display = "Fracture of bone following insertion of orthopaedic implant, joint prosthesis, or bone plate",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding OtherPostproceduralMusculoskeletalDisorders = new Coding
    {
      Code = "M96.8",
      Display = "Other postprocedural musculoskeletal disorders",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PostproceduralMusculoskeletalDisorderUnspecified = new Coding
    {
      Code = "M96.9",
      Display = "Postprocedural musculoskeletal disorder, unspecified",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DiseasesOfTheGenitourinarySystem = new Coding
    {
      Code = "N00-N99",
      Display = "Diseases of the genitourinary system",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding NoninflammatoryDisordersOfFemaleGenitalTract = new Coding
    {
      Code = "N80-N98",
      Display = "Noninflammatory disorders of female genital tract",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MenopausalAndOtherPerimenopausalDisorders = new Coding
    {
      Code = "N95",
      Display = "Menopausal and other perimenopausal disorders",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PostmenopausalBleeding = new Coding
    {
      Code = "N95.0",
      Display = "Postmenopausal bleeding",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MenopausalAndFemaleClimactericStates = new Coding
    {
      Code = "N95.1",
      Display = "Menopausal and female climacteric states",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PostmenopausalAtrophicVaginitis = new Coding
    {
      Code = "N95.2",
      Display = "Postmenopausal atrophic vaginitis",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding StatesAssociatedWithArtificialMenopause = new Coding
    {
      Code = "N95.3",
      Display = "States associated with artificial menopause",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding OtherSpecifiedMenopausalAndPerimenopausalDisorders = new Coding
    {
      Code = "N95.8",
      Display = "Other specified menopausal and perimenopausal disorders",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MenopausalAndPerimenopausalDisorderUnspecified = new Coding
    {
      Code = "N95.9",
      Display = "Menopausal and perimenopausal disorder, unspecified",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding SymptomsSignsAndAbnormalClinicalAndLaboratoryFindingsNotElsewhereClassified = new Coding
    {
      Code = "R00-R99",
      Display = "Symptoms, signs and abnormal clinical and laboratory findings, not elsewhere classified",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding GeneralSymptomsAndSigns = new Coding
    {
      Code = "R50-R69",
      Display = "General symptoms and signs",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PainNotElsewhereClassified = new Coding
    {
      Code = "R52",
      Display = "Pain, not elsewhere classified",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding AcutePain = new Coding
    {
      Code = "R52.0",
      Display = "Acute pain",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ChronicIntractablePain = new Coding
    {
      Code = "R52.1",
      Display = "Chronic intractable pain",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding OtherChronicPain = new Coding
    {
      Code = "R52.2",
      Display = "Other chronic pain",
      System = "http://hl7.org/fhir/sid/icd-10"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PainUnspecified = new Coding
    {
      Code = "R52.9",
      Display = "Pain, unspecified",
      System = "http://hl7.org/fhir/sid/icd-10"
    };

    /// <summary>
    /// Literal for code: EndocrineNutritionalAndMetabolicDiseases
    /// </summary>
    public const string LiteralEndocrineNutritionalAndMetabolicDiseases = "E00-E90";

    /// <summary>
    /// Literal for code: MetabolicDisorders
    /// </summary>
    public const string LiteralMetabolicDisorders = "E70-E90";

    /// <summary>
    /// Literal for code: CysticFibrosis
    /// </summary>
    public const string LiteralCysticFibrosis = "E84";

    /// <summary>
    /// Literal for code: CysticFibrosisWithPulmonaryManifestations
    /// </summary>
    public const string LiteralCysticFibrosisWithPulmonaryManifestations = "E84.0";

    /// <summary>
    /// Literal for code: DiseasesOfTheCirculatorySystem
    /// </summary>
    public const string LiteralDiseasesOfTheCirculatorySystem = "I00-I99";

    /// <summary>
    /// Literal for code: OtherFormsOfHeartDisease
    /// </summary>
    public const string LiteralOtherFormsOfHeartDisease = "I30-I52";

    /// <summary>
    /// Literal for code: ComplicationsAndIllDefinedDescriptionsOfHeartDisease
    /// </summary>
    public const string LiteralComplicationsAndIllDefinedDescriptionsOfHeartDisease = "I51";

    /// <summary>
    /// Literal for code: CardiacSeptalDefectAcquired
    /// </summary>
    public const string LiteralCardiacSeptalDefectAcquired = "I51.0";

    /// <summary>
    /// Literal for code: RuptureOfChordaeTendineaeNotElsewhereClassified
    /// </summary>
    public const string LiteralRuptureOfChordaeTendineaeNotElsewhereClassified = "I51.1";

    /// <summary>
    /// Literal for code: RuptureOfPapillaryMuscleNotElsewhereClassified
    /// </summary>
    public const string LiteralRuptureOfPapillaryMuscleNotElsewhereClassified = "I51.2";

    /// <summary>
    /// Literal for code: IntracardiacThrombosisNotElsewhereClassified
    /// </summary>
    public const string LiteralIntracardiacThrombosisNotElsewhereClassified = "I51.3";

    /// <summary>
    /// Literal for code: MyocarditisUnspecified
    /// </summary>
    public const string LiteralMyocarditisUnspecified = "I51.4";

    /// <summary>
    /// Literal for code: MyocardialDegeneration
    /// </summary>
    public const string LiteralMyocardialDegeneration = "I51.5";

    /// <summary>
    /// Literal for code: CardiovascularDiseaseUnspecified
    /// </summary>
    public const string LiteralCardiovascularDiseaseUnspecified = "I51.6";

    /// <summary>
    /// Literal for code: Cardiomegaly
    /// </summary>
    public const string LiteralCardiomegaly = "I51.7";

    /// <summary>
    /// Literal for code: OtherIllDefinedHeartDiseases
    /// </summary>
    public const string LiteralOtherIllDefinedHeartDiseases = "I51.8";

    /// <summary>
    /// Literal for code: HeartDiseaseUnspecified
    /// </summary>
    public const string LiteralHeartDiseaseUnspecified = "I51.9";

    /// <summary>
    /// Literal for code: DiseasesOfOralCavitySalivaryGlandsAndJaws
    /// </summary>
    public const string LiteralDiseasesOfOralCavitySalivaryGlandsAndJaws = "K00-K14";

    /// <summary>
    /// Literal for code: DiseasesOfTheDigestiveSystem
    /// </summary>
    public const string LiteralDiseasesOfTheDigestiveSystem = "K00-K93";

    /// <summary>
    /// Literal for code: DentofacialAnomaliesIncludingMalocclusion
    /// </summary>
    public const string LiteralDentofacialAnomaliesIncludingMalocclusion = "K07";

    /// <summary>
    /// Literal for code: MajorAnomaliesOfJawSize
    /// </summary>
    public const string LiteralMajorAnomaliesOfJawSize = "K07.0";

    /// <summary>
    /// Literal for code: AnomaliesOfJawCranialBaseRelationship
    /// </summary>
    public const string LiteralAnomaliesOfJawCranialBaseRelationship = "K07.1";

    /// <summary>
    /// Literal for code: AnomaliesOfDentalArchRelationship
    /// </summary>
    public const string LiteralAnomaliesOfDentalArchRelationship = "K07.2";

    /// <summary>
    /// Literal for code: AnomaliesOfToothPosition
    /// </summary>
    public const string LiteralAnomaliesOfToothPosition = "K07.3";

    /// <summary>
    /// Literal for code: MalocclusionUnspecified
    /// </summary>
    public const string LiteralMalocclusionUnspecified = "K07.4";

    /// <summary>
    /// Literal for code: DentofacialFunctionalAbnormalities
    /// </summary>
    public const string LiteralDentofacialFunctionalAbnormalities = "K07.5";

    /// <summary>
    /// Literal for code: TemporomandibularJointDisorders
    /// </summary>
    public const string LiteralTemporomandibularJointDisorders = "K07.6";

    /// <summary>
    /// Literal for code: OtherDentofacialAnomalies
    /// </summary>
    public const string LiteralOtherDentofacialAnomalies = "K07.8";

    /// <summary>
    /// Literal for code: DentofacialAnomalyUnspecified
    /// </summary>
    public const string LiteralDentofacialAnomalyUnspecified = "K07.9";

    /// <summary>
    /// Literal for code: DiseasesOfTheMusculoskeletalSystemAndConnectiveTissue
    /// </summary>
    public const string LiteralDiseasesOfTheMusculoskeletalSystemAndConnectiveTissue = "M00-M99";

    /// <summary>
    /// Literal for code: Dorsopathies
    /// </summary>
    public const string LiteralDorsopathies = "M40-M54";

    /// <summary>
    /// Literal for code: Spondylopathies
    /// </summary>
    public const string LiteralSpondylopathies = "M45-M49";

    /// <summary>
    /// Literal for code: Spondylosis
    /// </summary>
    public const string LiteralSpondylosis = "M47";

    /// <summary>
    /// Literal for code: AnteriorSpinalAndVertebralArteryCompressionSyndromes
    /// </summary>
    public const string LiteralAnteriorSpinalAndVertebralArteryCompressionSyndromes = "M47.0†";

    /// <summary>
    /// Literal for code: OtherSpondylosisWithMyelopathy
    /// </summary>
    public const string LiteralOtherSpondylosisWithMyelopathy = "M47.1";

    /// <summary>
    /// Literal for code: OtherSpondylosisWithRadiculopathy
    /// </summary>
    public const string LiteralOtherSpondylosisWithRadiculopathy = "M47.2";

    /// <summary>
    /// Literal for code: OtherSpondylosis
    /// </summary>
    public const string LiteralOtherSpondylosis = "M47.8";

    /// <summary>
    /// Literal for code: SpondylosisUnspecified
    /// </summary>
    public const string LiteralSpondylosisUnspecified = "M47.9";

    /// <summary>
    /// Literal for code: OtherDorsopathies
    /// </summary>
    public const string LiteralOtherDorsopathies = "M50-54";

    /// <summary>
    /// Literal for code: OtherDorsopathiesNotElsewhereClassified
    /// </summary>
    public const string LiteralOtherDorsopathiesNotElsewhereClassified = "M53";

    /// <summary>
    /// Literal for code: CervicocranialSyndrome
    /// </summary>
    public const string LiteralCervicocranialSyndrome = "M53.0";

    /// <summary>
    /// Literal for code: CervicobrachialSyndrome
    /// </summary>
    public const string LiteralCervicobrachialSyndrome = "M53.1";

    /// <summary>
    /// Literal for code: SpinalInstabilities
    /// </summary>
    public const string LiteralSpinalInstabilities = "M53.2";

    /// <summary>
    /// Literal for code: SacrococcygealDisordersNotElsewhereClassified
    /// </summary>
    public const string LiteralSacrococcygealDisordersNotElsewhereClassified = "M53.3";

    /// <summary>
    /// Literal for code: OtherSpecifiedDorsopathies
    /// </summary>
    public const string LiteralOtherSpecifiedDorsopathies = "M53.8";

    /// <summary>
    /// Literal for code: DorsopathyUnspecified
    /// </summary>
    public const string LiteralDorsopathyUnspecified = "M53.9";

    /// <summary>
    /// Literal for code: OtherDisordersOfTheMusculoskeletalSystemAndConnectiveTissue
    /// </summary>
    public const string LiteralOtherDisordersOfTheMusculoskeletalSystemAndConnectiveTissue = "M95-M99";

    /// <summary>
    /// Literal for code: PostproceduralMusculoskeletalDisordersNotElsewhereClassified
    /// </summary>
    public const string LiteralPostproceduralMusculoskeletalDisordersNotElsewhereClassified = "M96";

    /// <summary>
    /// Literal for code: PseudarthrosisAfterFusionOrArthrodesis
    /// </summary>
    public const string LiteralPseudarthrosisAfterFusionOrArthrodesis = "M96.0";

    /// <summary>
    /// Literal for code: PostlaminectomySyndromeNotElsewhereClassified
    /// </summary>
    public const string LiteralPostlaminectomySyndromeNotElsewhereClassified = "M96.1";

    /// <summary>
    /// Literal for code: PostradiationKyphosis
    /// </summary>
    public const string LiteralPostradiationKyphosis = "M96.2";

    /// <summary>
    /// Literal for code: PostlaminectomyKyphosis
    /// </summary>
    public const string LiteralPostlaminectomyKyphosis = "M96.3";

    /// <summary>
    /// Literal for code: PostsurgicalLordosis
    /// </summary>
    public const string LiteralPostsurgicalLordosis = "M96.4";

    /// <summary>
    /// Literal for code: PostradiationScoliosis
    /// </summary>
    public const string LiteralPostradiationScoliosis = "M96.5";

    /// <summary>
    /// Literal for code: FractureOfBoneFollowingInsertionOfOrthopaedicImplantJointProsthesisOrBonePlate
    /// </summary>
    public const string LiteralFractureOfBoneFollowingInsertionOfOrthopaedicImplantJointProsthesisOrBonePlate = "M96.6";

    /// <summary>
    /// Literal for code: OtherPostproceduralMusculoskeletalDisorders
    /// </summary>
    public const string LiteralOtherPostproceduralMusculoskeletalDisorders = "M96.8";

    /// <summary>
    /// Literal for code: PostproceduralMusculoskeletalDisorderUnspecified
    /// </summary>
    public const string LiteralPostproceduralMusculoskeletalDisorderUnspecified = "M96.9";

    /// <summary>
    /// Literal for code: DiseasesOfTheGenitourinarySystem
    /// </summary>
    public const string LiteralDiseasesOfTheGenitourinarySystem = "N00-N99";

    /// <summary>
    /// Literal for code: NoninflammatoryDisordersOfFemaleGenitalTract
    /// </summary>
    public const string LiteralNoninflammatoryDisordersOfFemaleGenitalTract = "N80-N98";

    /// <summary>
    /// Literal for code: MenopausalAndOtherPerimenopausalDisorders
    /// </summary>
    public const string LiteralMenopausalAndOtherPerimenopausalDisorders = "N95";

    /// <summary>
    /// Literal for code: PostmenopausalBleeding
    /// </summary>
    public const string LiteralPostmenopausalBleeding = "N95.0";

    /// <summary>
    /// Literal for code: MenopausalAndFemaleClimactericStates
    /// </summary>
    public const string LiteralMenopausalAndFemaleClimactericStates = "N95.1";

    /// <summary>
    /// Literal for code: PostmenopausalAtrophicVaginitis
    /// </summary>
    public const string LiteralPostmenopausalAtrophicVaginitis = "N95.2";

    /// <summary>
    /// Literal for code: StatesAssociatedWithArtificialMenopause
    /// </summary>
    public const string LiteralStatesAssociatedWithArtificialMenopause = "N95.3";

    /// <summary>
    /// Literal for code: OtherSpecifiedMenopausalAndPerimenopausalDisorders
    /// </summary>
    public const string LiteralOtherSpecifiedMenopausalAndPerimenopausalDisorders = "N95.8";

    /// <summary>
    /// Literal for code: MenopausalAndPerimenopausalDisorderUnspecified
    /// </summary>
    public const string LiteralMenopausalAndPerimenopausalDisorderUnspecified = "N95.9";

    /// <summary>
    /// Literal for code: SymptomsSignsAndAbnormalClinicalAndLaboratoryFindingsNotElsewhereClassified
    /// </summary>
    public const string LiteralSymptomsSignsAndAbnormalClinicalAndLaboratoryFindingsNotElsewhereClassified = "R00-R99";

    /// <summary>
    /// Literal for code: GeneralSymptomsAndSigns
    /// </summary>
    public const string LiteralGeneralSymptomsAndSigns = "R50-R69";

    /// <summary>
    /// Literal for code: PainNotElsewhereClassified
    /// </summary>
    public const string LiteralPainNotElsewhereClassified = "R52";

    /// <summary>
    /// Literal for code: AcutePain
    /// </summary>
    public const string LiteralAcutePain = "R52.0";

    /// <summary>
    /// Literal for code: ChronicIntractablePain
    /// </summary>
    public const string LiteralChronicIntractablePain = "R52.1";

    /// <summary>
    /// Literal for code: OtherChronicPain
    /// </summary>
    public const string LiteralOtherChronicPain = "R52.2";

    /// <summary>
    /// Literal for code: PainUnspecified
    /// </summary>
    public const string LiteralPainUnspecified = "R52.9";
  };
}
