// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// LDL Cholesterol codes - measured or calculated
  /// </summary>
  public static class LipidLdlCodesCodes
  {
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CholesterolInLDLMassVolumeInSerumOrPlasmaByCalculation = new Coding
    {
      Code = "13457-7",
      Display = "Cholesterol in LDL [Mass/volume] in Serum or Plasma by calculation",
      System = "http://loinc.org"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding LDLCholesterolAssay = new Coding
    {
      Code = "18262-6",
      Display = "LDL Cholesterol (Assay)",
      System = "http://loinc.org"
    };

    /// <summary>
    /// Literal for code: CholesterolInLDLMassVolumeInSerumOrPlasmaByCalculation
    /// </summary>
    public const string LiteralCholesterolInLDLMassVolumeInSerumOrPlasmaByCalculation = "13457-7";

    /// <summary>
    /// Literal for code: LDLCholesterolAssay
    /// </summary>
    public const string LiteralLDLCholesterolAssay = "18262-6";
  };
}
