// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// Used for status.
  /// </summary>
  public static class MedlineCitationStatusCodes
  {
    /// <summary>
    /// MedlineCitation record  completed (see https://www.nlm.nih.gov/bsd/licensee/elements_descriptions.html#status_value).
    /// </summary>
    public static readonly Coding Completed = new Coding
    {
      Code = "Completed",
      Display = "Completed",
      System = "http://hl7.org/fhir/medline-citation-status"
    };
    /// <summary>
    /// MedlineCitation record reviewed at journal issue level (see https://www.nlm.nih.gov/bsd/licensee/elements_descriptions.html#status_value).
    /// </summary>
    public static readonly Coding InDataReview = new Coding
    {
      Code = "In-Data-Review",
      Display = "In-Data-Review",
      System = "http://hl7.org/fhir/medline-citation-status"
    };
    /// <summary>
    /// MedlineCitation record reviewed at citation level (see https://www.nlm.nih.gov/bsd/licensee/elements_descriptions.html#status_value).
    /// </summary>
    public static readonly Coding InProcess = new Coding
    {
      Code = "In-Process",
      Display = "In-Process",
      System = "http://hl7.org/fhir/medline-citation-status"
    };
    /// <summary>
    /// MedlineCitation record that is a true MEDLINE record (see https://www.nlm.nih.gov/bsd/licensee/elements_descriptions.html#status_value).
    /// </summary>
    public static readonly Coding MEDLINE = new Coding
    {
      Code = "MEDLINE",
      Display = "MEDLINE",
      System = "http://hl7.org/fhir/medline-citation-status"
    };
    /// <summary>
    /// MedlineCitation record that is indexed with original (older) MeSH Headings (see https://www.nlm.nih.gov/bsd/licensee/elements_descriptions.html#status_value).
    /// </summary>
    public static readonly Coding OLDMEDLINE = new Coding
    {
      Code = "OLDMEDLINE",
      Display = "OLDMEDLINE",
      System = "http://hl7.org/fhir/medline-citation-status"
    };
    /// <summary>
    /// MedlineCitation record not indexed for MEDLINE (see https://www.nlm.nih.gov/bsd/licensee/elements_descriptions.html#status_value).
    /// </summary>
    public static readonly Coding Publisher = new Coding
    {
      Code = "Publisher",
      Display = "Publisher",
      System = "http://hl7.org/fhir/medline-citation-status"
    };
    /// <summary>
    /// MedlineCitation record that is indexed without MeSH Headings (see https://www.nlm.nih.gov/bsd/licensee/elements_descriptions.html#status_value).
    /// </summary>
    public static readonly Coding PubMedNotMEDLINE = new Coding
    {
      Code = "PubMed-not-MEDLINE",
      Display = "PubMed-not-MEDLINE",
      System = "http://hl7.org/fhir/medline-citation-status"
    };

    /// <summary>
    /// Literal for code: Completed
    /// </summary>
    public const string LiteralCompleted = "Completed";

    /// <summary>
    /// Literal for code: InDataReview
    /// </summary>
    public const string LiteralInDataReview = "In-Data-Review";

    /// <summary>
    /// Literal for code: InProcess
    /// </summary>
    public const string LiteralInProcess = "In-Process";

    /// <summary>
    /// Literal for code: MEDLINE
    /// </summary>
    public const string LiteralMEDLINE = "MEDLINE";

    /// <summary>
    /// Literal for code: OLDMEDLINE
    /// </summary>
    public const string LiteralOLDMEDLINE = "OLDMEDLINE";

    /// <summary>
    /// Literal for code: Publisher
    /// </summary>
    public const string LiteralPublisher = "Publisher";

    /// <summary>
    /// Literal for code: PubMedNotMEDLINE
    /// </summary>
    public const string LiteralPubMedNotMEDLINE = "PubMed-not-MEDLINE";
  };
}
