// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// Used for owner.
  /// </summary>
  public static class MedlineCitationOwnerCodes
  {
    /// <summary>
    /// History of Medicine Division, National Library of Medicine.
    /// </summary>
    public static readonly Coding HMD = new Coding
    {
      Code = "HMD",
      Display = "HMD",
      System = "http://hl7.org/fhir/medline-citation-owner"
    };
    /// <summary>
    /// National Information Center on Health Services Research and Health Care Technology, National Library of Medicine.
    /// </summary>
    public static readonly Coding HSR = new Coding
    {
      Code = "HSR",
      Display = "HSR",
      System = "http://hl7.org/fhir/medline-citation-owner"
    };
    /// <summary>
    /// Kennedy Institute of Ethics, Georgetown University.
    /// </summary>
    public static readonly Coding KIE = new Coding
    {
      Code = "KIE",
      Display = "KIE",
      System = "http://hl7.org/fhir/medline-citation-owner"
    };
    /// <summary>
    /// National Aeronautics and Space Administration.
    /// </summary>
    public static readonly Coding NASA = new Coding
    {
      Code = "NASA",
      Display = "NASA",
      System = "http://hl7.org/fhir/medline-citation-owner"
    };
    /// <summary>
    /// National Library of Medicine, Index Section.
    /// </summary>
    public static readonly Coding NLM = new Coding
    {
      Code = "NLM",
      Display = "NLM",
      System = "http://hl7.org/fhir/medline-citation-owner"
    };
    /// <summary>
    /// Not used by National Library of Medicine; used by others to adapt the MEDLINE DTD for other applications.
    /// </summary>
    public static readonly Coding NOTNLM = new Coding
    {
      Code = "NOTNLM",
      Display = "NOTNLM",
      System = "http://hl7.org/fhir/medline-citation-owner"
    };
    /// <summary>
    /// Population Information Program, Johns Hopkins School of Public Health.
    /// </summary>
    public static readonly Coding PIP = new Coding
    {
      Code = "PIP",
      Display = "PIP",
      System = "http://hl7.org/fhir/medline-citation-owner"
    };
    /// <summary>
    /// Specialized Information Services Division, National Library of Medicine.
    /// </summary>
    public static readonly Coding SIS = new Coding
    {
      Code = "SIS",
      Display = "SIS",
      System = "http://hl7.org/fhir/medline-citation-owner"
    };

    /// <summary>
    /// Literal for code: HMD
    /// </summary>
    public const string LiteralHMD = "HMD";

    /// <summary>
    /// Literal for code: HSR
    /// </summary>
    public const string LiteralHSR = "HSR";

    /// <summary>
    /// Literal for code: KIE
    /// </summary>
    public const string LiteralKIE = "KIE";

    /// <summary>
    /// Literal for code: NASA
    /// </summary>
    public const string LiteralNASA = "NASA";

    /// <summary>
    /// Literal for code: NLM
    /// </summary>
    public const string LiteralNLM = "NLM";

    /// <summary>
    /// Literal for code: NOTNLM
    /// </summary>
    public const string LiteralNOTNLM = "NOTNLM";

    /// <summary>
    /// Literal for code: PIP
    /// </summary>
    public const string LiteralPIP = "PIP";

    /// <summary>
    /// Literal for code: SIS
    /// </summary>
    public const string LiteralSIS = "SIS";
  };
}
