// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// A set of codes each of which specifies a certain subcategory of the name part in addition to the main name part type.
  /// </summary>
  public static class NamePartQualifierCodes
  {
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Academic = new Coding
    {
      Code = "AC",
      Display = "Academic",
      System = "http://terminology.hl7.org/CodeSystem/v3-EntityNamePartQualifierR2"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Acquired = new Coding
    {
      Code = "AD",
      Display = "Acquired",
      System = "http://terminology.hl7.org/CodeSystem/v3-EntityNamePartQualifierR2"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Birth = new Coding
    {
      Code = "BR",
      Display = "Birth",
      System = "http://terminology.hl7.org/CodeSystem/v3-EntityNamePartQualifierR2"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CallMe = new Coding
    {
      Code = "CL",
      Display = "Call me",
      System = "http://terminology.hl7.org/CodeSystem/v3-EntityNamePartQualifierR2"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Honorific = new Coding
    {
      Code = "HON",
      Display = "Honorific",
      System = "http://terminology.hl7.org/CodeSystem/v3-EntityNamePartQualifierR2"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Initial = new Coding
    {
      Code = "IN",
      Display = "Initial",
      System = "http://terminology.hl7.org/CodeSystem/v3-EntityNamePartQualifierR2"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding LegalStatus = new Coding
    {
      Code = "LS",
      Display = "Legal status",
      System = "http://terminology.hl7.org/CodeSystem/v3-EntityNamePartQualifierR2"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MiddleName = new Coding
    {
      Code = "MID",
      Display = "Middle Name",
      System = "http://terminology.hl7.org/CodeSystem/v3-EntityNamePartQualifierR2"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Nobility = new Coding
    {
      Code = "NB",
      Display = "Nobility",
      System = "http://terminology.hl7.org/CodeSystem/v3-EntityNamePartQualifierR2"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Professional = new Coding
    {
      Code = "PR",
      Display = "Professional",
      System = "http://terminology.hl7.org/CodeSystem/v3-EntityNamePartQualifierR2"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Spouse = new Coding
    {
      Code = "SP",
      Display = "Spouse",
      System = "http://terminology.hl7.org/CodeSystem/v3-EntityNamePartQualifierR2"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Voorvoegsel = new Coding
    {
      Code = "VV",
      Display = "Voorvoegsel",
      System = "http://terminology.hl7.org/CodeSystem/v3-EntityNamePartQualifier"
    };

    /// <summary>
    /// Literal for code: Academic
    /// </summary>
    public const string LiteralAcademic = "AC";

    /// <summary>
    /// Literal for code: Acquired
    /// </summary>
    public const string LiteralAcquired = "AD";

    /// <summary>
    /// Literal for code: Birth
    /// </summary>
    public const string LiteralBirth = "BR";

    /// <summary>
    /// Literal for code: CallMe
    /// </summary>
    public const string LiteralCallMe = "CL";

    /// <summary>
    /// Literal for code: Honorific
    /// </summary>
    public const string LiteralHonorific = "HON";

    /// <summary>
    /// Literal for code: Initial
    /// </summary>
    public const string LiteralInitial = "IN";

    /// <summary>
    /// Literal for code: LegalStatus
    /// </summary>
    public const string LiteralLegalStatus = "LS";

    /// <summary>
    /// Literal for code: MiddleName
    /// </summary>
    public const string LiteralMiddleName = "MID";

    /// <summary>
    /// Literal for code: Nobility
    /// </summary>
    public const string LiteralNobility = "NB";

    /// <summary>
    /// Literal for code: Professional
    /// </summary>
    public const string LiteralProfessional = "PR";

    /// <summary>
    /// Literal for code: Spouse
    /// </summary>
    public const string LiteralSpouse = "SP";

    /// <summary>
    /// Literal for code: Voorvoegsel
    /// </summary>
    public const string LiteralVoorvoegsel = "VV";
  };
}
