// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// A code that represents the preferred display order of the components of a human name.
  /// </summary>
  public static class NameAssemblyOrderCodes
  {
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PrefixFamilyGivenSuffix = new Coding
    {
      Code = "F",
      Display = "Prefix Family Given Suffix",
      System = "http://terminology.hl7.org/CodeSystem/v2-0444"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PrefixGivenFamilySuffix = new Coding
    {
      Code = "G",
      Display = "Prefix Given Family Suffix",
      System = "http://terminology.hl7.org/CodeSystem/v2-0444"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding OwnName = new Coding
    {
      Code = "NL1",
      Display = "Own Name",
      System = "http://terminology.hl7.org/CodeSystem/name-assembly-order"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PartnerName = new Coding
    {
      Code = "NL2",
      Display = "Partner Name",
      System = "http://terminology.hl7.org/CodeSystem/name-assembly-order"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PartnerNameFollowedByMaidenName = new Coding
    {
      Code = "NL3",
      Display = "Partner Name followed by Maiden Name",
      System = "http://terminology.hl7.org/CodeSystem/name-assembly-order"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding OwnNameFollowedByPartnerName = new Coding
    {
      Code = "NL4",
      Display = "Own Name followed by Partner Name",
      System = "http://terminology.hl7.org/CodeSystem/name-assembly-order"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Unknown = new Coding
    {
      Code = "UNK",
      Display = "Unknown",
      System = "http://terminology.hl7.org/CodeSystem/v3-NullFlavor"
    };

    /// <summary>
    /// Literal for code: PrefixFamilyGivenSuffix
    /// </summary>
    public const string LiteralPrefixFamilyGivenSuffix = "F";

    /// <summary>
    /// Literal for code: PrefixGivenFamilySuffix
    /// </summary>
    public const string LiteralPrefixGivenFamilySuffix = "G";

    /// <summary>
    /// Literal for code: OwnName
    /// </summary>
    public const string LiteralOwnName = "NL1";

    /// <summary>
    /// Literal for code: PartnerName
    /// </summary>
    public const string LiteralPartnerName = "NL2";

    /// <summary>
    /// Literal for code: PartnerNameFollowedByMaidenName
    /// </summary>
    public const string LiteralPartnerNameFollowedByMaidenName = "NL3";

    /// <summary>
    /// Literal for code: OwnNameFollowedByPartnerName
    /// </summary>
    public const string LiteralOwnNameFollowedByPartnerName = "NL4";

    /// <summary>
    /// Literal for code: Unknown
    /// </summary>
    public const string LiteralUnknown = "UNK";
  };
}
