// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// This value set indicates the allowed vital sign result types.   The LOINC code for Vitals Signs panel (85353-1) is a grouping structure for a set of vital signs and includes related links (with type=has-member) to the Observations in this set (e.g. respiratory rate, heart rate, BP).  The Blood pressure panel (85354-9) is used to group the component observations Systolic blood pressure (8480-6) and Diastolic blood pressure (8462-4).
  /// </summary>
  public static class ObservationVitalsignresultCodes
  {
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VAL27086 = new Coding
    {
      Code = "2708-6",
      System = "http://loinc.org"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VAL294637 = new Coding
    {
      Code = "29463-7",
      System = "http://loinc.org"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VAL391565 = new Coding
    {
      Code = "39156-5",
      System = "http://loinc.org"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VAL83022 = new Coding
    {
      Code = "8302-2",
      System = "http://loinc.org"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VAL83105 = new Coding
    {
      Code = "8310-5",
      System = "http://loinc.org"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VAL84624 = new Coding
    {
      Code = "8462-4",
      System = "http://loinc.org"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VAL84780 = new Coding
    {
      Code = "8478-0",
      System = "http://loinc.org"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VAL84806 = new Coding
    {
      Code = "8480-6",
      System = "http://loinc.org"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VAL853531 = new Coding
    {
      Code = "85353-1",
      System = "http://loinc.org"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VAL853549 = new Coding
    {
      Code = "85354-9",
      System = "http://loinc.org"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VAL88674 = new Coding
    {
      Code = "8867-4",
      System = "http://loinc.org"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VAL92791 = new Coding
    {
      Code = "9279-1",
      System = "http://loinc.org"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VAL98434 = new Coding
    {
      Code = "9843-4",
      System = "http://loinc.org"
    };

    /// <summary>
    /// Literal for code: VAL27086
    /// </summary>
    public const string LiteralVAL27086 = "2708-6";

    /// <summary>
    /// Literal for code: VAL294637
    /// </summary>
    public const string LiteralVAL294637 = "29463-7";

    /// <summary>
    /// Literal for code: VAL391565
    /// </summary>
    public const string LiteralVAL391565 = "39156-5";

    /// <summary>
    /// Literal for code: VAL83022
    /// </summary>
    public const string LiteralVAL83022 = "8302-2";

    /// <summary>
    /// Literal for code: VAL83105
    /// </summary>
    public const string LiteralVAL83105 = "8310-5";

    /// <summary>
    /// Literal for code: VAL84624
    /// </summary>
    public const string LiteralVAL84624 = "8462-4";

    /// <summary>
    /// Literal for code: VAL84780
    /// </summary>
    public const string LiteralVAL84780 = "8478-0";

    /// <summary>
    /// Literal for code: VAL84806
    /// </summary>
    public const string LiteralVAL84806 = "8480-6";

    /// <summary>
    /// Literal for code: VAL853531
    /// </summary>
    public const string LiteralVAL853531 = "85353-1";

    /// <summary>
    /// Literal for code: VAL853549
    /// </summary>
    public const string LiteralVAL853549 = "85354-9";

    /// <summary>
    /// Literal for code: VAL88674
    /// </summary>
    public const string LiteralVAL88674 = "8867-4";

    /// <summary>
    /// Literal for code: VAL92791
    /// </summary>
    public const string LiteralVAL92791 = "9279-1";

    /// <summary>
    /// Literal for code: VAL98434
    /// </summary>
    public const string LiteralVAL98434 = "9843-4";
  };
}
