// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// The types of involvement of the performer in the Event.
  /// </summary>
  public static class PerformerFunctionCodes
  {
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ATND = new Coding
    {
      Code = "ATND",
      System = "http://terminology.hl7.org/CodeSystem/v3-ParticipationType"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding AUT = new Coding
    {
      Code = "AUT",
      System = "http://terminology.hl7.org/CodeSystem/v3-ParticipationType"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding AUTHEN = new Coding
    {
      Code = "AUTHEN",
      System = "http://terminology.hl7.org/CodeSystem/v3-ParticipationType"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CON = new Coding
    {
      Code = "CON",
      System = "http://terminology.hl7.org/CodeSystem/v3-ParticipationType"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ENT = new Coding
    {
      Code = "ENT",
      System = "http://terminology.hl7.org/CodeSystem/v3-ParticipationType"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding INF = new Coding
    {
      Code = "INF",
      System = "http://terminology.hl7.org/CodeSystem/v3-ParticipationType"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding LA = new Coding
    {
      Code = "LA",
      System = "http://terminology.hl7.org/CodeSystem/v3-ParticipationType"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PART = new Coding
    {
      Code = "PART",
      System = "http://terminology.hl7.org/CodeSystem/v3-ParticipationType"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PPRF = new Coding
    {
      Code = "PPRF",
      System = "http://terminology.hl7.org/CodeSystem/v3-ParticipationType"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding RESP = new Coding
    {
      Code = "RESP",
      System = "http://terminology.hl7.org/CodeSystem/v3-ParticipationType"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding SPRF = new Coding
    {
      Code = "SPRF",
      System = "http://terminology.hl7.org/CodeSystem/v3-ParticipationType"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding TRANS = new Coding
    {
      Code = "TRANS",
      System = "http://terminology.hl7.org/CodeSystem/v3-ParticipationType"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VRF = new Coding
    {
      Code = "VRF",
      System = "http://terminology.hl7.org/CodeSystem/v3-ParticipationType"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding WIT = new Coding
    {
      Code = "WIT",
      System = "http://terminology.hl7.org/CodeSystem/v3-ParticipationType"
    };

    /// <summary>
    /// Literal for code: ATND
    /// </summary>
    public const string LiteralATND = "ATND";

    /// <summary>
    /// Literal for code: AUT
    /// </summary>
    public const string LiteralAUT = "AUT";

    /// <summary>
    /// Literal for code: AUTHEN
    /// </summary>
    public const string LiteralAUTHEN = "AUTHEN";

    /// <summary>
    /// Literal for code: CON
    /// </summary>
    public const string LiteralCON = "CON";

    /// <summary>
    /// Literal for code: ENT
    /// </summary>
    public const string LiteralENT = "ENT";

    /// <summary>
    /// Literal for code: INF
    /// </summary>
    public const string LiteralINF = "INF";

    /// <summary>
    /// Literal for code: LA
    /// </summary>
    public const string LiteralLA = "LA";

    /// <summary>
    /// Literal for code: PART
    /// </summary>
    public const string LiteralPART = "PART";

    /// <summary>
    /// Literal for code: PPRF
    /// </summary>
    public const string LiteralPPRF = "PPRF";

    /// <summary>
    /// Literal for code: RESP
    /// </summary>
    public const string LiteralRESP = "RESP";

    /// <summary>
    /// Literal for code: SPRF
    /// </summary>
    public const string LiteralSPRF = "SPRF";

    /// <summary>
    /// Literal for code: TRANS
    /// </summary>
    public const string LiteralTRANS = "TRANS";

    /// <summary>
    /// Literal for code: VRF
    /// </summary>
    public const string LiteralVRF = "VRF";

    /// <summary>
    /// Literal for code: WIT
    /// </summary>
    public const string LiteralWIT = "WIT";
  };
}
