// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// Uses of an address not included in Address.use.
  /// </summary>
  public static class PostalAddressUseCodes
  {
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding BadAddress = new Coding
    {
      Code = "BAD",
      Display = "bad address",
      System = "http://terminology.hl7.org/CodeSystem/v3-AddressUse"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ConfidentialAddress = new Coding
    {
      Code = "CONF",
      Display = "confidential address",
      System = "http://terminology.hl7.org/CodeSystem/v3-AddressUse"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Direct = new Coding
    {
      Code = "DIR",
      Display = "direct",
      System = "http://terminology.hl7.org/CodeSystem/v3-AddressUse"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PrimaryHome = new Coding
    {
      Code = "HP",
      Display = "primary home",
      System = "http://terminology.hl7.org/CodeSystem/v3-AddressUse"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VacationHome = new Coding
    {
      Code = "HV",
      Display = "vacation home",
      System = "http://terminology.hl7.org/CodeSystem/v3-AddressUse"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PhysicalVisitAddress = new Coding
    {
      Code = "PHYS",
      Display = "physical visit address",
      System = "http://terminology.hl7.org/CodeSystem/v3-AddressUse"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PostalAddress = new Coding
    {
      Code = "PST",
      Display = "postal address",
      System = "http://terminology.hl7.org/CodeSystem/v3-AddressUse"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding VALPublic = new Coding
    {
      Code = "PUB",
      Display = "public",
      System = "http://terminology.hl7.org/CodeSystem/v3-AddressUse"
    };

    /// <summary>
    /// Literal for code: BadAddress
    /// </summary>
    public const string LiteralBadAddress = "BAD";

    /// <summary>
    /// Literal for code: ConfidentialAddress
    /// </summary>
    public const string LiteralConfidentialAddress = "CONF";

    /// <summary>
    /// Literal for code: Direct
    /// </summary>
    public const string LiteralDirect = "DIR";

    /// <summary>
    /// Literal for code: PrimaryHome
    /// </summary>
    public const string LiteralPrimaryHome = "HP";

    /// <summary>
    /// Literal for code: VacationHome
    /// </summary>
    public const string LiteralVacationHome = "HV";

    /// <summary>
    /// Literal for code: PhysicalVisitAddress
    /// </summary>
    public const string LiteralPhysicalVisitAddress = "PHYS";

    /// <summary>
    /// Literal for code: PostalAddress
    /// </summary>
    public const string LiteralPostalAddress = "PST";

    /// <summary>
    /// Literal for code: VALPublic
    /// </summary>
    public const string LiteralVALPublic = "PUB";
  };
}
