// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// To identify the medium/media in which the cited article is published, eg print, electronic or print-electronic.
  /// </summary>
  public static class PublishingModelTypeCodes
  {
    /// <summary>
    /// Journal in electronic format only (see https://www.nlm.nih.gov/bsd/licensee/elements_descriptions.html#article).
    /// </summary>
    public static readonly Coding Electronic = new Coding
    {
      Code = "Electronic",
      Display = "Electronic",
      System = "http://terminology.hl7.org/CodeSystem/publishing-model-type"
    };
    /// <summary>
    /// Electronic-only journal that publishes individual articles then later collects with issue date (see https://www.nlm.nih.gov/bsd/licensee/elements_descriptions.html#article).
    /// </summary>
    public static readonly Coding EletronicECollection = new Coding
    {
      Code = "Eletronic-eCollection",
      Display = "Eletronic-eCollection",
      System = "http://terminology.hl7.org/CodeSystem/publishing-model-type"
    };
    /// <summary>
    /// Journal in print only (see https://www.nlm.nih.gov/bsd/licensee/elements_descriptions.html#article).
    /// </summary>
    public static readonly Coding Print = new Coding
    {
      Code = "Print",
      Display = "Print",
      System = "http://terminology.hl7.org/CodeSystem/publishing-model-type"
    };
    /// <summary>
    /// Journal in print and electronic formats (see https://www.nlm.nih.gov/bsd/licensee/elements_descriptions.html#article).
    /// </summary>
    public static readonly Coding PrintElectronic = new Coding
    {
      Code = "Print-Electronic",
      Display = "Print-Electronic",
      System = "http://terminology.hl7.org/CodeSystem/publishing-model-type"
    };

    /// <summary>
    /// Literal for code: Electronic
    /// </summary>
    public const string LiteralElectronic = "Electronic";

    /// <summary>
    /// Literal for code: EletronicECollection
    /// </summary>
    public const string LiteralEletronicECollection = "Eletronic-eCollection";

    /// <summary>
    /// Literal for code: Print
    /// </summary>
    public const string LiteralPrint = "Print";

    /// <summary>
    /// Literal for code: PrintElectronic
    /// </summary>
    public const string LiteralPrintElectronic = "Print-Electronic";
  };
}
