// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// PubMed Publication Status.
  /// </summary>
  public static class PubmedPubstatusCodes
  {
    /// <summary>
    /// Used as the value of PublicationStatus or attribute of PubmedPubDate in MEDLINE DTD.
    /// </summary>
    public static readonly Coding Accepted = new Coding
    {
      Code = "accepted",
      Display = "accepted",
      System = "http://hl7.org/fhir/pubmed-pubstatus"
    };
    /// <summary>
    /// Used as the value of PublicationStatus or attribute of PubmedPubDate in MEDLINE DTD.
    /// </summary>
    public static readonly Coding Aheadofprint = new Coding
    {
      Code = "aheadofprint",
      Display = "aheadofprint",
      System = "http://hl7.org/fhir/pubmed-pubstatus"
    };
    /// <summary>
    /// Used as the value of PublicationStatus or attribute of PubmedPubDate in MEDLINE DTD.
    /// </summary>
    public static readonly Coding Ecollection = new Coding
    {
      Code = "ecollection",
      Display = "ecollection",
      System = "http://hl7.org/fhir/pubmed-pubstatus"
    };
    /// <summary>
    /// Used as the value of PublicationStatus or attribute of PubmedPubDate in MEDLINE DTD.
    /// </summary>
    public static readonly Coding Entrez = new Coding
    {
      Code = "entrez",
      Display = "entrez",
      System = "http://hl7.org/fhir/pubmed-pubstatus"
    };
    /// <summary>
    /// Used as the value of PublicationStatus or attribute of PubmedPubDate in MEDLINE DTD.
    /// </summary>
    public static readonly Coding Epublish = new Coding
    {
      Code = "epublish",
      Display = "epublish",
      System = "http://hl7.org/fhir/pubmed-pubstatus"
    };
    /// <summary>
    /// Used as the value of PublicationStatus or attribute of PubmedPubDate in MEDLINE DTD.
    /// </summary>
    public static readonly Coding Medline = new Coding
    {
      Code = "medline",
      Display = "medline",
      System = "http://hl7.org/fhir/pubmed-pubstatus"
    };
    /// <summary>
    /// Used as the value of PublicationStatus or attribute of PubmedPubDate in MEDLINE DTD.
    /// </summary>
    public static readonly Coding Medliner = new Coding
    {
      Code = "medliner",
      Display = "medliner",
      System = "http://hl7.org/fhir/pubmed-pubstatus"
    };
    /// <summary>
    /// Used as the value of PublicationStatus or attribute of PubmedPubDate in MEDLINE DTD.
    /// </summary>
    public static readonly Coding Pmc = new Coding
    {
      Code = "pmc",
      Display = "pmc",
      System = "http://hl7.org/fhir/pubmed-pubstatus"
    };
    /// <summary>
    /// Used as the value of PublicationStatus or attribute of PubmedPubDate in MEDLINE DTD.
    /// </summary>
    public static readonly Coding Pmcr = new Coding
    {
      Code = "pmcr",
      Display = "pmcr",
      System = "http://hl7.org/fhir/pubmed-pubstatus"
    };
    /// <summary>
    /// Used as the value of PublicationStatus or attribute of PubmedPubDate in MEDLINE DTD.
    /// </summary>
    public static readonly Coding PmcRelease = new Coding
    {
      Code = "pmc-release",
      Display = "pmc-release",
      System = "http://hl7.org/fhir/pubmed-pubstatus"
    };
    /// <summary>
    /// Used as the value of PublicationStatus or attribute of PubmedPubDate in MEDLINE DTD.
    /// </summary>
    public static readonly Coding Ppublish = new Coding
    {
      Code = "ppublish",
      Display = "ppublish",
      System = "http://hl7.org/fhir/pubmed-pubstatus"
    };
    /// <summary>
    /// Used as the value of PublicationStatus or attribute of PubmedPubDate in MEDLINE DTD.
    /// </summary>
    public static readonly Coding Premedline = new Coding
    {
      Code = "premedline",
      Display = "premedline",
      System = "http://hl7.org/fhir/pubmed-pubstatus"
    };
    /// <summary>
    /// Used as the value of PublicationStatus or attribute of PubmedPubDate in MEDLINE DTD.
    /// </summary>
    public static readonly Coding Pubmed = new Coding
    {
      Code = "pubmed",
      Display = "pubmed",
      System = "http://hl7.org/fhir/pubmed-pubstatus"
    };
    /// <summary>
    /// Used as the value of PublicationStatus or attribute of PubmedPubDate in MEDLINE DTD.
    /// </summary>
    public static readonly Coding Pubmedr = new Coding
    {
      Code = "pubmedr",
      Display = "pubmedr",
      System = "http://hl7.org/fhir/pubmed-pubstatus"
    };
    /// <summary>
    /// Used as the value of PublicationStatus or attribute of PubmedPubDate in MEDLINE DTD.
    /// </summary>
    public static readonly Coding Received = new Coding
    {
      Code = "received",
      Display = "received",
      System = "http://hl7.org/fhir/pubmed-pubstatus"
    };
    /// <summary>
    /// Used as the value of PublicationStatus or attribute of PubmedPubDate in MEDLINE DTD.
    /// </summary>
    public static readonly Coding Retracted = new Coding
    {
      Code = "retracted",
      Display = "retracted",
      System = "http://hl7.org/fhir/pubmed-pubstatus"
    };
    /// <summary>
    /// Used as the value of PublicationStatus or attribute of PubmedPubDate in MEDLINE DTD.
    /// </summary>
    public static readonly Coding Revised = new Coding
    {
      Code = "revised",
      Display = "revised",
      System = "http://hl7.org/fhir/pubmed-pubstatus"
    };

    /// <summary>
    /// Literal for code: Accepted
    /// </summary>
    public const string LiteralAccepted = "accepted";

    /// <summary>
    /// Literal for code: Aheadofprint
    /// </summary>
    public const string LiteralAheadofprint = "aheadofprint";

    /// <summary>
    /// Literal for code: Ecollection
    /// </summary>
    public const string LiteralEcollection = "ecollection";

    /// <summary>
    /// Literal for code: Entrez
    /// </summary>
    public const string LiteralEntrez = "entrez";

    /// <summary>
    /// Literal for code: Epublish
    /// </summary>
    public const string LiteralEpublish = "epublish";

    /// <summary>
    /// Literal for code: Medline
    /// </summary>
    public const string LiteralMedline = "medline";

    /// <summary>
    /// Literal for code: Medliner
    /// </summary>
    public const string LiteralMedliner = "medliner";

    /// <summary>
    /// Literal for code: Pmc
    /// </summary>
    public const string LiteralPmc = "pmc";

    /// <summary>
    /// Literal for code: Pmcr
    /// </summary>
    public const string LiteralPmcr = "pmcr";

    /// <summary>
    /// Literal for code: PmcRelease
    /// </summary>
    public const string LiteralPmcRelease = "pmc-release";

    /// <summary>
    /// Literal for code: Ppublish
    /// </summary>
    public const string LiteralPpublish = "ppublish";

    /// <summary>
    /// Literal for code: Premedline
    /// </summary>
    public const string LiteralPremedline = "premedline";

    /// <summary>
    /// Literal for code: Pubmed
    /// </summary>
    public const string LiteralPubmed = "pubmed";

    /// <summary>
    /// Literal for code: Pubmedr
    /// </summary>
    public const string LiteralPubmedr = "pubmedr";

    /// <summary>
    /// Literal for code: Received
    /// </summary>
    public const string LiteralReceived = "received";

    /// <summary>
    /// Literal for code: Retracted
    /// </summary>
    public const string LiteralRetracted = "retracted";

    /// <summary>
    /// Literal for code: Revised
    /// </summary>
    public const string LiteralRevised = "revised";
  };
}
