// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// A rating system that describes the strength of the recommendation, such as the GRADE, DynaMed, or HGPS systems.
  /// </summary>
  public static class RecommendationStrengthCodes
  {
    /// <summary>
    /// Strong recommendation.
    /// </summary>
    public static readonly Coding Strong = new Coding
    {
      Code = "strong",
      Display = "Strong",
      System = "http://terminology.hl7.org/CodeSystem/recommendation-strength"
    };
    /// <summary>
    /// Weak recommendation.
    /// </summary>
    public static readonly Coding Weak = new Coding
    {
      Code = "weak",
      Display = "Weak",
      System = "http://terminology.hl7.org/CodeSystem/recommendation-strength"
    };

    /// <summary>
    /// Literal for code: Strong
    /// </summary>
    public const string LiteralStrong = "strong";

    /// <summary>
    /// Literal for code: Weak
    /// </summary>
    public const string LiteralWeak = "weak";
  };
}
