// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// Codes to denote a guideline or policy statement.when a genetic test result is being shared as a secondary finding.
  /// </summary>
  public static class SecondaryFindingCodes
  {
    /// <summary>
    /// First release (2013): ACMG Recommendations for Reporting of Incidental Findings in Clinical Exome and Genome Sequencing.  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3727274/
    /// </summary>
    public static readonly Coding ACMGVersion1 = new Coding
    {
      Code = "acmg-version1",
      Display = "ACMG Version 1",
      System = "http://hl7.org/fhir/secondary-finding"
    };
    /// <summary>
    /// Second release (2016): Recommendations for reporting of secondary findings in clinical exome and genome sequencing, 2016 update (ACMG SF v2.0): a policy statement of the American College of Medical Genetics and Genomics. https://www.ncbi.nlm.nih.gov/pubmed/27854360
    /// </summary>
    public static readonly Coding ACMGVersion2 = new Coding
    {
      Code = "acmg-version2",
      Display = "ACMG Version 2",
      System = "http://hl7.org/fhir/secondary-finding"
    };

    /// <summary>
    /// Literal for code: ACMGVersion1
    /// </summary>
    public const string LiteralACMGVersion1 = "acmg-version1";

    /// <summary>
    /// Literal for code: ACMGVersion2
    /// </summary>
    public const string LiteralACMGVersion2 = "acmg-version2";
  };
}
