// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// Containers which may hold specimens or specimen containers. Include codes  SNOMED CT(http://snomed.info/sct) where concept is-a 434711009 (Specimen container (physical object))
  /// </summary>
  public static class SpecimenContainerTypeCodes
  {
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding SpecimenContainer = new Coding
    {
      Code = "434711009",
      Display = "Specimen container",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding SpecimenVial = new Coding
    {
      Code = "434746001",
      Display = "Specimen vial",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding SpecimenWell = new Coding
    {
      Code = "434822004",
      Display = "Specimen well",
      System = "http://snomed.info/sct"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding BreathSpecimenContainer = new Coding
    {
      Code = "713791004",
      Display = "Breath specimen container",
      System = "http://snomed.info/sct"
    };

    /// <summary>
    /// Literal for code: SpecimenContainer
    /// </summary>
    public const string LiteralSpecimenContainer = "434711009";

    /// <summary>
    /// Literal for code: SpecimenVial
    /// </summary>
    public const string LiteralSpecimenVial = "434746001";

    /// <summary>
    /// Literal for code: SpecimenWell
    /// </summary>
    public const string LiteralSpecimenWell = "434822004";

    /// <summary>
    /// Literal for code: BreathSpecimenContainer
    /// </summary>
    public const string LiteralBreathSpecimenContainer = "713791004";
  };
}
