// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  ///  This example value set defines a set of codes that can be used to indicate the priority of collection of a specimen.
  /// </summary>
  public static class SpecimenCollectionPriorityCodes
  {
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding STAT = new Coding
    {
      Code = "1",
      Display = "STAT",
      System = "http://example.com"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ASAP = new Coding
    {
      Code = "2",
      Display = "ASAP",
      System = "http://example.com"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ASAPED = new Coding
    {
      Code = "3",
      Display = "ASAP-ED",
      System = "http://example.com"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding AM = new Coding
    {
      Code = "4",
      Display = "AM",
      System = "http://example.com"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding ROUTINE = new Coding
    {
      Code = "5",
      Display = "ROUTINE",
      System = "http://example.com"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding NURSECOLLECT = new Coding
    {
      Code = "6",
      Display = "NURSE COLLECT",
      System = "http://example.com"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding CALLORFAX = new Coding
    {
      Code = "7",
      Display = "CALL OR FAX",
      System = "http://example.com"
    };

    /// <summary>
    /// Literal for code: STAT
    /// </summary>
    public const string LiteralSTAT = "1";

    /// <summary>
    /// Literal for code: ASAP
    /// </summary>
    public const string LiteralASAP = "2";

    /// <summary>
    /// Literal for code: ASAPED
    /// </summary>
    public const string LiteralASAPED = "3";

    /// <summary>
    /// Literal for code: AM
    /// </summary>
    public const string LiteralAM = "4";

    /// <summary>
    /// Literal for code: ROUTINE
    /// </summary>
    public const string LiteralROUTINE = "5";

    /// <summary>
    /// Literal for code: NURSECOLLECT
    /// </summary>
    public const string LiteralNURSECOLLECT = "6";

    /// <summary>
    /// Literal for code: CALLORFAX
    /// </summary>
    public const string LiteralCALLORFAX = "7";
  };
}
