// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// Statistic Model Method.
  /// </summary>
  public static class StatisticModelMethodCodes
  {
    /// <summary>
    /// Generalized linear mixed model (GLMM) method for pooling in meta-analysis.
    /// </summary>
    public static readonly Coding GeneralizedLinearMixedModelGLMM = new Coding
    {
      Code = "poolGeneralizedLinearMixedModel",
      Display = "Generalized linear mixed model (GLMM)",
      System = "http://terminology.hl7.org/CodeSystem/statistic-model-method"
    };
    /// <summary>
    /// Inverse variance method for pooling in meta-analysis.
    /// </summary>
    public static readonly Coding InverseVarianceMethod = new Coding
    {
      Code = "poolInverseVariance",
      Display = "Inverse variance method",
      System = "http://terminology.hl7.org/CodeSystem/statistic-model-method"
    };
    /// <summary>
    /// Mantel-Haenszel method for pooling in meta-analysis.
    /// </summary>
    public static readonly Coding MantelHaenszelMethod = new Coding
    {
      Code = "poolMantelHaenzsel",
      Display = "Mantel-Haenszel method",
      System = "http://terminology.hl7.org/CodeSystem/statistic-model-method"
    };
    /// <summary>
    /// Peto method for pooling in meta-analysis.
    /// </summary>
    public static readonly Coding PetoMethod = new Coding
    {
      Code = "poolPeto",
      Display = "Peto method",
      System = "http://terminology.hl7.org/CodeSystem/statistic-model-method"
    };
    /// <summary>
    /// Dersimonian-Laird method for tau squared.
    /// </summary>
    public static readonly Coding DersimonianLairdMethod = new Coding
    {
      Code = "tauDersimonianLaird",
      Display = "Dersimonian-Laird method",
      System = "http://terminology.hl7.org/CodeSystem/statistic-model-method"
    };
    /// <summary>
    /// Empirical Bayes method for tau squared.
    /// </summary>
    public static readonly Coding EmpiricalBayesMethod = new Coding
    {
      Code = "tauEmpiricalBayes",
      Display = "Empirical Bayes method",
      System = "http://terminology.hl7.org/CodeSystem/statistic-model-method"
    };
    /// <summary>
    /// Hedges method for tau squared.
    /// </summary>
    public static readonly Coding HedgesMethod = new Coding
    {
      Code = "tauHedges",
      Display = "Hedges method",
      System = "http://terminology.hl7.org/CodeSystem/statistic-model-method"
    };
    /// <summary>
    /// Hunter-Schmidt method for tau squared.
    /// </summary>
    public static readonly Coding HunterSchmidtMethod = new Coding
    {
      Code = "tauHunterSchmidt",
      Display = "Hunter-Schmidt method",
      System = "http://terminology.hl7.org/CodeSystem/statistic-model-method"
    };
    /// <summary>
    /// Maximum Likelihood method for tau squared.
    /// </summary>
    public static readonly Coding MaximumLikelihoodMethod = new Coding
    {
      Code = "tauMaximumLikelihood",
      Display = "Maximum Likelihood method",
      System = "http://terminology.hl7.org/CodeSystem/statistic-model-method"
    };
    /// <summary>
    /// Paule-Mandel method for tau squared.
    /// </summary>
    public static readonly Coding PauleMandelMethod = new Coding
    {
      Code = "tauPauleMandel",
      Display = "Paule-Mandel method",
      System = "http://terminology.hl7.org/CodeSystem/statistic-model-method"
    };
    /// <summary>
    /// Restricted Maximum Likelihood method for tau squared.
    /// </summary>
    public static readonly Coding RestrictedMaximumLikelihoodMethod = new Coding
    {
      Code = "tauRestrictedMaximumLikelihood",
      Display = "Restricted Maximum Likelihood method",
      System = "http://terminology.hl7.org/CodeSystem/statistic-model-method"
    };
    /// <summary>
    /// Sidik-Jonkman method for tau squared.
    /// </summary>
    public static readonly Coding SidikJonkmanMethod = new Coding
    {
      Code = "tauSidikJonkman",
      Display = "Sidik-Jonkman method",
      System = "http://terminology.hl7.org/CodeSystem/statistic-model-method"
    };

    /// <summary>
    /// Literal for code: GeneralizedLinearMixedModelGLMM
    /// </summary>
    public const string LiteralGeneralizedLinearMixedModelGLMM = "poolGeneralizedLinearMixedModel";

    /// <summary>
    /// Literal for code: InverseVarianceMethod
    /// </summary>
    public const string LiteralInverseVarianceMethod = "poolInverseVariance";

    /// <summary>
    /// Literal for code: MantelHaenszelMethod
    /// </summary>
    public const string LiteralMantelHaenszelMethod = "poolMantelHaenzsel";

    /// <summary>
    /// Literal for code: PetoMethod
    /// </summary>
    public const string LiteralPetoMethod = "poolPeto";

    /// <summary>
    /// Literal for code: DersimonianLairdMethod
    /// </summary>
    public const string LiteralDersimonianLairdMethod = "tauDersimonianLaird";

    /// <summary>
    /// Literal for code: EmpiricalBayesMethod
    /// </summary>
    public const string LiteralEmpiricalBayesMethod = "tauEmpiricalBayes";

    /// <summary>
    /// Literal for code: HedgesMethod
    /// </summary>
    public const string LiteralHedgesMethod = "tauHedges";

    /// <summary>
    /// Literal for code: HunterSchmidtMethod
    /// </summary>
    public const string LiteralHunterSchmidtMethod = "tauHunterSchmidt";

    /// <summary>
    /// Literal for code: MaximumLikelihoodMethod
    /// </summary>
    public const string LiteralMaximumLikelihoodMethod = "tauMaximumLikelihood";

    /// <summary>
    /// Literal for code: PauleMandelMethod
    /// </summary>
    public const string LiteralPauleMandelMethod = "tauPauleMandel";

    /// <summary>
    /// Literal for code: RestrictedMaximumLikelihoodMethod
    /// </summary>
    public const string LiteralRestrictedMaximumLikelihoodMethod = "tauRestrictedMaximumLikelihood";

    /// <summary>
    /// Literal for code: SidikJonkmanMethod
    /// </summary>
    public const string LiteralSidikJonkmanMethod = "tauSidikJonkman";
  };
}
