// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// UCUM units for recording Body Weight
  /// </summary>
  public static class UcumBodyweightCodes
  {
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding NONE = new Coding
    {
      Code = "[lb_av]",
      System = "http://unitsofmeasure.org"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding NONE_2 = new Coding
    {
      Code = "g",
      System = "http://unitsofmeasure.org"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding NONE_3 = new Coding
    {
      Code = "kg",
      System = "http://unitsofmeasure.org"
    };

    /// <summary>
    /// Literal for code: NONE
    /// </summary>
    public const string LiteralNONE = "[lb_av]";

    /// <summary>
    /// Literal for code: NONE_2
    /// </summary>
    public const string LiteralNONE_2 = "g";

    /// <summary>
    /// Literal for code: NONE_3
    /// </summary>
    public const string LiteralNONE_3 = "kg";
  };
}
