// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// Common UCUM units for recording Vital Signs
  /// </summary>
  public static class UcumVitalsCommonCodes
  {
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Percent = new Coding
    {
      Code = "%",
      Display = "percent",
      System = "http://unitsofmeasure.org"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PerMinute = new Coding
    {
      Code = "/min",
      Display = "per minute",
      System = "http://unitsofmeasure.org"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DegreeFahrenheit = new Coding
    {
      Code = "[degF]",
      Display = "degree Fahrenheit",
      System = "http://unitsofmeasure.org"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding InchInternational = new Coding
    {
      Code = "[in_i]",
      Display = "inch (international)",
      System = "http://unitsofmeasure.org"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding PoundUSAndBritish = new Coding
    {
      Code = "[lb_av]",
      Display = "pound (US and British)",
      System = "http://unitsofmeasure.org"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding DegreeCelsius = new Coding
    {
      Code = "Cel",
      Display = "degree Celsius",
      System = "http://unitsofmeasure.org"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Centimeter = new Coding
    {
      Code = "cm",
      Display = "centimeter",
      System = "http://unitsofmeasure.org"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Gram = new Coding
    {
      Code = "g",
      Display = "gram",
      System = "http://unitsofmeasure.org"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Kilogram = new Coding
    {
      Code = "kg",
      Display = "kilogram",
      System = "http://unitsofmeasure.org"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding KilogramMeterPower2 = new Coding
    {
      Code = "kg/m2",
      Display = "kilogram / (meter ^ 2)",
      System = "http://unitsofmeasure.org"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding SquareMeter = new Coding
    {
      Code = "m2",
      Display = "square meter",
      System = "http://unitsofmeasure.org"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding MillimeterOfMercury = new Coding
    {
      Code = "mm[Hg]",
      Display = "millimeter of mercury",
      System = "http://unitsofmeasure.org"
    };

    /// <summary>
    /// Literal for code: Percent
    /// </summary>
    public const string LiteralPercent = "%";

    /// <summary>
    /// Literal for code: PerMinute
    /// </summary>
    public const string LiteralPerMinute = "/min";

    /// <summary>
    /// Literal for code: DegreeFahrenheit
    /// </summary>
    public const string LiteralDegreeFahrenheit = "[degF]";

    /// <summary>
    /// Literal for code: InchInternational
    /// </summary>
    public const string LiteralInchInternational = "[in_i]";

    /// <summary>
    /// Literal for code: PoundUSAndBritish
    /// </summary>
    public const string LiteralPoundUSAndBritish = "[lb_av]";

    /// <summary>
    /// Literal for code: DegreeCelsius
    /// </summary>
    public const string LiteralDegreeCelsius = "Cel";

    /// <summary>
    /// Literal for code: Centimeter
    /// </summary>
    public const string LiteralCentimeter = "cm";

    /// <summary>
    /// Literal for code: Gram
    /// </summary>
    public const string LiteralGram = "g";

    /// <summary>
    /// Literal for code: Kilogram
    /// </summary>
    public const string LiteralKilogram = "kg";

    /// <summary>
    /// Literal for code: KilogramMeterPower2
    /// </summary>
    public const string LiteralKilogramMeterPower2 = "kg/m2";

    /// <summary>
    /// Literal for code: SquareMeter
    /// </summary>
    public const string LiteralSquareMeter = "m2";

    /// <summary>
    /// Literal for code: MillimeterOfMercury
    /// </summary>
    public const string LiteralMillimeterOfMercury = "mm[Hg]";
  };
}
