// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// This value set includes common codes from BCP-47 (http://tools.ietf.org/html/bcp47) for the purpose of writing; this value set (unlike the common languages value set) doesn't include dialects except where they are relevant for written languages
  /// </summary>
  public static class WrittenLanguageCodes
  {
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Arabic = new Coding
    {
      Code = "ar",
      Display = "Arabic",
      System = "urn:ietf:bcp:47"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Bengali = new Coding
    {
      Code = "bn",
      Display = "Bengali",
      System = "urn:ietf:bcp:47"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Czech = new Coding
    {
      Code = "cs",
      Display = "Czech",
      System = "urn:ietf:bcp:47"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Danish = new Coding
    {
      Code = "da",
      Display = "Danish",
      System = "urn:ietf:bcp:47"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding German = new Coding
    {
      Code = "de",
      Display = "German",
      System = "urn:ietf:bcp:47"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Greek = new Coding
    {
      Code = "el",
      Display = "Greek",
      System = "urn:ietf:bcp:47"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding English = new Coding
    {
      Code = "en",
      Display = "English",
      System = "urn:ietf:bcp:47"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Spanish = new Coding
    {
      Code = "es",
      Display = "Spanish",
      System = "urn:ietf:bcp:47"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Finnish = new Coding
    {
      Code = "fi",
      Display = "Finnish",
      System = "urn:ietf:bcp:47"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding French = new Coding
    {
      Code = "fr",
      Display = "French",
      System = "urn:ietf:bcp:47"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Frysian = new Coding
    {
      Code = "fy",
      Display = "Frysian",
      System = "urn:ietf:bcp:47"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Hindi = new Coding
    {
      Code = "hi",
      Display = "Hindi",
      System = "urn:ietf:bcp:47"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Croatian = new Coding
    {
      Code = "hr",
      Display = "Croatian",
      System = "urn:ietf:bcp:47"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Italian = new Coding
    {
      Code = "it",
      Display = "Italian",
      System = "urn:ietf:bcp:47"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Japanese = new Coding
    {
      Code = "ja",
      Display = "Japanese",
      System = "urn:ietf:bcp:47"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Korean = new Coding
    {
      Code = "ko",
      Display = "Korean",
      System = "urn:ietf:bcp:47"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Dutch = new Coding
    {
      Code = "nl",
      Display = "Dutch",
      System = "urn:ietf:bcp:47"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Norwegian = new Coding
    {
      Code = "no",
      Display = "Norwegian",
      System = "urn:ietf:bcp:47"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Punjabi = new Coding
    {
      Code = "pa",
      Display = "Punjabi",
      System = "urn:ietf:bcp:47"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Polish = new Coding
    {
      Code = "pl",
      Display = "Polish",
      System = "urn:ietf:bcp:47"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Portuguese = new Coding
    {
      Code = "pt",
      Display = "Portuguese",
      System = "urn:ietf:bcp:47"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Russian = new Coding
    {
      Code = "ru",
      Display = "Russian",
      System = "urn:ietf:bcp:47"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Serbian = new Coding
    {
      Code = "sr",
      Display = "Serbian",
      System = "urn:ietf:bcp:47"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Swedish = new Coding
    {
      Code = "sv",
      Display = "Swedish",
      System = "urn:ietf:bcp:47"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Telegu = new Coding
    {
      Code = "te",
      Display = "Telegu",
      System = "urn:ietf:bcp:47"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Chinese = new Coding
    {
      Code = "zh",
      Display = "Chinese",
      System = "urn:ietf:bcp:47"
    };

    /// <summary>
    /// Literal for code: Arabic
    /// </summary>
    public const string LiteralArabic = "ar";

    /// <summary>
    /// Literal for code: Bengali
    /// </summary>
    public const string LiteralBengali = "bn";

    /// <summary>
    /// Literal for code: Czech
    /// </summary>
    public const string LiteralCzech = "cs";

    /// <summary>
    /// Literal for code: Danish
    /// </summary>
    public const string LiteralDanish = "da";

    /// <summary>
    /// Literal for code: German
    /// </summary>
    public const string LiteralGerman = "de";

    /// <summary>
    /// Literal for code: Greek
    /// </summary>
    public const string LiteralGreek = "el";

    /// <summary>
    /// Literal for code: English
    /// </summary>
    public const string LiteralEnglish = "en";

    /// <summary>
    /// Literal for code: Spanish
    /// </summary>
    public const string LiteralSpanish = "es";

    /// <summary>
    /// Literal for code: Finnish
    /// </summary>
    public const string LiteralFinnish = "fi";

    /// <summary>
    /// Literal for code: French
    /// </summary>
    public const string LiteralFrench = "fr";

    /// <summary>
    /// Literal for code: Frysian
    /// </summary>
    public const string LiteralFrysian = "fy";

    /// <summary>
    /// Literal for code: Hindi
    /// </summary>
    public const string LiteralHindi = "hi";

    /// <summary>
    /// Literal for code: Croatian
    /// </summary>
    public const string LiteralCroatian = "hr";

    /// <summary>
    /// Literal for code: Italian
    /// </summary>
    public const string LiteralItalian = "it";

    /// <summary>
    /// Literal for code: Japanese
    /// </summary>
    public const string LiteralJapanese = "ja";

    /// <summary>
    /// Literal for code: Korean
    /// </summary>
    public const string LiteralKorean = "ko";

    /// <summary>
    /// Literal for code: Dutch
    /// </summary>
    public const string LiteralDutch = "nl";

    /// <summary>
    /// Literal for code: Norwegian
    /// </summary>
    public const string LiteralNorwegian = "no";

    /// <summary>
    /// Literal for code: Punjabi
    /// </summary>
    public const string LiteralPunjabi = "pa";

    /// <summary>
    /// Literal for code: Polish
    /// </summary>
    public const string LiteralPolish = "pl";

    /// <summary>
    /// Literal for code: Portuguese
    /// </summary>
    public const string LiteralPortuguese = "pt";

    /// <summary>
    /// Literal for code: Russian
    /// </summary>
    public const string LiteralRussian = "ru";

    /// <summary>
    /// Literal for code: Serbian
    /// </summary>
    public const string LiteralSerbian = "sr";

    /// <summary>
    /// Literal for code: Swedish
    /// </summary>
    public const string LiteralSwedish = "sv";

    /// <summary>
    /// Literal for code: Telegu
    /// </summary>
    public const string LiteralTelegu = "te";

    /// <summary>
    /// Literal for code: Chinese
    /// </summary>
    public const string LiteralChinese = "zh";
  };
}
