// <auto-generated />
// Built from: hl7.fhir.r4b.core version: 4.1.0
  // Option: "NAMESPACE" = "fhirCsR4"

using fhirCsR4.Models;

namespace fhirCsR4.ValueSets
{
  /// <summary>
  /// For Capturing simple yes-no-don't know answers
  /// </summary>
  public static class YesnodontknowCodes
  {
    /// <summary>
    /// The source was asked but does not know the value.
    /// </summary>
    public static readonly Coding AskedButUnknown = new Coding
    {
      Code = "asked-unknown",
      Display = "Asked But Unknown",
      System = "http://terminology.hl7.org/CodeSystem/data-absent-reason"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding No = new Coding
    {
      Code = "N",
      Display = "No",
      System = "http://terminology.hl7.org/CodeSystem/v2-0136"
    };
    /// <summary>
    /// 
    /// </summary>
    public static readonly Coding Yes = new Coding
    {
      Code = "Y",
      Display = "Yes",
      System = "http://terminology.hl7.org/CodeSystem/v2-0136"
    };

    /// <summary>
    /// Literal for code: AskedButUnknown
    /// </summary>
    public const string LiteralAskedButUnknown = "asked-unknown";

    /// <summary>
    /// Literal for code: No
    /// </summary>
    public const string LiteralNo = "N";

    /// <summary>
    /// Literal for code: Yes
    /// </summary>
    public const string LiteralYes = "Y";
  };
}
